"""Generate filled ELARA-U result tables (LaTeX) from VERIFIED data.

Sources (all leakage-free, paired-bootstrap CIs):
  experiments/elara_u/honest_benchmark.json        main/family/regret/calibration/LFO
  experiments/elara_u/learned_router_ablation.json reliability ablation (i.i.d.)
  experiments/elara_u/shift_stress_ablation.json   reliability ablation (uniform shift)
  experiments/elara_u/heterogeneous_degradation_ablation.json  (missingness)
  experiments/elara_u/natural_shift_results.json   D22 sealed natural temporal-shift

Replaces the previous generator that read the stale results.json (AUROC-inert
"stress" numbers + a vacuous all-identical ablation). Writes
docs/research/ELARA_U_RESULT_TABLES.tex. Cells needing artifacts we do not yet have
(Brier/NLL) are "--".
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
EXP = ROOT / "experiments/elara_u"
OUT = ROOT / "docs/research/ELARA_U_RESULT_TABLES.tex"

H = json.loads((EXP / "honest_benchmark.json").read_text())
CAL = json.loads((EXP / "calibration_results.json").read_text()) if (EXP / "calibration_results.json").exists() else None
SA = json.loads((EXP / "statistical_audit.json").read_text()) if (EXP / "statistical_audit.json").exists() else None
PT_AUC = {m: np.array(v, float) for m, v in H["per_task_auc"].items()}
PT_RANK = {m: np.array(v, float) for m, v in H["per_task_rank"].items()}
FAM = np.array(H["task_families"])
BEST = H["best_fixed"]                       # e.g. "fixed/KNN"
BEST_LBL = BEST.split("/")[-1] + " (best fixed)"
NTASK = H["n_tasks"]

LBL = {"stack": "ELARA-U Stack", "auto_select": "Auto-select",
       "stack_rel": "Stack + reliability gate", BEST: BEST_LBL,
       "rank_mean": "Rank-mean", "cw_mean": "CW-mean"}
HEAD = ["stack", "auto_select", "stack_rel", BEST, "rank_mean", "cw_mean"]


def tex(s):
    return str(s).replace("_", r"\_")


def boot(a, b, n=10000, seed=0):
    a, b = np.array(a, float), np.array(b, float)
    rng = np.random.default_rng(seed)
    d = [float(a[i].mean() - b[i].mean()) for i in (rng.integers(0, len(a), len(a)) for _ in range(n))]
    return a.mean() - b.mean(), float(np.percentile(d, 2.5)), float(np.percentile(d, 97.5))


def _load(name):
    p = EXP / name
    return json.loads(p.read_text()) if p.exists() else {}


def main() -> int:
    fams = sorted(set(FAM.tolist()))
    # oracle = best SINGLE detector per task (the selection ceiling; fusion may exceed it)
    oracle = np.max(np.stack([PT_AUC[m] for m in PT_AUC if m.startswith("fixed/")]), axis=0)
    L = ["% Auto-generated by emit_tables.py from VERIFIED honest_benchmark.json + ablation files.",
         f"% {NTASK} tasks, 5 families, leakage-free. Stacking beats selection; reliability "
         "routing is decisively negative (tab:ablation, incl. D22 natural shift).", ""]

    # tab:main
    L += [r"\begin{table}[t]\centering",
          r"\caption{Main result over " + f"{NTASK}" + r" tasks, 5 families (clean splits, no "
          r"test labels). Average rank among the 11 non-oracle strategies; lower rank/regret/ECE "
          r"better. The oracle is the best \emph{single} detector per task (a selection ceiling; "
          r"the stack exceeds it because fusion beats selection).}",
          r"\label{tab:main}\footnotesize", r"\begin{tabular}{lcccc}", r"\toprule",
          r"\textbf{Method} & rank & AUROC & regret & ECE \\", r"\midrule"]
    for m in HEAD:
        rank = H["average_rank"].get(m, float("nan"))
        reg = float((oracle - PT_AUC[m]).mean())
        ece = H["mean_ece"].get(m)
        ece_s = f"{ece:.3f}" if ece is not None else "--"
        reg_s = "---" if m == "stack" else f"{reg:.3f}"   # stack exceeds best-single oracle
        bold = (r"\textbf{%.2f}" % rank, r"\textbf{%.3f}" % H["mean_auroc"][m]) if m == "stack" else (f"{rank:.2f}", f"{H['mean_auroc'][m]:.3f}")
        L.append(f"{LBL[m]} & {bold[0]} & {bold[1]} & {reg_s} & {ece_s} \\\\")
    L += [r"\midrule",
          r"oracle (best single detector) & --- & " + f"{H['mean_auroc']['oracle']:.3f}" + r" & 0.000 & --- \\",
          r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    # tab:family
    L += [r"\begin{table}[t]\centering", r"\caption{Family-level mean rank (lower better).}",
          r"\label{tab:family}\footnotesize", r"\begin{tabular}{l" + "c" * len(fams) + "}",
          r"\toprule", r"\textbf{Method} & " + " & ".join(tex(f) for f in fams) + r" \\", r"\midrule"]
    for m in ["stack", "auto_select", BEST]:
        row = [f"{np.mean(PT_RANK[m][FAM == f]):.2f}" for f in fams]
        L.append(f"{LBL[m]} & " + " & ".join(row) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    # tab:winloss
    L += [r"\begin{table}[t]\centering", r"\caption{Win/tie/loss vs.\ best fixed detector "
          f"({tex(BEST_LBL)}) and negative-transfer rate (worse than rank-mean).}}",
          r"\label{tab:winloss}\footnotesize", r"\begin{tabular}{lcccc}", r"\toprule",
          r"\textbf{Method} & Wins & Ties & Losses & Neg.-transfer \\", r"\midrule"]
    for m in ["stack", "auto_select", "stack_rel"]:
        d = PT_AUC[m] - PT_AUC[BEST]
        w, t, ll = int((d > 1e-3).sum()), int((np.abs(d) <= 1e-3).sum()), int((d < -1e-3).sum())
        nt = float(np.mean(PT_AUC[m] < PT_AUC["rank_mean"] - 1e-9))
        L.append(f"{LBL[m]} & {w} & {t} & {ll} & {nt:.3f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    # tab:regret
    L += [r"\begin{table}[t]\centering", r"\caption{Regret to per-task best-single-detector "
          r"oracle (lower better; the stack can be negative as fusion exceeds the selection "
          r"ceiling).}", r"\label{tab:regret}\footnotesize", r"\begin{tabular}{lcc}", r"\toprule",
          r"\textbf{Method} & Mean regret & Worst regret \\", r"\midrule"]
    for m in ["stack", "auto_select", BEST]:
        reg = oracle - PT_AUC[m]
        L.append(f"{LBL[m]} & {reg.mean():+.4f} & {reg.max():.4f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    # tab:calib -- real Brier/NLL/ECE, raw -> isotonic-calibrated (validation-fit)
    L += [r"\begin{table}[t]\centering",
          r"\caption{Calibration: Brier, NLL, ECE as raw\,$\to$\,isotonic-calibrated "
          r"(calibrator fit on validation only). The stack has the best raw calibration; "
          r"after calibration all methods are well-calibrated.}",
          r"\label{tab:calib}\footnotesize", r"\begin{tabular}{lccc}", r"\toprule",
          r"\textbf{Method} & Brier (raw$\to$cal) & NLL (raw$\to$cal) & ECE (raw$\to$cal) \\", r"\midrule"]
    if CAL:
        for m in ["stack", "auto_select", "rank_mean"]:
            d = CAL["metrics"][m]
            L.append(f"{LBL[m]} & {d['brier_raw']:.3f}$\\to${d['brier_cal']:.3f} & "
                     f"{d['nll_raw']:.3f}$\\to${d['nll_cal']:.3f} & "
                     f"{d['ece_raw']:.3f}$\\to${d['ece_cal']:.3f} \\\\")
    else:
        for m in ["stack", "auto_select", "rank_mean"]:
            L.append(f"{LBL[m]} & -- & -- & {H['mean_ece'][m]:.3f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    # tab:lfo
    L += [r"\begin{table}[t]\centering", r"\caption{Leave-family-out: ELARA-U Stack minus "
          r"auto-select mean rank on each held-out family (negative = Stack better), "
          r"paired-bootstrap 95\% CI.}", r"\label{tab:lfo}\footnotesize",
          r"\begin{tabular}{lccc}", r"\toprule",
          r"\textbf{Held-out family} & Rank $\Delta$ & 95\% CI & Excl.\ 0 \\", r"\midrule"]
    for f in fams:
        mask = FAM == f
        if mask.sum() < 2:
            dd = float(PT_RANK["stack"][mask].mean() - PT_RANK["auto_select"][mask].mean())
            L.append(f"{tex(f)} & {dd:+.2f} & (n={int(mask.sum())}) & -- \\\\"); continue
        delta, lo, hi = boot(PT_RANK["stack"][mask], PT_RANK["auto_select"][mask])
        L.append(f"{tex(f)} & {delta:+.2f} & $[{lo:+.2f},{hi:+.2f}]$ & {'yes' if (hi<0 or lo>0) else 'no'} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    # tab:ablation -- CONSOLIDATED reliability ablation (4 regimes + gate), Holm-corrected
    ns = _load("natural_shift_results.json")   # kept for tab:natshift below
    L += [r"\begin{table}[t]\centering",
          r"\caption{\textbf{Consolidated reliability ablation (verified, Holm-corrected).} "
          r"The decisive RQ3 test across four deployment regimes plus the stack gate: does "
          r"reliability/drift signal improve over plain validation quality? $\Delta=$(with "
          r"reliability)$-$(without); $>0$ means reliability helps. $p_{\mathrm{Holm}}$ is the "
          r"two-sided CI$\to p$ value, Holm-corrected within this family. \emph{Reliability helps "
          r"in no regime after correction; the 123-task stack gate is significantly negative.}}",
          r"\label{tab:ablation}\footnotesize", r"\begin{tabular}{lccc}", r"\toprule",
          r"\textbf{Regime} & $\Delta$AUROC & 95\% CI & $p_{\mathrm{Holm}}$ (helps?) \\", r"\midrule"]
    if SA:
        for e in SA["family_B_reliability_ablation"]:
            v = "HELPS" if e["reliability_helps"] else (r"\textbf{HURTS}" if e["reliability_hurts"] else "no")
            ci = e["ci95"]
            L.append(f"{e['label']} & {e['delta']:+.3f} & $[{ci[0]:+.3f},{ci[1]:+.3f}]$ & "
                     f"{e['p_holm']:.2g} ({v}) \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}",
          r"\noindent\emph{Primary claims, Holm-corrected:} the three positive results "
          r"(Stack$>$auto-select, Stack$>$best fixed, auto-select$>$best fixed; "
          r"Table~\ref{tab:main}) all survive Holm correction ($p_{\mathrm{Holm}}<10^{-4}$).", ""]

    # tab:natshift -- D22 detail
    if ns:
        m = ns["mean_auroc"]; vs = ns["drift_stack_vs_plain_stack"]; va = ns["drift_stack_vs_auto_select"]
        L += [r"\begin{table}[t]\centering",
              r"\caption{\textbf{D22 sealed natural temporal-shift benchmark} (" + f"{ns['n_tasks']}"
              + r" UNSW attack-category tasks, train-early/test-late). Plain stacking wins; the "
              r"drift-aware (reliability) router is \emph{worse} (raw 95\% CI excludes 0). With only "
              r"$n{=}7$ tasks this does \emph{not} survive Holm correction across the ablation family "
              r"($p_{\mathrm{Holm}}{=}0.12$), but it is directionally consistent: reliability does not "
              r"help even under genuine natural shift.}",
              r"\label{tab:natshift}\footnotesize", r"\begin{tabular}{lc}", r"\toprule",
              r"\textbf{Method / contrast} & AUROC or $\Delta$ (95\% CI) \\", r"\midrule",
              f"Auto-select & {m['auto_select']:.3f} \\\\",
              f"Plain stack & \\textbf{{{m['plain_stack']:.3f}}} \\\\",
              f"Drift-aware (reliability) stack & {m['drift_stack']:.3f} \\\\", r"\midrule",
              f"drift $-$ plain stack & ${vs['mean']:+.3f}\\ [{vs['ci95'][0]:+.3f},{vs['ci95'][1]:+.3f}]$ "
              + ("(excl.\\ 0)" if vs["ci_excludes_zero"] else "(crosses 0)") + r" \\",
              f"drift $-$ auto-select & ${va['mean']:+.3f}\\ [{va['ci95'][0]:+.3f},{va['ci95'][1]:+.3f}]$ "
              + ("(excl.\\ 0)" if va["ci_excludes_zero"] else "(crosses 0)") + r" \\",
              r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    # tab:abstain -- honest action mix (the deployed method is pure stacking)
    L += [r"\begin{table}[t]\centering", r"\caption{ELARA-U action mix over tasks (the verified "
          r"method is rank-normalized stacking).}", r"\label{tab:abstain}\footnotesize",
          r"\begin{tabular}{lcc}", r"\toprule", r"\textbf{Action} & Tasks & Fraction \\", r"\midrule",
          f"stack & {NTASK} & 1.00 \\\\", r"select / fuse / fallback & 0 & 0.00 \\",
          r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    # tab:failure -- honest
    L += [r"\begin{table}[t]\centering", r"\caption{Failure analysis: where ELARA-U does not "
          r"improve, and why.}", r"\label{tab:failure}\footnotesize",
          r"\begin{tabular}{p{0.20\linewidth}p{0.32\linewidth}p{0.34\linewidth}}", r"\toprule",
          r"\textbf{Regime} & \textbf{Failure} & \textbf{Cause} \\", r"\midrule",
          r"Reliability gating & gate hurts the stack ($-0.037$) & shared-input detectors have "
          r"correlated reliability; test-time gating adds no signal beyond validation quality \\",
          r"Natural shift (D22) & drift router worse ($-0.050$) & same cause persists under "
          r"genuine temporal shift \\",
          r"Fraud family & underpowered & $n{=}1$ in leave-family-out \\",
          r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    # tab:repro
    L += [r"\begin{table}[t]\centering", r"\caption{Reproducibility / artifact checklist.}",
          r"\label{tab:repro}\footnotesize", r"\begin{tabular}{p{0.62\linewidth}c}", r"\toprule",
          r"\textbf{Artifact} & \textbf{Released} \\", r"\midrule",
          r"Verified benchmark \texttt{honest\_benchmark.json} (123 tasks) & yes \\",
          r"Reliability ablations (3 regimes) + D22 natural shift & yes \\",
          r"Method/emit scripts \texttt{src/scripts/elara\_u/} & yes \\",
          r"Score archive (123 tasks) + manifest & yes \\",
          r"Multimodal harness + pre-registered protocol & yes \\",
          r"No-test-label routing audit & yes \\",
          r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    OUT.write_text("\n".join(L))
    print(f"wrote {OUT} ({len(L)} lines, {sum('begin{table' in x for x in L)} tables) from VERIFIED data")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
