"""T5b (novel): sample-complexity guarantee for the switching certificate.

The T5 certificate (audit_switching_certificate_t5.py) tests whether a switch is
beneficial. T5b answers the *design* question a practitioner asks BEFORE running:
how many paired units n are needed to certify a benefit of size eps at confidence
1-delta?

Setup. Let X_i = AUC_RGA,i - AUC_static,i be paired AUC differences. Treating the
per-seed (or per-cell) AUC difference as the i.i.d. unit with X_i in [-1, 1]
(range R = 2), Hoeffding's inequality gives the one-sided lower confidence bound

    Cert(n, delta) = Xbar_n - sqrt(2 ln(1/delta) / n)          [X_i in [-1,1]]

and to guarantee Cert(n, delta) >= eps with confidence 1-delta the required
sample size is

    n*(eps, delta) = 2 ln(1/delta) / (E[dAUC] - eps)^2.

Honesty notes:
  * AUC is a U-statistic, not a sum of i.i.d. terms; the bound is exact for the
    chosen i.i.d. UNIT (per-seed / per-cell AUC difference), which is what the
    certificate aggregates. Stated explicitly, not hidden.
  * eps is the practical-significance margin; eps -> 0 recovers "n to certify any
    positive benefit". We report n* at eps=0 (certify >0) for each Family-A cell.

Writes experiments/fusion/switching_sample_complexity_t5b.json + table.
"""

from __future__ import annotations

import csv
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HOLM = ROOT / "experiments/fusion" / "family_a_v2_primary_cell_level_holm_k5.csv"
# fall back to the phase2 statistics location
if not HOLM.is_file():
    HOLM = ROOT / "experiments/phase2/statistics/family_a_v2_primary_cell_level_holm_k5.csv"


def n_star(delta_auc: float, eps: float = 0.0, delta: float = 0.05) -> float:
    """Min i.i.d. units to certify benefit >= eps at confidence 1-delta (X in [-1,1])."""
    margin = delta_auc - eps
    if margin <= 0:
        return float("inf")
    return 2.0 * math.log(1.0 / delta) / (margin ** 2)


def cert(xbar: float, n: int, delta: float = 0.05) -> float:
    """One-sided Hoeffding LCB for X in [-1,1]."""
    return xbar - math.sqrt(2.0 * math.log(1.0 / delta) / n)


def main() -> int:
    if not HOLM.is_file():
        print(f"missing {HOLM}")
        return 1
    rows = list(csv.DictReader(HOLM.open()))
    # available test n per Family-A cell (from prior audits / archive)
    n_avail = {
        "A-POWERED-1": 278, "A-POWERED-2": 278, "A-POWERED-3": 1080,
        "A-POWERED-4": 3250, "A-POWERED-5": 27000,
    }
    out_rows = []
    for r in rows:
        eid = r["experiment_id"]
        d = float(r["ensemble_delta_auc"])
        ns = n_star(d, eps=0.0)
        navail = n_avail.get(eid)
        out_rows.append({
            "cell": eid, "benchmark": r["benchmark"],
            "delta_auc": d,
            "n_star_certify_positive": (None if math.isinf(ns) else int(math.ceil(ns))),
            "n_available": navail,
            "certifiable_with_available": (navail is not None and not math.isinf(ns) and navail >= ns),
        })

    out = {
        "theorem": "T5b sample complexity for switching certificate",
        "formula_n_star": "2 ln(1/delta) / (E[dAUC] - eps)^2  (X_i in [-1,1])",
        "delta": 0.05, "eps": 0.0,
        "rows": out_rows,
        "honest_note": (
            "i.i.d. unit = per-cell/per-seed AUC difference (AUC is a U-statistic; "
            "bound is exact for that unit). n* certifies benefit>0 at 95% confidence."
        ),
    }
    (ROOT / "experiments/fusion/switching_sample_complexity_t5b.json").write_text(json.dumps(out, indent=2))

    L = ["% Auto-generated by audit_switching_sample_complexity_t5b.py",
         r"\begin{tabular}{lccccc}", r"\toprule",
         r"Cell & Benchmark & $\Delta$AUC & $n^{*}$ (certify $>0$) & $n$ avail & Certifiable? \\",
         r"\midrule"]
    for r in out_rows:
        b = r["benchmark"].replace("_", r"\_")
        ns = "--" if r["n_star_certify_positive"] is None else str(r["n_star_certify_positive"])
        na = "--" if r["n_available"] is None else str(r["n_available"])
        ok = r"\textbf{yes}" if r["certifiable_with_available"] else "no"
        L.append(f"{r['cell']} & {b} & {r['delta_auc']:.4f} & {ns} & {na} & {ok} \\")
    L += [r"\bottomrule", r"\end{tabular}", "",
          r"% n* = 2 ln(1/delta)/(Delta AUC)^2; i.i.d. unit = per-cell AUC difference, X in [-1,1]."]
    (ROOT / "docs/research/tables/switching_sample_complexity_t5b.tex").write_text("\n".join(L))

    print("=== T5b sample complexity (certify benefit>0 at 95%) ===")
    for r in out_rows:
        ns = r["n_star_certify_positive"]
        print(f"  {r['cell']:13s} dAUC={r['delta_auc']:+.4f}  n*={ns}  n_avail={r['n_available']}  "
              f"certifiable={r['certifiable_with_available']}")
    print("\nWrote switching_sample_complexity_t5b.json + table")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
