"""Emit the T5 (finite-sample switching certificate) audit table."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

GENERATED_COMMENT = "% Auto-generated by emit_switching_certificate_t5_table.py (do not edit by hand)"


def _fmt(value, decimals: int = 4, sign: bool = False) -> str:
    if value is None or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        return "--"
    if sign:
        return f"{float(value):+.{decimals}f}"
    return f"{float(value):.{decimals}f}"


def render(payload: dict) -> str:
    alpha = payload.get("alpha", 0.05)
    rows = payload.get("rows", [])

    out = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llcccccc}",
        r"\toprule",
        r"\textbf{Benchmark} & \textbf{Protocol} & \textbf{$n_{\mathrm{seeds}}$} & "
        r"\textbf{RGA path} & \textbf{Static AUROC} & \textbf{RGA AUROC} & "
        + rf"\textbf{{LCB$_{{{alpha:.2f}}}$}} & "
        + r"\textbf{Verdict} \\",
        r"\midrule",
    ]
    for r in rows:
        path_label = {
            "rga_boosted_fusion": "boost",
            "rga_meta_router": "router",
        }.get(r.get("rga_path", ""), r.get("rga_path", "?"))
        verdict_label = r"\textbf{certified}" if r.get("certified") else "not cert."
        out.append(
            rf"{r['benchmark']} & {r['protocol']} & {r['n_seeds']} & "
            rf"{path_label} & {_fmt(r.get('static_auroc_mean'), 3)} & "
            rf"{_fmt(r.get('rga_auroc_mean'), 3)} & "
            rf"{_fmt(r.get('lcb'), 4, sign=True)} & "
            rf"{verdict_label} \\"
        )
    out += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("experiments/fusion/switching_certificate_t5_audit.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/research/tables/switching_certificate_t5.tex"),
    )
    args = parser.parse_args()
    payload = json.loads(args.input.read_text())
    table = render(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")
    print(table)


if __name__ == "__main__":
    main()
