"""Emit a per-benchmark RGA+ component ablation table.

A senior-reviewer criticism is that the RGA+ headline is reported as
max(meta_router, boosted_fusion) without explaining where the gain
comes from per cell. This script renders a table that puts the two
RGA+ variants side-by-side with base RGA and the best non-router
baseline, per benchmark.

Columns: Benchmark | Protocol | Static | RGA | RGA+ router | RGA+ boost |
         Best non-router | Best ROC | router-best | boost-best
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

GENERATED_COMMENT = "% Auto-generated by emit_rga_plus_ablation.py (do not edit by hand)"


def _fmt(value: Any, decimals: int = 3) -> str:
    if value is None or (isinstance(value, float) and not math.isfinite(float(value))):
        return "--"
    try:
        return f"{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return "--"


def _dig(payload: dict | None, *keys: str) -> Any:
    for key in keys:
        if payload is None:
            return None
        payload = payload.get(key)
    return payload


def _method_label(name: str | None) -> str:
    labels = {
        "random_forest": "RF",
        "confidence_weighted_mean": "Conf-m",
        "tent_score_adapter": "Tent",
        "ttt_pseudo_label_adapter": "TTT",
        "eata_score_adapter": "EATA",
        "sar_score_adapter": "SAR",
        "early_fusion_mlp": "MLP",
        "late_fusion_ensemble": "LFE",
        "static_attention": "Static",
    }
    return labels.get(str(name), str(name or "--"))


BENCHMARKS = [
    ("MVTec 3D-AD", "PatchCore canonical", "experiments/fusion/mvtec3d_patchcore_results.json"),
    ("MVTec 3D-AD", "PatchCore supervised", "experiments/fusion/mvtec3d_patchcore_supervised_paired_results.json"),
    ("MVTec 3D-AD", "PatchCore held-out", "experiments/fusion/mvtec3d_patchcore_heldout_results.json"),
    ("MVTec LOCO-AD", "PatchCore canonical", "experiments/fusion/mvtec_loco_patchcore_results.json"),
    ("MVTec LOCO-AD", "PatchCore supervised", "experiments/fusion/mvtec_loco_patchcore_supervised_paired_results.json"),
    ("Real3D-AD", "PCA shape + depth supervised", "experiments/fusion/real3d_supervised_paired_results.json"),
    ("VisA", "RGB+edge canonical", "experiments/fusion/visa_fusion_results.json"),
    ("VisA", "RGB+edge supervised", "experiments/fusion/visa_supervised_paired_results.json"),
    ("VisA", "RGB+random noise-floor", "experiments/fusion/visa_supervised_paired_noise_floor_results.json"),
    ("UNSW-NB15", "flow/conn/context", "experiments/fusion/unsw_paired_results.json"),
    ("UNSW-NB15", "held-out attack", "experiments/fusion/unsw_heldout_attack_results.json"),
]


def render_table(repo_root: Path) -> str:
    """Phase 1.1 — render the RGA+ component-attribution table under the
    locked validation-frozen comparator policy. The comparator name is
    read from `experiments/audit/audited_comparator_selection.csv`
    (validation-frozen, never test-winner). Δ columns are RGA+ router or
    boost minus the validation-frozen comparator.
    """
    import csv
    # Load validation-frozen comparator per cell.
    comp_path = repo_root / "experiments/audit/audited_comparator_selection.csv"
    comp_idx: dict[tuple[str, str], dict] = {}
    if comp_path.exists():
        with comp_path.open() as f:
            for r in csv.DictReader(f):
                comp_idx[(r["benchmark"], r["protocol"])] = r

    rows = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llcccccccc}",
        r"\toprule",
        r"\textbf{Benchmark} & \textbf{Protocol} & \textbf{Static} & \textbf{RGA} & "
        r"\textbf{RGA+ router} & \textbf{RGA+ boost} & "
        r"\textbf{Validation-frozen comparator} & "
        r"\textbf{Comparator test ROC} & "
        r"\textbf{Audited $\Delta$ router} & "
        r"\textbf{Audited $\Delta$ boost} \\",
        r"\midrule",
    ]
    for benchmark, protocol, rel_path in BENCHMARKS:
        full_path = repo_root / rel_path
        if not full_path.exists():
            rows.append(
                rf"{benchmark} & {protocol} & \multicolumn{{8}}{{c}}{{\emph{{results pending}}}} \\"
            )
            continue
        payload = json.loads(full_path.read_text(encoding="utf-8"))
        cs = payload.get("clean_metric_summary", {})
        static = _dig(cs, "static_attention", "roc_auc", "mean")
        rga = _dig(cs, "craf_attention", "roc_auc", "mean")
        router = _dig(cs, "rga_meta_router", "roc_auc", "mean")
        boost = _dig(cs, "rga_boosted_fusion", "roc_auc", "mean")

        # Validation-frozen comparator (Phase 1.C): never selected from test ROC.
        comp_row = comp_idx.get((benchmark, protocol)) or {}
        comp_name = comp_row.get("selected_comparator")
        try:
            comp_test = float(comp_row.get("selected_comparator_test_auc"))
        except (TypeError, ValueError):
            comp_test = None

        router_delta = (
            router - comp_test
            if (router is not None and comp_test is not None) else None
        )
        boost_delta = (
            boost - comp_test
            if (boost is not None and comp_test is not None) else None
        )

        rows.append(
            rf"{benchmark} & {protocol} & {_fmt(static)} & {_fmt(rga)} & "
            rf"{_fmt(router)} & {_fmt(boost)} & {_method_label(comp_name)} & "
            rf"{_fmt(comp_test)} & {_fmt(router_delta)} & {_fmt(boost_delta)} \\"
        )
    rows += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/research/tables/rga_plus_ablation.tex"),
    )
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    args = parser.parse_args()

    table = render_table(args.repo_root)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")
    print(table)


if __name__ == "__main__":
    main()
