"""Emit a LaTeX table summarising the gradient-adversarial sweep.

Reads experiments/fusion/visa_sp_gradient_adversarial.json (produced by
src/scripts/eval_gradient_adversarial.py) and renders a small table:
columns = (clean | FGSM eps_1 | FGSM eps_2 | ... | PGD eps_1 | ...).
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

GENERATED_COMMENT = "% Auto-generated by emit_gradient_adversarial_table.py (do not edit by hand)"


def _fmt(value, decimals: int = 3) -> str:
    if value is None or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        return "--"
    return f"{float(value):.{decimals}f}"


def render_table(payload: dict) -> str:
    epsilons = payload.get("epsilons", [])
    fgsm = {r["epsilon"]: r["static_auroc"] for r in payload.get("fgsm", [])}
    pgd = {r["epsilon"]: r["static_auroc"] for r in payload.get("pgd", [])}
    clean = payload.get("clean", {}).get("static_auroc")
    n_steps = int(payload.get("pgd_steps", 0))

    n_eps = len(epsilons)
    col_spec = "l" + "c" * (1 + 2 * n_eps)
    eps_headers = "".join(rf" & $\epsilon{{=}}{e:.2f}$" for e in epsilons)
    # Phase 1.G K: explicit FGSM | PGD group label so the duplicate
    # epsilon columns are unambiguous.
    rows = [
        GENERATED_COMMENT,
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
        (
            r"\textbf{Attack} & \textbf{clean} & "
            rf"\multicolumn{{{n_eps}}}{{c}}{{\textbf{{FGSM (1-step)}}}} & "
            rf"\multicolumn{{{n_eps}}}{{c}}{{\textbf{{PGD ({n_steps}-step)}}}} \\"
        ),
        rf" & {eps_headers}{eps_headers} \\",
        r"\midrule",
    ]
    fgsm_row = ["FGSM (1-step)", _fmt(clean)]
    fgsm_row += [_fmt(fgsm.get(e)) for e in epsilons]
    fgsm_row += ["" for _ in epsilons]  # placeholder for visual alignment
    rows.append(" & ".join(fgsm_row) + r" \\")

    pgd_row = [rf"PGD ({n_steps}-step)", _fmt(clean)]
    pgd_row += ["" for _ in epsilons]
    pgd_row += [_fmt(pgd.get(e)) for e in epsilons]
    rows.append(" & ".join(pgd_row) + r" \\")
    rows += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("experiments/fusion/visa_sp_gradient_adversarial.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/research/tables/gradient_adversarial.tex"),
    )
    args = parser.parse_args()

    payload = json.loads(args.input.read_text())
    table = render_table(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")
    print(table)


if __name__ == "__main__":
    main()
