"""Emit the MVTec 3D-AD SOTA demarcation table + companion bar-chart figure.

The published-SOTA image-AUROC headlines on MVTec 3D-AD's canonical
one-class protocol are well-known public values. This script renders a
side-by-side table that lists those published headlines (with citation
provenance) alongside ELARA's RGA+ numbers under both the canonical
one-class protocol and the supervised-paired protocol, plus an explicit
"Comparable?" column that flags why the ELARA rows are not directly
leaderboard-comparable.

The script is intentionally a *demarcation*, not a comparison. It does
not claim that ELARA's 0.740 supervised-paired score beats anything on
the canonical leaderboard. The table makes the protocol mismatch
visible at a glance; the paper subsection that consumes it explains
what an honest head-to-head leaderboard comparison would require.

Pattern follows emit_milestone2_cross_benchmark.py: hard-coded
constants for the published rows, JSON-driven values for the local
ELARA rows.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt

GENERATED_COMMENT = "% Auto-generated by emit_mvtec3d_sota_demarcation.py (do not edit by hand)"


# ---------------------------------------------------------------------------
# Published SOTA headlines (canonical MVTec 3D-AD one-class protocol)
# ---------------------------------------------------------------------------
PUBLISHED_SOTA: list[dict[str, Any]] = [
    {
        "method": "BTF",
        "protocol": "canonical one-class",
        "image_auroc": 0.865,
        "pixel_auroc": 0.992,
        "citation": "horwitz2023btf",
        "note": "Classical 3D handcrafted features + RGB; image-AUROC as reported in Horwitz \\& Hoshen, 2023.",
    },
    {
        "method": "EasyNet",
        "protocol": "canonical one-class",
        "image_auroc": 0.872,
        "pixel_auroc": 0.985,
        "citation": "chen2023easynet",
        "note": "Lightweight reconstruction-based 3D AD; image-AUROC as reported in Chen et al., 2023.",
    },
    {
        "method": "PatchCore-3D",
        "protocol": "canonical one-class",
        "image_auroc": 0.901,
        "pixel_auroc": 0.992,
        "citation": "roth2022patchcore",
        "note": "Depth+RGB patch memory; image-AUROC as reported by M3DM (Wang et al., 2023) as a baseline row.",
    },
    {
        "method": "AST",
        "protocol": "canonical one-class",
        "image_auroc": 0.937,
        "pixel_auroc": 0.976,
        "citation": "rudolph2023ast",
        "note": "Asymmetric student-teacher with depth normalising flow; as reported in Rudolph et al., 2023.",
    },
    {
        "method": "M3DM",
        "protocol": "canonical one-class",
        "image_auroc": 0.945,
        "pixel_auroc": 0.964,
        "citation": "wang2023m3dm",
        "note": "Hybrid feature + decision-layer fusion with memory banks; as reported in Wang et al., 2023.",
    },
]


# ---------------------------------------------------------------------------
# Local ELARA cells (loaded from the existing breakthrough-runner JSONs)
# ---------------------------------------------------------------------------
LOCAL_ROWS: list[dict[str, Any]] = [
    {
        "label": "ELARA RGA+ (this work)",
        "protocol": "canonical one-class",
        "results_path": "experiments/fusion/mvtec3d_patchcore_results.json",
        "note": "Score-fusion layer over PatchCore-derived RGB/depth scores; no localization head, no detector retraining.",
    },
    {
        "label": "ELARA RGA+ (this work)",
        "protocol": "supervised paired (diagnostic only)",
        "results_path": "experiments/fusion/mvtec3d_patchcore_supervised_paired_results.json",
        "note": "Different protocol: fusion training fold sees positives. Not directly comparable to canonical leaderboard rows.",
    },
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fmt(value: Any, decimals: int = 3) -> str:
    if value is None or (isinstance(value, float) and value != value):
        return "--"
    try:
        return f"{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return "--"


def _dig(payload: dict | None, *keys: str) -> Any:
    for key in keys:
        if payload is None:
            return None
        payload = payload.get(key)
    return payload


def _local_image_auroc(results_path: Path) -> float | None:
    """Return the headline image-AUROC for an ELARA cell.

    Uses the same convention as emit_milestone1_comparison.py and
    emit_milestone2_cross_benchmark.py: prefer max(rga_meta_router,
    rga_boosted_fusion); fall back to base RGA (craf_attention) when
    neither boosted variant has a meaningful clean-summary entry.
    """
    if not results_path.exists():
        return None
    payload = json.loads(results_path.read_text(encoding="utf-8"))
    cs = payload.get("clean_metric_summary", {})
    rga = _dig(cs, "craf_attention", "roc_auc", "mean")
    router = _dig(cs, "rga_meta_router", "roc_auc", "mean")
    boost = _dig(cs, "rga_boosted_fusion", "roc_auc", "mean")
    plus_candidates = [v for v in (router, boost) if v is not None]
    rga_plus = max(plus_candidates) if plus_candidates else None
    # If the boosted variant collapses to a constant (its router didn't
    # find supervised signal) it can equal RGA; surface whichever number
    # is higher.
    options = [v for v in (rga, rga_plus) if v is not None]
    return max(options) if options else None


# ---------------------------------------------------------------------------
# Table rendering
# ---------------------------------------------------------------------------

def render_table(repo_root: Path) -> str:
    rows: list[str] = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llcclp{4.0cm}l}",
        r"\toprule",
        r"\textbf{Method} & \textbf{Protocol} & \textbf{Image-AUROC} & "
        r"\textbf{Pixel-AUROC} & \textbf{Comparable?} & \textbf{Notes} & "
        r"\textbf{Source} \\",
        r"\midrule",
    ]

    for entry in PUBLISHED_SOTA:
        rows.append(
            rf"{entry['method']} & {entry['protocol']} & "
            rf"{_fmt(entry['image_auroc'])} & {_fmt(entry['pixel_auroc'])} & "
            rf"leaderboard & {entry['note']} & "
            rf"\cite{{{entry['citation']}}} \\"
        )

    rows.append(r"\midrule")

    for entry in LOCAL_ROWS:
        local_auroc = _local_image_auroc(repo_root / entry["results_path"])
        rows.append(
            rf"{entry['label']} & {entry['protocol']} & "
            rf"{_fmt(local_auroc)} & n/a (no localization head) & "
            rf"\emph{{not}} leaderboard-comparable & {entry['note']} & "
            r"this work \\"
        )

    rows += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(rows)


# ---------------------------------------------------------------------------
# Figure rendering
# ---------------------------------------------------------------------------

def render_figure(repo_root: Path, out_path: Path) -> None:
    """Horizontal bar chart of image-AUROC: published SOTA + ELARA rows.

    Published methods are drawn in one colour, ELARA rows in a
    contrasting colour. A horizontal divider separates the two groups
    with the label "different protocol --- not leaderboard
    comparable" above the ELARA rows.
    """
    published_sorted = sorted(PUBLISHED_SOTA, key=lambda d: d["image_auroc"])
    local_with_vals = []
    for entry in LOCAL_ROWS:
        val = _local_image_auroc(repo_root / entry["results_path"])
        if val is None:
            continue
        local_with_vals.append(
            (f"{entry['label']}\n({entry['protocol']})", float(val))
        )

    labels: list[str] = [f"{e['method']} ({e['protocol']})" for e in published_sorted]
    values: list[float] = [float(e["image_auroc"]) for e in published_sorted]
    colors: list[str] = ["#1f77b4"] * len(published_sorted)

    # Divider row: render as a thin spacer
    labels.append("")
    values.append(0.0)
    colors.append("none")

    for label, val in local_with_vals:
        labels.append(label)
        values.append(val)
        colors.append("#d62728")

    fig_h = max(3.5, 0.45 * len(labels))
    fig, ax = plt.subplots(figsize=(8.6, fig_h))
    y_pos = list(range(len(labels)))
    ax.barh(y_pos, values, color=colors, edgecolor="black", linewidth=0.4)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(labels, fontsize=8)
    ax.set_xlabel("Image-AUROC on MVTec 3D-AD")
    ax.set_xlim(0.0, 1.0)
    ax.axvline(0.5, color="grey", linestyle=":", linewidth=0.6)
    # Divider line at the empty spacer row
    divider_index = len(published_sorted)
    ax.axhline(divider_index, color="black", linestyle="--", linewidth=0.7)
    ax.text(
        0.99,
        divider_index + 0.05,
        "different protocol --- not leaderboard comparable",
        ha="right",
        va="bottom",
        fontsize=7,
        color="#d62728",
        transform=ax.get_yaxis_transform(),
    )
    for y, val in zip(y_pos, values):
        if val <= 0.0:
            continue
        ax.text(val + 0.005, y, f"{val:.3f}", va="center", fontsize=7)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_title(
        "Position relative to published MVTec 3D-AD state of the art",
        fontsize=10,
    )
    fig.patch.set_facecolor("white")
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=200, facecolor="white", edgecolor="none")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--table-output",
        type=Path,
        default=Path("docs/research/tables/mvtec3d_sota_demarcation.tex"),
    )
    parser.add_argument(
        "--figure-output",
        type=Path,
        default=Path("docs/research/figures/mvtec3d_sota_demarcation.png"),
    )
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    args = parser.parse_args()

    table = render_table(args.repo_root)
    args.table_output.parent.mkdir(parents=True, exist_ok=True)
    args.table_output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.table_output}")

    render_figure(args.repo_root, args.figure_output)
    print(f"Wrote {args.figure_output}")


if __name__ == "__main__":
    main()
