"""Emit T6 KS window power table from B-MECH-4 sweep CSV."""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from pathlib import Path

GENERATED_COMMENT = "% Auto-generated by emit_ks_power_t6_table.py (do not edit by hand)"


def _fmt(value, decimals: int = 3) -> str:
    if value is None or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        return "--"
    return f"{float(value):.{decimals}f}"


def _aggregate(path: Path) -> list[dict]:
    buckets: dict[int, list[dict]] = defaultdict(list)
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            buckets[int(row["window_size"])].append(row)
    out = []
    for window in sorted(buckets):
        rows = buckets[window]
        out.append(
            {
                "window_size": window,
                "false_activation_rate": float(
                    sum(float(r["false_activation_rate"]) for r in rows) / len(rows)
                ),
                "detection_power": float(
                    sum(float(r["true_degradation_detection_power"]) for r in rows) / len(rows)
                ),
                "roc_auc_effect": float(sum(float(r["roc_auc_effect"]) for r in rows) / len(rows)),
                "n_seeds": len(rows),
            }
        )
    return out


def render(rows: list[dict]) -> str:
    out = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"\textbf{Window} & \textbf{$n_{\mathrm{seeds}}$} & "
        r"\textbf{False activation} & \textbf{Detection power} & \textbf{ROC effect} \\",
        r"\midrule",
    ]
    for row in rows:
        out.append(
            rf"{row['window_size']} & {row['n_seeds']} & "
            rf"{_fmt(row['false_activation_rate'], 4)} & "
            rf"{_fmt(row['detection_power'], 3)} & "
            rf"{_fmt(row['roc_auc_effect'], 4)} \\"
        )
    out += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("experiments/phase2/mechanism/ks_window_size_power.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/research/tables/ks_power_t6.tex"),
    )
    args = parser.parse_args()
    table = render(_aggregate(args.input))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
