"""Emit k-of-D corruption assets that validate Theorem T3.

The thesis appendix theorem T3 (mean-gate dilution failure) predicts:
for D domains and threshold tau, the mean gate fires only when more
than D(1-tau) domains collapse. For D=4 and tau=0.66 this is k>1.36,
so k=1 falls below threshold (gate stays closed; delta near zero) and
k=4 fires (gate switches; delta positive). The runner already produced
``table_10_k_domain_corruption`` in ``craf_real_k_domain_results.json``;
this script consumes that table and renders a LaTeX table plus a mechanism
figure the paper can include.

Columns: attack | k | gate mode | Static ROC-AUC | RGA ROC-AUC |
Delta with 95% CI | adaptation rate | mean reliability | minimum reliability
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import matplotlib.pyplot as plt

GENERATED_COMMENT = "% Auto-generated by emit_k_of_d_corruption_table.py (do not edit by hand)"
ATTACK_ORDER = {"none": 0, "zero_attack": 1, "max_attack": 2}
GATE_ORDER = {"mean": 0, "minimum": 1, "hybrid": 2}
GATE_COLORS = {
    "mean": "#1f77b4",
    "minimum": "#d62728",
    "hybrid": "#2ca02c",
}
GATE_OFFSETS = {
    "mean": -0.045,
    "minimum": 0.0,
    "hybrid": 0.045,
}
ATTACK_LINESTYLES = {
    "zero_attack": "-",
    "max_attack": "--",
}


def _fmt(value, decimals: int = 3) -> str:
    if value is None or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        return "--"
    return f"{float(value):.{decimals}f}"


def _escape_latex(value: str) -> str:
    return value.replace("_", r"\_")


def _delta(row: dict | None) -> float | None:
    if not row:
        return None
    if isinstance(row.get("delta_auc"), (int, float)):
        return float(row["delta_auc"])
    static = row.get("static_auc")
    craf = row.get("craf_auc")
    if isinstance(static, (int, float)) and isinstance(craf, (int, float)):
        return float(craf) - float(static)
    return None


def _ordered_rows(payload: dict) -> list[dict]:
    rows = payload.get("table_10_k_domain_corruption", [])
    return sorted(
        rows,
        key=lambda r: (
            ATTACK_ORDER.get(str(r.get("attack")), 99),
            int(r.get("failed_domain_count", 0)),
            GATE_ORDER.get(str(r.get("gate_mode")), 99),
        ),
    )


def render_table(payload: dict) -> str:
    out = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llccccccc}",
        r"\toprule",
        r"\textbf{Attack} & \textbf{$k$} & \textbf{Gate} & \textbf{Static ROC} & \textbf{RGA ROC} & \textbf{$\Delta$ ROC 95\% CI} & \textbf{Adapt} & \textbf{Mean $r$} & \textbf{Min $r$} \\",
        r"\midrule",
    ]
    last_attack = None
    for r in _ordered_rows(payload):
        attack = str(r.get("attack", "?"))
        if last_attack is not None and attack != last_attack:
            out.append(r"\midrule")
        last_attack = attack
        delta = _delta(r)
        ci_low = r.get("delta_auc_ci_low")
        ci_high = r.get("delta_auc_ci_high")
        ci = rf"{_fmt(delta, 4)} [{_fmt(ci_low, 4)}, {_fmt(ci_high, 4)}]"
        out.append(
            rf"{_escape_latex(attack)} & {int(r.get('failed_domain_count', 0))} & "
            rf"{_escape_latex(str(r.get('gate_mode', '?')))} & "
            rf"{_fmt(r.get('static_auc'), 4)} & {_fmt(r.get('craf_auc'), 4)} & {ci} & "
            rf"{_fmt(r.get('adaptation_rate'), 3)} & {_fmt(r.get('mean_reliability'), 3)} & "
            rf"{_fmt(r.get('min_reliability'), 3)} \\"
        )
    out += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(out)


def render_theory_mapping_table() -> str:
    return "\n".join(
        [
            GENERATED_COMMENT,
            r"\begin{tabular}{p{0.16\textwidth}p{0.35\textwidth}p{0.38\textwidth}}",
            r"\toprule",
            r"\textbf{Claim} & \textbf{Current evidence} & \textbf{Boundary still open} \\",
            r"\midrule",
            r"T1 quality-blind impossibility & Architectural motivation: score-only fusion cannot disambiguate identical score vectors with different latent reliability states. & Formal example is theoretical; no separate empirical table is needed beyond collapse construction. \\",
            r"T2 global-KS mixture confounding & MVTec category-aware reference experiments show global references can over-activate under heterogeneous categories. & Needs a pure controlled mixture-shift table with no within-category corruption. \\",
            r"T3 mean-gate dilution & Directly supported by the $k$-of-$D$ table and figure: weak or mixed effects for $k=1,2,3$, full activation and positive ROC-AUC gain at $k=4$. & The ideal theorem assumes failed-domain reliability is zero; the implemented estimator keeps minimum reliability above $0.34$. \\",
            r"T4 risk dominance & The theorem gives measurable terms $(q_0,q_1,\Delta_0,\Delta_1)$ for when switching should win. & These terms are not yet reported as a deployment prevalence sensitivity table. \\",
            r"T5 finite-sample certificate & Certificate utility exists and defines fired-case paired benefit. & Needs an audited deployment-window LCB table before making operational safety claims. \\",
            r"T6 KS false-fire/power & KS is the empirically necessary trigger in component ablation. & Needs sample-size and multiple-testing power curves before claiming calibrated drift detection. \\",
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )


def plot_figure(payload: dict, output: Path) -> None:
    rows = _ordered_rows(payload)
    by_key = {
        (str(r.get("attack")), str(r.get("gate_mode")), int(r.get("failed_domain_count", 0))): r
        for r in rows
    }
    gates = ["mean", "minimum", "hybrid"]
    attacks = ["zero_attack", "max_attack"]
    k_values = [0, 1, 2, 3, 4]

    plt.rcParams.update(
        {
            "font.size": 9,
            "axes.titlesize": 10,
            "axes.labelsize": 9,
            "legend.fontsize": 7.8,
            "figure.dpi": 150,
            "savefig.dpi": 250,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
        }
    )
    fig, axes = plt.subplots(1, 2, figsize=(8.4, 3.2), sharex=True)

    for attack in attacks:
        for gate in gates:
            delta_values: list[float] = []
            adapt_values: list[float] = []
            for k in k_values:
                key = ("none", gate, 0) if k == 0 else (attack, gate, k)
                row = by_key.get(key)
                delta_values.append(float(_delta(row) or 0.0) if row else 0.0)
                adapt_values.append(float(row.get("adaptation_rate", 0.0)) if row else 0.0)
            label = f"{gate}, {attack.replace('_attack', '')}"
            color = GATE_COLORS.get(gate, "#333333")
            linestyle = ATTACK_LINESTYLES.get(attack, "-")
            offset = GATE_OFFSETS.get(gate, 0.0)
            x_values = [k + offset for k in k_values]
            axes[0].plot(x_values, delta_values, marker="o", linewidth=1.8, color=color, linestyle=linestyle, label=label)
            axes[1].plot(x_values, adapt_values, marker="o", linewidth=1.8, color=color, linestyle=linestyle, label=label)

    axes[0].axhline(0.0, color="#444444", linewidth=0.8)
    axes[0].set_title("ROC-AUC delta")
    axes[0].set_ylabel("RGA - static")
    axes[1].set_title("Gate adaptation")
    axes[1].set_ylabel("adaptation rate")
    axes[1].set_ylim(-0.03, 1.05)

    for ax in axes:
        ax.set_xlabel("failed domains k")
        ax.set_xticks(k_values)
        ax.grid(True, linewidth=0.5, alpha=0.35)
        for spine in ["top", "right"]:
            ax.spines[spine].set_visible(False)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=3, frameon=False, bbox_to_anchor=(0.5, -0.02))
    fig.tight_layout(rect=(0, 0.14, 1, 1))
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, bbox_inches="tight", facecolor="white", edgecolor="none")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("experiments/fusion/craf_real_k_domain_results.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/research/tables/elara_k_domain_corruption_results.tex"),
    )
    parser.add_argument(
        "--mapping-output",
        type=Path,
        default=Path("docs/research/tables/elara_theory_experiment_mapping.tex"),
    )
    parser.add_argument(
        "--figure-output",
        type=Path,
        default=Path("docs/research/figures/elara_k_domain_corruption.png"),
    )
    args = parser.parse_args()

    payload = json.loads(args.input.read_text())
    table = render_table(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    args.mapping_output.parent.mkdir(parents=True, exist_ok=True)
    args.mapping_output.write_text(render_theory_mapping_table(), encoding="utf-8")
    plot_figure(payload, args.figure_output)
    print(f"Wrote {args.output}")
    print(f"Wrote {args.mapping_output}")
    print(f"Wrote {args.figure_output}")
    print(table)


if __name__ == "__main__":
    main()
