"""Phase 2.1 — emit corrected Phase-2 registries as v2 sibling files.

Writes:
  docs/research/phase2/PHASE_2_EXPERIMENT_REGISTRY_v2.csv
  docs/research/phase2/PHASE_2_CLAIM_MATRIX_v2.csv

Both files are written with the `csv` standard library writer so every
row has exactly `len(header)` fields, regardless of embedded commas in
quoted strings.
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_REGISTRY = ROOT / "docs" / "research" / "phase2" / "PHASE_2_EXPERIMENT_REGISTRY_v2.csv"
OUT_CLAIMS = ROOT / "docs" / "research" / "phase2" / "PHASE_2_CLAIM_MATRIX_v2.csv"


# ---------------------------------------------------------------------------
# v2 Experiment registry
# ---------------------------------------------------------------------------

REGISTRY_HEADER = [
    "experiment_id",
    "analysis_family",
    "research_question",
    "benchmark",
    "protocol",
    "pairing_strength",
    "dataset_partition_status",
    "existing_or_new_evidence",
    "method_candidates",
    "primary_comparator",
    "analysis_surface",
    "selection_data_allowed",
    "test_data_visibility_before_lock",
    "seed_plan",
    "prediction_archive_required",
    "primary_metric",
    "secondary_metrics",
    "multiplicity_family",
    "allowed_claim",
    "forbidden_claim",
    "status",
]

# Common candidate pool string (pipe-separated to avoid embedded commas).
CAND_POOL = (
    "rga_meta_router|rga_boosted_fusion|static_attention|craf_attention|"
    "RF|MLP|LFE|Conf-mean|Tent|TTT|EATA|SAR"
)

REGISTRY_ROWS = [
    [
        "A-POWERED-1",
        "A",
        "Q1",
        "MVTec 3D-AD",
        "PatchCore supervised-paired",
        "independent_modalities",
        "inspected",
        "powered audited reproduction",
        CAND_POOL,
        "static_attention",
        "PRIMARY_FAMILY_A_CELL_LEVEL + SECONDARY_ALL_COMPARATOR_PILOT_AUDIT",
        "validation only",
        "partially inspected prior to lock; reproduction is audited not confirmatory",
        "30",
        "True",
        "roc_auc",
        "pr_auc|ece|brier|f1",
        "A-POWERED-K5",
        "audited reproduction; RGA+ vs static_attention as the primary K=5 cell-level surface; secondary all-comparator audit allowed",
        "confirmatory|preregistered|beats every baseline|broad cross-domain generalization",
        "pilot_archive_valid;primary_surface_pending_recompute",
    ],
    [
        "A-POWERED-2",
        "A",
        "Q1",
        "MVTec 3D-AD",
        "PatchCore held-out category",
        "independent_modalities",
        "inspected",
        "powered audited reproduction",
        CAND_POOL,
        "static_attention",
        "PRIMARY_FAMILY_A_CELL_LEVEL",
        "validation only",
        "partially inspected",
        "30",
        "True",
        "roc_auc",
        "pr_auc|ece|brier",
        "A-POWERED-K5",
        "audited reproduction; cross-category transfer audited Delta vs static_attention",
        "confirmatory|preregistered|beats every baseline",
        "pending_compute",
    ],
    [
        "A-POWERED-3",
        "A",
        "Q1",
        "MVTec LOCO-AD",
        "PatchCore supervised-paired",
        "derived_view_proxy",  # PHASE_2_LOCO_PAIRING_STRENGTH_AUDIT: rgb + edge_proxy
        "inspected",
        "powered audited reproduction",
        CAND_POOL,
        "static_attention",
        "PRIMARY_FAMILY_A_CELL_LEVEL",
        "validation only",
        "partially inspected",
        "30",
        "True",
        "roc_auc",
        "pr_auc|ece|brier",
        "A-POWERED-K5",
        "audited reproduction; expected sign-flip vs Phase 1 must be transparently reported",
        "confirmatory|preregistered|beats every baseline",
        "pending_compute",
    ],
    [
        "A-POWERED-4",
        "A",
        "Q1",
        "VisA",
        "RGB+edge supervised-paired",
        "derived_view_proxy",
        "inspected",
        "powered audited reproduction",
        CAND_POOL,
        "static_attention",
        "PRIMARY_FAMILY_A_CELL_LEVEL",
        "validation only",
        "partially inspected",
        "30",
        "True",
        "roc_auc",
        "pr_auc|ece|brier",
        "A-POWERED-K5",
        "audited reproduction; derived-view-proxy pairing cannot support independent-modality generalization",
        "confirmatory|preregistered|broad cross-domain generalization",
        "pending_compute",
    ],
    [
        "A-POWERED-5",
        "A",
        "Q1",
        "UNSW-NB15",
        "flow/conn/context",
        "naturally_structured_views",
        "inspected",
        "powered audited reproduction",
        CAND_POOL,
        "static_attention",
        "PRIMARY_FAMILY_A_CELL_LEVEL",
        "validation only",
        "partially inspected",
        "30",
        "True",
        "roc_auc",
        "pr_auc|ece|brier",
        "A-POWERED-K5",
        "audited reproduction; practical-effect band reported alongside p-value",
        "confirmatory|preregistered|broad cross-domain generalization",
        "pending_compute",
    ],
    [
        "B-MECH-1",
        "B",
        "Q1",
        "ELARA-Bench-LA",
        "k-of-D corruption k=4 mean-gate at locked tau=0.66 (B1+B2 endpoints)",
        "label_aligned_stress_only",
        "reproduction of inspected mechanism cell",
        "mechanism replication",
        "RGA vs static",
        "static_attention",
        "PRIMARY_FAMILY_B_MECHANISM",
        "validation only for any auxiliary choices",
        "partially inspected",
        "30",
        "True",
        "roc_auc_delta",
        "gate_activation_rate|mean_reliability|min_reliability",
        "B-MECH-K2",
        "reproduction of B1/B2 audited mechanism endpoints (+0.0506 / +0.0319) under archived predictions + ensemble inference",
        "confirmatory|preregistered|cross-domain generalization",
        "pending_compute",
    ],
    [
        "B-MECH-2",
        "B",
        "Q2",
        "ELARA-Bench-LA",
        "RGA-v2 partial-failure evaluation across k in {0,1,2,3,4}",
        "label_aligned_stress_only",
        "new mechanism method test",
        "RGA-v2 gate-candidate sweep",
        "G0 mean|G1 min|G2 hybrid|G3 top-q|G4 learned (optional)",
        "G0 (base mean-gate)",
        "PRIMARY_RGA_V2_PROMOTION",
        "validation only",
        "k=0 (clean) data and validation-fold corruption only",
        "15-30",
        "True",
        "roc_auc_delta_per_k|clean_false_fire_rate",
        "gate_activation_rate|certificate_status",
        "B-RGA-V2-K5",
        "RGA-v2 may be called an improvement only if all promotion criteria pass; otherwise reported as partial / no improvement",
        "RGA-v2 universally better|RGA-v2 promotion based on test-tuning",
        "pending_compute",
    ],
    [
        "B-MECH-3",
        "B",
        "Q3",
        "ELARA-Bench-LA",
        "pure mixture-shift false-fire control",
        "label_aligned_stress_only",
        "new theory/mechanism evidence",
        "category-aware reference test",
        "global KS reference vs category-aware reference",
        "global KS reference",
        "PRIMARY_MIXTURE_SHIFT_CONTROL",
        "validation only",
        "not previously inspected",
        "5+",
        "True",
        "gate_false_activation_rate",
        "reliability_score_shift|roc_auc_effect_of_unnecessary_switching",
        "B-MECH-K2",
        "reduces false firing under the evaluated pure mixture-shift controls",
        "solves distribution shift universally|guarantees no false alarms",
        "pending_compute",
    ],
    [
        "B-MECH-4",
        "B",
        "Q3",
        "ELARA-Bench-LA",
        "KS window-size / sample-size power sweep",
        "label_aligned_stress_only",
        "new theory/mechanism evidence",
        "KS power sweep",
        "KS with windows in {32,64,128,256,512}",
        "n/a (sweep)",
        "PRIMARY_KS_POWER_SWEEP",
        "validation only",
        "not previously inspected",
        "5+",
        "True",
        "detection_power",
        "false_activation_rate|roc_auc_effect",
        "B-MECH-K2",
        "reports the window/power tradeoff",
        "no power-vs-window claim outside the evaluated window set",
        "pending_compute",
    ],
    [
        "B-CERT-1",
        "B",
        "Q4",
        "B1/B2 + RGA-v2 partial-failure cells",
        "risk-dominance terms + finite-sample switching certificate",
        "label_aligned_stress_only|independent_modalities",
        "retrospective audit",
        "retrospective certificate from archived predictions",
        "n/a (retrospective)",
        "n/a (retrospective)",
        "PRIMARY_RETROSPECTIVE_CERTIFICATE",
        "validation + test for retrospective certificate only",
        "n/a",
        "n/a",
        "uses existing + new prediction archives",
        "fired_subset_paired_loss_difference + LCB",
        "q0|q1|delta0|delta1|pi_star",
        "no cross-family Holm",
        "retrospective evaluation certificates under defined stress protocols",
        "production safety certificate|clinical deployment guarantee",
        "pending_compute",
    ],
    [
        "C-EXP-EFFICIENTAD-1",
        "C",
        "Q1-exploratory",
        "MVTec 3D-AD",
        "EfficientAD supervised-paired",
        "independent_modalities",
        "inspected",
        "exploratory expansion (NOT Family A)",
        CAND_POOL,
        "n/a (descriptive)",
        "EXPLORATORY_DESCRIPTIVE",
        "validation only",
        "partially inspected",
        "30",
        "True",
        "roc_auc",
        "pr_auc|ece|brier",
        "no Holm (Family C)",
        "exploratory expansion: not part of the Family-A K=5 multiplicity",
        "confirmatory|preregistered|Family-A status",
        "pending_compute",
    ],
    [
        "C-EXP-EFFICIENTAD-2",
        "C",
        "Q1-exploratory",
        "MVTec 3D-AD",
        "EfficientAD one-class",
        "independent_modalities",
        "inspected",
        "exploratory expansion (NOT Family A)",
        CAND_POOL,
        "n/a (descriptive)",
        "EXPLORATORY_DESCRIPTIVE",
        "validation only",
        "partially inspected",
        "30",
        "True",
        "roc_auc",
        "pr_auc|ece|brier",
        "no Holm (Family C)",
        "exploratory expansion: not part of the Family-A K=5 multiplicity",
        "confirmatory|preregistered|Family-A status",
        "pending_compute",
    ],
    [
        "C-EXP-REAL3D-1",
        "C",
        "Q1-exploratory",
        "Real3D",
        "PatchCore supervised-paired",
        "independent_modalities",
        "inspected",
        "exploratory expansion (NOT Family A)",
        CAND_POOL,
        "n/a (descriptive)",
        "EXPLORATORY_DESCRIPTIVE",
        "validation only",
        "partially inspected",
        "30",
        "True",
        "roc_auc",
        "pr_auc|ece|brier",
        "no Holm (Family C)",
        "exploratory expansion: not part of the Family-A K=5 multiplicity",
        "confirmatory|preregistered|Real3D supports generalization",
        "pending_compute",
    ],
    [
        "C-EXP-REAL3D-2",
        "C",
        "Q1-exploratory",
        "Real3D",
        "PatchCore one-class",
        "independent_modalities",
        "inspected",
        "exploratory expansion (NOT Family A)",
        CAND_POOL,
        "n/a (descriptive)",
        "EXPLORATORY_DESCRIPTIVE",
        "validation only",
        "partially inspected",
        "30",
        "True",
        "roc_auc",
        "pr_auc|ece|brier",
        "no Holm (Family C)",
        "exploratory expansion: not part of the Family-A K=5 multiplicity",
        "confirmatory|preregistered|Real3D supports generalization",
        "pending_compute",
    ],
    [
        "D-CONTRACT-V1",
        "D",
        "Q5",
        "MPDD|Eyecandies|VisA (v1 candidates)",
        "v1 contract (invalidated)",
        "n/a",
        "uninspected (v1 claim)",
        "FUTURE LOCKED CONFIRMATORY REPLICATION",
        "n/a",
        "n/a",
        "INVALID_FOR_EXECUTION",
        "n/a",
        "untouched (claim under v1)",
        "n/a",
        "n/a",
        "n/a",
        "n/a",
        "D-CONFIRMATORY-FAMILY (v1)",
        "v1 preserved only as historical contract evidence; not executable",
        "any Family-D outcome under v1",
        "invalidated_v1",
    ],
    [
        "D-CONTRACT-V2",
        "D",
        "Q5",
        "TBD-eligibility-review",
        "v2 design (not frozen)",
        "n/a",
        "uninspected",
        "FUTURE LOCKED CONFIRMATORY REPLICATION",
        "n/a",
        "n/a",
        "V2_DESIGN_PENDING",
        "validation only",
        "untouched test partition; will be locked before evaluation under v2",
        "TBD",
        "True",
        "TBD",
        "TBD",
        "D-CONFIRMATORY-FAMILY",
        "only Family D may use the word confirmatory; only after a valid v2 contract is locked and independently reviewed",
        "any Family-D outcome in this task",
        "v2_design_pending",
    ],
]


CLAIMS_HEADER = [
    "claim_id",
    "manuscript_location",
    "claim_text",
    "benchmark",
    "protocol",
    "method",
    "metric",
    "value_in_text",
    "source_artifact",
    "value_in_artifact",
    "status",
    "required_fix",
]

CLAIMS_ROWS = [
    [
        "P2-A1-SECONDARY",
        "FAMILY_A_POWERED_AUDITED_REPRODUCTION_REPORT_v2.md sec 2.1",
        "Secondary all-comparator pilot audit: RGA+ ensemble vs 10 named comparators; 5 reach Holm significance within-cell at K=10",
        "MVTec 3D-AD",
        "PatchCore supervised-paired",
        "validation-frozen RGA+ vs 10 comparators",
        "roc_auc_delta + within-cell K=10 p_Holm",
        "0.7420 / 5-of-10",
        "experiments/phase2/statistics/family_a_powered_ensemble_inference.csv",
        "0.7420 / 5-of-10",
        "secondary_all_comparator_pilot_audit_complete",
        "N/A (frozen)",
    ],
    [
        "P2-A1-PRIMARY-RECOMPUTE",
        "FAMILY_A_POWERED_AUDITED_REPRODUCTION_REPORT_v2.md sec 2.2",
        "Primary Family-A K=5 cell-level surface for A-POWERED-1 (RGA+ vs static_attention)",
        "MVTec 3D-AD",
        "PatchCore supervised-paired",
        "validation-frozen RGA+ vs static_attention only",
        "roc_auc_delta + K=5 p_Holm (pending full family)",
        "pending",
        "experiments/phase2/predictions/A-POWERED-1__MVTec_3D-AD__PatchCore_supervised-paired (existing archive)",
        "pending",
        "primary_surface_pending_recompute",
        "rerun audited_analysis() against static_attention only; do not retrain",
    ],
    [
        "P2-A2",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Audited reproduction MVTec 3D-AD PatchCore held-out category",
        "MVTec 3D-AD",
        "PatchCore held-out category",
        "validation-frozen RGA+ vs static_attention",
        "roc_auc_delta + K=5 p_Holm",
        "pending",
        "(pending)",
        "(pending)",
        "pending_compute",
        "run experiment + populate prediction archive",
    ],
    [
        "P2-A3",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Audited reproduction MVTec LOCO-AD PatchCore supervised-paired",
        "MVTec LOCO-AD",
        "PatchCore supervised-paired",
        "validation-frozen RGA+ vs static_attention",
        "roc_auc_delta + K=5 p_Holm",
        "pending",
        "(pending)",
        "(pending)",
        "pending_compute",
        "run experiment + populate prediction archive",
    ],
    [
        "P2-A4",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Audited reproduction VisA RGB+edge supervised-paired",
        "VisA",
        "RGB+edge supervised-paired",
        "validation-frozen RGA+ vs static_attention",
        "roc_auc_delta + K=5 p_Holm",
        "pending",
        "(pending)",
        "(pending)",
        "pending_compute",
        "run experiment + populate prediction archive",
    ],
    [
        "P2-A5",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Audited reproduction UNSW-NB15 flow/conn/context",
        "UNSW-NB15",
        "flow/conn/context",
        "validation-frozen RGA+ vs static_attention",
        "roc_auc_delta + K=5 p_Holm",
        "pending",
        "(pending)",
        "(pending)",
        "pending_compute",
        "run experiment + populate prediction archive",
    ],
    [
        "P2-B1",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Reproduction of B1 mechanism endpoint at k=4 mean-gate locked tau=0.66",
        "ELARA-Bench-LA",
        "k-of-D mean-gate B1 zero-attack",
        "RGA vs static",
        "roc_auc_delta + 95% CI",
        "target +0.0506",
        "(pending)",
        "(pending)",
        "pending_compute",
        "run experiment + compare to Phase 1",
    ],
    [
        "P2-B2",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Reproduction of B2 mechanism endpoint",
        "ELARA-Bench-LA",
        "k-of-D mean-gate B2 max-attack",
        "RGA vs static",
        "roc_auc_delta + 95% CI",
        "target +0.0319",
        "(pending)",
        "(pending)",
        "pending_compute",
        "run experiment + compare to Phase 1",
    ],
    [
        "P2-RGA2",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) RGA-v2 promotion decision against locked criteria",
        "ELARA-Bench-LA",
        "RGA-v2 partial-failure surface",
        "gate candidates G0/G1/G2/G3 (G4 optional)",
        "clean_false_fire + per-k AUROC delta",
        "promotion_decision",
        "(pending)",
        "(pending)",
        "pending_compute",
        "run gate-candidate sweep with locked false-fire budget",
    ],
    [
        "P2-KS",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Mixture-shift false-fire control",
        "ELARA-Bench-LA",
        "pure mixture-shift",
        "KS reference vs category-aware",
        "gate_false_activation_rate",
        "(pending)",
        "(pending)",
        "(pending)",
        "pending_compute",
        "run controlled mixture-shift sweep",
    ],
    [
        "P2-CERT",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Risk-dominance + switching-certificate audit",
        "B1+B2 + RGA-v2 cells",
        "risk_dominance + LCB",
        "RGA gated vs static",
        "q0/q1/Delta0/Delta1/pi_star + LCB",
        "(pending)",
        "(pending)",
        "(pending)",
        "pending_compute",
        "compute from archived predictions",
    ],
    [
        "P2-FAMILYD-CONTRACT-V1",
        "FAMILY_D_V1_INVALIDATION_NOTICE.md",
        "Family D v1 contract preserved as historical evidence; INVALID_FOR_EXECUTION",
        "n/a",
        "n/a",
        "n/a",
        "N/A (contract)",
        "N/A",
        "docs/research/phase2/FAMILY_D_CONFIRMATORY_REPLICATION_CONTRACT.md",
        "N/A",
        "invalidated_v1",
        "no further action under v1",
    ],
    [
        "P2-FAMILYD-V2-DESIGN",
        "FAMILY_D_V2_DATASET_ELIGIBILITY_REVIEW.md",
        "Family D v2 design pending completion of eligibility review and resolution of protocol-level issues",
        "TBD",
        "TBD",
        "TBD",
        "N/A (contract)",
        "N/A",
        "docs/research/phase2/FAMILY_D_V2_DATASET_ELIGIBILITY_REVIEW.md",
        "N/A",
        "v2_design_pending",
        "complete eligibility review; identify at least one genuinely untouched RGB+depth candidate; resolve Eyecandies protocol question",
    ],
    [
        "P2-C-EXP-EFFICIENTAD-1",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Exploratory MVTec 3D-AD EfficientAD supervised-paired",
        "MVTec 3D-AD",
        "EfficientAD supervised-paired",
        "exploratory",
        "roc_auc",
        "pending",
        "(pending)",
        "(pending)",
        "pending_compute",
        "exploratory cell; not part of Family-A K=5",
    ],
    [
        "P2-C-EXP-EFFICIENTAD-2",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Exploratory MVTec 3D-AD EfficientAD one-class",
        "MVTec 3D-AD",
        "EfficientAD one-class",
        "exploratory",
        "roc_auc",
        "pending",
        "(pending)",
        "(pending)",
        "pending_compute",
        "exploratory cell; not part of Family-A K=5",
    ],
    [
        "P2-C-EXP-REAL3D-1",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Exploratory Real3D PatchCore supervised-paired",
        "Real3D",
        "PatchCore supervised-paired",
        "exploratory",
        "roc_auc",
        "pending",
        "(pending)",
        "(pending)",
        "pending_compute",
        "exploratory cell; not part of Family-A K=5",
    ],
    [
        "P2-C-EXP-REAL3D-2",
        "PHASE_2_INTERIM_REPORT_v2.md sec 4",
        "(pending) Exploratory Real3D PatchCore one-class",
        "Real3D",
        "PatchCore one-class",
        "exploratory",
        "roc_auc",
        "pending",
        "(pending)",
        "(pending)",
        "pending_compute",
        "exploratory cell; not part of Family-A K=5",
    ],
]


def _write_csv(path: Path, header: list[str], rows: list[list[str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        w.writerow(header)
        for r in rows:
            if len(r) != len(header):
                raise ValueError(
                    f"row id={r[0]!r}: has {len(r)} fields, expected {len(header)}"
                )
            w.writerow(r)


def main() -> int:
    _write_csv(OUT_REGISTRY, REGISTRY_HEADER, REGISTRY_ROWS)
    _write_csv(OUT_CLAIMS, CLAIMS_HEADER, CLAIMS_ROWS)
    # Round-trip verification
    for path, header in [(OUT_REGISTRY, REGISTRY_HEADER), (OUT_CLAIMS, CLAIMS_HEADER)]:
        with path.open() as f:
            rows = list(csv.reader(f))
        assert rows[0] == header, f"header mismatch in {path}"
        for r in rows[1:]:
            assert len(r) == len(header), f"{path}: row {r[0]!r} has {len(r)} fields"
        print(f"wrote {path} ({len(rows)-1} rows, {len(header)} columns)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
