"""Emit the Milestone-1 cross-protocol comparison table for the paper.

Pulls the five MVTec variant results JSONs (lightweight canonical,
M3DM canonical, PatchCore canonical, PatchCore supervised-paired,
PatchCore held-out) and renders a single LaTeX table summarising
static / RGA / strong-baseline ROC-AUC, the gate adapt rate, and the
category-aware mean reliability for each cell.

This is the Milestone-1 deliverable described in the upgrade plan:
"Does reliability gating help when natural RGB-D paired data has
stronger domain scorers?"
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

GENERATED_COMMENT = "% Auto-generated by emit_milestone1_comparison.py (do not edit by hand)"


def _fmt(value: Any, decimals: int = 3) -> str:
    if value is None or value == "":
        return "--"
    try:
        return f"{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return "--"


def _dig(payload: dict | None, *keys: str) -> Any:
    for key in keys:
        if payload is None:
            return None
        payload = payload.get(key)
    return payload


def _method_label(name: str | None) -> str:
    labels = {
        "random_forest": "RF",
        "confidence_weighted_mean": "Conf.-mean",
        "tent_score_adapter": "Tent",
        "ttt_pseudo_label_adapter": "TTT",
        "eata_score_adapter": "EATA",
        "sar_score_adapter": "SAR",
        "early_fusion_mlp": "MLP",
        "late_fusion_ensemble": "LFE",
        "static_attention": "Static",
        "craf_attention": "RGA",
        "rga_boosted_fusion": "RGA+ boost",
        "rga_meta_router": "RGA+ router",
    }
    return labels.get(str(name), str(name or "--"))


def _cell(payload: dict, comp_idx: dict | None = None, lookup_key: tuple[str, str] | None = None) -> dict[str, float | str | None]:
    """Phase 1.1: read validation-frozen comparator from audit CSV; no test-winner argmax."""
    cs = payload.get("clean_metric_summary", {})
    static = _dig(cs, "static_attention", "roc_auc", "mean")
    rga = _dig(cs, "craf_attention", "roc_auc", "mean")
    boosted_rows = [
        row.get("rga_boosted_fusion", {})
        for row in payload.get("table_1_clean_performance", [])
    ]
    boosted_applicable = any(row.get("selected_candidate") != "constant" for row in boosted_rows)
    rga_plus = _dig(cs, "rga_boosted_fusion", "roc_auc", "mean") if boosted_applicable else None

    # Validation-frozen comparator from Phase 1.C artifact.
    comp_name = None
    comp_roc = None
    if comp_idx is not None and lookup_key is not None:
        row = comp_idx.get(lookup_key) or {}
        comp_name = row.get("selected_comparator")
        raw = row.get("selected_comparator_test_auc")
        if raw not in (None, ""):
            try:
                comp_roc = float(raw)
            except (TypeError, ValueError):
                comp_roc = None

    cat_rel = _dig(payload, "table_8_category_aware", "category_aware_mean_reliability")
    cat_adapt = _dig(payload, "table_8_category_aware", "category_aware_adapt_rate")
    return {
        "static": static,
        "rga": rga,
        "delta": (rga - static) if (rga is not None and static is not None) else None,
        "rga_plus": rga_plus,
        "delta_plus": (rga_plus - comp_roc) if (rga_plus is not None and comp_roc is not None) else None,
        "comparator_name": _method_label(comp_name) if comp_name else "--",
        "comparator_roc": comp_roc,
        "cat_rel": cat_rel,
        "cat_adapt": cat_adapt,
    }


VARIANTS = [
    ("Lightweight image-stats", "canonical one-class", "experiments/fusion/mvtec3d_results.json"),
    ("PatchCore kNN", "canonical one-class", "experiments/fusion/mvtec3d_patchcore_results.json"),
    ("PatchCore kNN", "supervised paired", "experiments/fusion/mvtec3d_patchcore_supervised_paired_results.json"),
    ("PatchCore kNN", "held-out category", "experiments/fusion/mvtec3d_patchcore_heldout_results.json"),
]


VARIANT_TO_COMPARATOR_KEY = {
    ("Lightweight image-stats", "canonical one-class"): ("MVTec 3D-AD", "PatchCore canonical"),
    ("PatchCore kNN", "canonical one-class"): ("MVTec 3D-AD", "PatchCore canonical"),
    ("PatchCore kNN", "supervised paired"): ("MVTec 3D-AD", "PatchCore supervised"),
    ("PatchCore kNN", "held-out category"): ("MVTec 3D-AD", "PatchCore held-out"),
}


def render_table(repo_root: Path) -> str:
    """Phase 1.1: render milestone1 comparison using the validation-frozen
    primary comparator (Phase 1.C audit CSV) instead of post-hoc test-winner."""
    import csv
    comp_path = repo_root / "experiments/audit/audited_comparator_selection.csv"
    comp_idx: dict[tuple[str, str], dict] = {}
    if comp_path.exists():
        with comp_path.open() as f:
            for r in csv.DictReader(f):
                comp_idx[(r["benchmark"], r["protocol"])] = r

    rows = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llcccccccc}",
        r"\toprule",
        r"\textbf{Scorer} & \textbf{Protocol} & \textbf{Static} & \textbf{RGA} & "
        r"\textbf{$\Delta$} & \textbf{RGA+} & "
        r"\textbf{Audited $\Delta$ vs validation-frozen comparator} & "
        r"\textbf{Validation-frozen comparator} & "
        r"\textbf{Comparator test ROC} & "
        r"\textbf{Gate adapt} \\",
        r"\midrule",
    ]
    for scorer, protocol, rel_path in VARIANTS:
        full_path = (repo_root / rel_path)
        if not full_path.exists():
            rows.append(rf"{scorer} & {protocol} & -- & -- & -- & -- & -- & -- & -- & -- \\")
            continue
        payload = json.loads(full_path.read_text(encoding="utf-8"))
        comp_key = VARIANT_TO_COMPARATOR_KEY.get((scorer, protocol))
        cell = _cell(payload, comp_idx=comp_idx, lookup_key=comp_key)
        rows.append(
            rf"{scorer} & {protocol} & {_fmt(cell['static'])} & {_fmt(cell['rga'])} & "
            rf"{_fmt(cell['delta'])} & {_fmt(cell['rga_plus'])} & {_fmt(cell['delta_plus'])} & "
            rf"{cell['comparator_name']} & {_fmt(cell['comparator_roc'])} & "
            rf"{_fmt(cell['cat_adapt'])} \\"
        )
    rows += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("docs/research/tables/mvtec3d_milestone1_comparison.tex"))
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    args = parser.parse_args()

    table = render_table(args.repo_root)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")
    print(table)


if __name__ == "__main__":
    main()
