"""Emit the T2 (Global-KS mixture confounding) validation table."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

GENERATED_COMMENT = "% Auto-generated by emit_category_mixture_t2_table.py (do not edit by hand)"


def _fmt(value, decimals: int = 3) -> str:
    if value is None or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        return "--"
    return f"{float(value):.{decimals}f}"


def render(payload: dict) -> str:
    rows = payload.get("rows", [])
    mean_global = payload.get("mean_global_ks")
    mean_per_cat = payload.get("mean_max_per_category_ks")
    confirmed = payload.get("all_confirmed", False)

    out = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        r"\textbf{Seed} & \textbf{Global KS} & \textbf{Per-cat KS$_0$} & "
        r"\textbf{Per-cat KS$_1$} & \textbf{Per-cat KS$_2$} & \textbf{Confirmed?} \\",
        r"\midrule",
    ]
    for r in rows:
        per_cat = r.get("per_category_ks_distance", {})
        out.append(
            rf"{r.get('seed','?')} & {_fmt(r.get('global_ks_distance'))} & "
            rf"{_fmt(per_cat.get('0'))} & {_fmt(per_cat.get('1'))} & {_fmt(per_cat.get('2'))} & "
            rf"{'yes' if r.get('t2_confirmed') else 'no'} \\"
        )
    out += [
        r"\midrule",
        rf"\textbf{{Mean}} & \textbf{{{_fmt(mean_global)}}} & \multicolumn{{3}}{{c}}{{\textbf{{max per-cat: {_fmt(mean_per_cat)}}}}} & "
        rf"\textbf{{{'yes' if confirmed else 'no'}}} \\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("experiments/fusion/category_mixture_t2_validation.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/research/tables/category_mixture_t2.tex"),
    )
    args = parser.parse_args()
    payload = json.loads(args.input.read_text())
    table = render(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")
    print(table)


if __name__ == "__main__":
    main()
