"""Emit T7 PAC meta-router slack table."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

GENERATED_COMMENT = "% Auto-generated by emit_meta_router_pac_t7_table.py (do not edit by hand)"


def _fmt(value, decimals: int = 3) -> str:
    if value is None or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        return "--"
    return f"{float(value):.{decimals}f}"


def render(payload: dict) -> str:
    rows = payload.get("rows", [])
    delta = payload.get("delta", 0.05)
    out = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        r"\textbf{Fold / benchmark} & \textbf{$n$} & \textbf{$B$} & \textbf{$R$} & "
        + rf"\textbf{{Slack ($\delta={delta:.2f}$)}} & \textbf{{Bound tight?}} \\",
        r"\midrule",
    ]
    for row in rows:
        fold = str(row["fold"]).replace("_", r"\_").replace(".json", "")
        slack = float(row["slack"])
        tight = r"\textbf{yes}" if slack < 1.0 else "no"
        out.append(
            rf"{fold} & {row['n']} & {_fmt(row['B'], 1)} & {_fmt(row['R'], 3)} & "
            rf"{_fmt(slack, 3)} & {tight} \\"
        )
    out += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("experiments/fusion/meta_router_pac_audit.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/research/tables/meta_router_pac_t7.tex"),
    )
    args = parser.parse_args()
    payload = json.loads(args.input.read_text(encoding="utf-8"))
    table = render(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
