"""Emit T4 prevalence-sensitivity table from locked B-CERT-1 v2 terms."""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

from elara.certification.risk_dominance import RiskDominanceTerms, prevalence_sensitivity_rows

GENERATED_COMMENT = "% Auto-generated by emit_risk_dominance_t4_table.py (do not edit by hand)"
PI_VALUES = (0.0, 0.01, 0.05, 0.1, 0.25, 0.5)


def _fmt(value, decimals: int = 4, sign: bool = False) -> str:
    if value is None or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        return "--"
    if sign:
        return f"{float(value):+.{decimals}f}"
    return f"{float(value):.{decimals}f}"


def _load_terms(path: Path) -> list[RiskDominanceTerms]:
    rows: list[RiskDominanceTerms] = []
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            rows.append(
                RiskDominanceTerms(
                    gate_id=row["gate_id"],
                    scenario_id=row["scenario_id"],
                    q0=float(row["q0_clean_fire_rate"]),
                    q1=float(row["q1_degraded_fire_rate"]),
                    delta_0=float(row["delta_0_clean_cost"]),
                    delta_1=float(row["delta_1_degraded_benefit"]),
                    pi_star=float(row["pi_star_indifference_prevalence"])
                    if row["pi_star_indifference_prevalence"] not in ("", "nan")
                    else float("nan"),
                    n_clean_samples=int(row["n_clean_samples"]),
                    n_degraded_samples=int(row["n_degraded_samples"]),
                    notes=row.get("boundary_notice", ""),
                )
            )
    return rows


def render(terms_list: list[RiskDominanceTerms]) -> str:
    out = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llcccccc}",
        r"\toprule",
        r"\textbf{Scenario} & \textbf{$\pi$} & \textbf{$q_0$} & \textbf{$q_1$} & "
        r"\textbf{$\Delta_0$} & \textbf{$\Delta_1$} & \textbf{$\pi^\*$} & \textbf{Dominates?} \\",
        r"\midrule",
    ]
    for terms in terms_list:
        label = terms.scenario_id.replace("_", r"\_")
        rows = prevalence_sensitivity_rows(terms, pi_values=PI_VALUES)
        for idx, row in enumerate(rows):
            scenario_cell = label if idx == 0 else ""
            dominates = r"\textbf{yes}" if row["dominates"] else "no"
            out.append(
                rf"{scenario_cell} & {_fmt(row['pi'], 2)} & {_fmt(row['q0'], 3)} & "
                rf"{_fmt(row['q1'], 3)} & {_fmt(row['delta_0'], 4, sign=True)} & "
                rf"{_fmt(row['delta_1'], 4, sign=True)} & {_fmt(row['pi_star'], 3)} & {dominates} \\"
            )
        out.append(r"\midrule")
    if out[-1] == r"\midrule":
        out[-1] = r"\bottomrule"
    else:
        out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    out.append("")
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("experiments/phase2/certification/risk_dominance_terms_v2.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/research/tables/risk_dominance_t4_prevalence.tex"),
    )
    args = parser.parse_args()
    table = render(_load_terms(args.input))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
