"""Emit v3 result tables (in-domain MVTec 3D-AD + degradation-regime transfer)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def emit_indomain() -> None:
    d = json.loads((ROOT / "experiments/fusion/mvtec3d_v3_strong_detector_result.json").read_text())
    fc = d["fusion_clean_test_auroc"]
    rows = [
        ("RGA+ (router)", fc["rga_meta_router"], True),
        ("Random forest", fc["random_forest"], False),
        ("Confidence-weighted mean", fc["confidence_weighted_mean"], False),
        ("SAR (frozen strongest baseline)", fc["sar_score_adapter_FROZEN_STRONGEST_BASELINE"], False),
        ("TENT", fc["tent_score_adapter"], False),
        ("Static attention", fc["static_attention"], False),
    ]
    L = [
        "% Auto-generated by emit_v3_tables.py",
        r"\begin{tabular}{lc}",
        r"\toprule",
        r"\textbf{Method} & \textbf{Clean ROC-AUC} \\",
        r"\midrule",
    ]
    for name, val, bold in rows:
        nm = name.replace("_", r"\_")
        if bold:
            L.append(r"\textbf{" + nm + r"} & \textbf{" + f"{val:.4f}" + r"} \\")
        else:
            L.append(f"{nm} & {val:.4f}" + r" \\")
    L += [
        r"\midrule",
        r"\multicolumn{2}{l}{\footnotesize RGA+ vs SAR: $\Delta=+0.1615$, 95\% CI $[+0.1022,+0.2242]$} \\",
        r"\multicolumn{2}{l}{\footnotesize RGA+ vs static: $\Delta=+0.2357$, 95\% CI $[+0.1634,+0.3094]$ (per-sample bootstrap)} \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    (ROOT / "docs/research/tables/mvtec3d_v3_indomain.tex").write_text("\n".join(L))
    print("wrote mvtec3d_v3_indomain.tex")


def emit_degradation() -> None:
    dt = json.loads((ROOT / "experiments/fusion/degradation_transfer_v3_investigation.json").read_text())
    L = [
        "% Auto-generated by emit_v3_tables.py",
        r"\begin{tabular}{cccccc}",
        r"\toprule",
        r"$\alpha$ & $r_{\mathrm{depth}}$ & Static & Conf.-wt. & \textbf{RGA} & RGA$-$CW \\",
        r"\midrule",
    ]
    for r in dt["rows"]:
        star = r"$^{*}$" if r["rga_beats_cw_significant"] else ""
        L.append(
            f"{r['alpha_depth_degradation']:.2f} & {r['reliability_depth']:.3f} & "
            f"{r['auroc_static']:.4f} & {r['auroc_confidence_weighted']:.4f} & "
            r"\textbf{" + f"{r['auroc_rga_gated']:.4f}" + r"} & "
            f"{r['delta_rga_minus_cw']:+.4f}{star}" + r" \\"
        )
    L += [
        r"\bottomrule",
        r"\end{tabular}",
        r"",
        r"% *: RGA significantly beats confidence-weighting (per-sample bootstrap CI excludes 0).",
    ]
    (ROOT / "docs/research/tables/degradation_transfer_v3.tex").write_text("\n".join(L))
    print("wrote degradation_transfer_v3.tex")


if __name__ == "__main__":
    emit_indomain()
    emit_degradation()
