"""Phase 1.D — emit the locked audited-reanalysis statistical artifacts.

Reads the validation-frozen selection artifacts (Phase 1.B and 1.C) and
the per-seed clean-performance tables, and produces:

  1. experiments/audit/statistical_family_registry.csv
  2. experiments/audit/audited_ensemble_inference_results.csv
  3. experiments/audit/descriptive_seed_variability.csv

Statistical method (honest fallback under existing JSONs):

  - The seed-averaged-ensemble DeLong specified by
    STATISTICAL_ANALYSIS_POLICY.md §2 requires raw per-seed test
    predictions; the current JSONs DO NOT archive them. The runner
    patch in this commit logs predictions for future runs (Phase 1.F);
    today's audited analysis uses the policy's secondary option:
    **single-representative-seed DeLong** with all other seeds
    reported descriptively for stability.
  - Representative seed = first seed in the table_1_clean_performance
    list (seed 42 for every cell).
  - The DeLong p-value used is the one already logged at
    `table_1_clean_performance[0].delong_p_rga_plus_vs_baseline[<chosen_head>][<chosen_comparator>]`.
  - Holm correction is applied across the locked Family A K=5 set:
    {A2, A3, A5, A7, A8}. Protocol diagnostics (A1, A4, A6) are
    reported with raw p-values only and are NOT in the Holm K-count.
  - Family B audited mechanism endpoints (B1, B2) are corrected within
    a separate K=2 family.
  - Family C exploratory cells receive no correction.

No Fisher combination. No bootstrap over seeds as a confirmatory test.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path

GENERATED_COMMENT = "% Auto-generated by emit_locked_audited_statistics.py (do not edit by hand)"


# ---------------------------------------------------------------------------
# Family registry — single source of truth for Holm K-count and language
# ---------------------------------------------------------------------------

FAMILY_REGISTRY = [
    # cell_id, benchmark, protocol, family, status, pairing_strength, holm_included, allowed, forbidden
    ("A1", "MVTec 3D-AD", "PatchCore canonical", "A", "protocol-diagnostic", "independent_modalities", False),
    ("A2", "MVTec 3D-AD", "PatchCore supervised", "A", "audited primary reanalysis", "independent_modalities", True),
    ("A3", "MVTec 3D-AD", "PatchCore held-out", "A", "audited primary reanalysis", "independent_modalities", True),
    ("A4", "MVTec LOCO-AD", "PatchCore canonical", "A", "protocol-diagnostic", "independent_modalities", False),
    ("A5", "MVTec LOCO-AD", "PatchCore supervised", "A", "audited primary reanalysis", "independent_modalities", True),
    ("A6", "VisA", "RGB+edge canonical", "A", "protocol-diagnostic", "derived_view_proxy", False),
    ("A7", "VisA", "RGB+edge supervised", "A", "audited primary reanalysis", "derived_view_proxy", True),
    ("A8", "UNSW-NB15", "flow/conn/context", "A", "audited primary reanalysis", "naturally_structured_views", True),
    ("C1", "Real3D-AD", "PCA shape + depth supervised", "C", "exploratory", "naturally_structured_views", False),
    ("C2", "VisA", "RGB+random noise-floor", "C", "exploratory", "derived_view_proxy", False),
    ("C3", "UNSW-NB15", "held-out attack categories", "C", "exploratory", "naturally_structured_views", False),
]

JSON_PATHS = {
    ("MVTec 3D-AD", "PatchCore canonical"): "experiments/fusion/mvtec3d_patchcore_results.json",
    ("MVTec 3D-AD", "PatchCore supervised"): "experiments/fusion/mvtec3d_patchcore_supervised_paired_results.json",
    ("MVTec 3D-AD", "PatchCore held-out"): "experiments/fusion/mvtec3d_patchcore_heldout_results.json",
    ("MVTec LOCO-AD", "PatchCore canonical"): "experiments/fusion/mvtec_loco_patchcore_results.json",
    ("MVTec LOCO-AD", "PatchCore supervised"): "experiments/fusion/mvtec_loco_patchcore_supervised_paired_results.json",
    ("Real3D-AD", "PCA shape + depth supervised"): "experiments/fusion/real3d_supervised_paired_results.json",
    ("VisA", "RGB+edge canonical"): "experiments/fusion/visa_fusion_results.json",
    ("VisA", "RGB+edge supervised"): "experiments/fusion/visa_supervised_paired_results.json",
    ("VisA", "RGB+random noise-floor"): "experiments/fusion/visa_supervised_paired_noise_floor_results.json",
    ("UNSW-NB15", "flow/conn/context"): "experiments/fusion/unsw_paired_results.json",
    ("UNSW-NB15", "held-out attack categories"): "experiments/fusion/unsw_heldout_attack_results.json",
}


def _load_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open() as f:
        return list(csv.DictReader(f))


def _holm_bonferroni(p_values: dict[str, float], K: int) -> dict[str, float]:
    """Standard Holm-Bonferroni with explicit K (allows K > number of finite p)."""
    finite = [
        (k, float(p))
        for k, p in p_values.items()
        if p is not None and isinstance(p, (int, float)) and math.isfinite(float(p))
    ]
    finite.sort(key=lambda kv: kv[1])
    out: dict[str, float] = {}
    running = 0.0
    for rank, (k, raw_p) in enumerate(finite, start=1):
        cand = min(1.0, raw_p * (K - rank + 1))
        running = max(running, cand)
        out[k] = running
    return out


def _safe_float(x):
    try:
        return float(x) if x is not None and math.isfinite(float(x)) else None
    except (TypeError, ValueError):
        return None


# ---------------------------------------------------------------------------
# Main emit
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument(
        "--rga-csv", type=Path, default=Path("experiments/audit/rga_plus_validation_frozen_selection.csv")
    )
    parser.add_argument(
        "--comparator-csv", type=Path, default=Path("experiments/audit/audited_comparator_selection.csv")
    )
    parser.add_argument(
        "--family-registry-out",
        type=Path,
        default=Path("experiments/audit/statistical_family_registry.csv"),
    )
    parser.add_argument(
        "--inference-out",
        type=Path,
        default=Path("experiments/audit/audited_ensemble_inference_results.csv"),
    )
    parser.add_argument(
        "--variability-out",
        type=Path,
        default=Path("experiments/audit/descriptive_seed_variability.csv"),
    )
    args = parser.parse_args()

    rga_rows = _load_csv(args.repo_root / args.rga_csv)
    comp_rows = _load_csv(args.repo_root / args.comparator_csv)
    # Index by (benchmark, protocol) ensemble row only.
    rga_idx = {(r["benchmark"], r["protocol"]): r for r in rga_rows if r.get("seed_or_ensemble") == "ensemble"}
    comp_idx = {(r["benchmark"], r["protocol"]): r for r in comp_rows}

    # --- Statistical family registry CSV ---
    fr_fields = [
        "analysis_family",
        "cell_id",
        "benchmark",
        "protocol",
        "analysis_status",
        "pairing_strength",
        "rga_plus_selection_rule",
        "comparator_selection_rule",
        "inference_status",
        "holm_included",
        "holm_family_size",
        "allowed_claim",
        "forbidden_claim",
    ]
    holm_A_size = sum(1 for row in FAMILY_REGISTRY if row[3] == "A" and row[6])  # K=5
    holm_C_size = 0
    family_rows: list[dict] = []
    for cell_id, benchmark, protocol, family, status, pairing, holm in FAMILY_REGISTRY:
        family_size = {"A": holm_A_size, "C": holm_C_size}.get(family, 0)
        if status == "protocol-diagnostic":
            allowed = "ROC-AUC at chance level only. Canonical PR/ECE/Brier are degenerate-predictor artefacts (Phase 1.A audit)."
            forbidden = "No PR-AUC/ECE/Brier promotion. No superiority claim."
        elif status == "audited primary reanalysis":
            allowed = "Audited inferential summary of validation-frozen RGA+ vs validation-frozen primary comparator, single-representative-seed DeLong (seed 42), Holm-corrected within Family A K=5."
            forbidden = "No 'confirmatory' or 'pre-registered' label. No 'RGA+ beats every baseline' framing."
        elif status == "exploratory":
            allowed = "Descriptive point estimates only. No Holm correction."
            forbidden = "No confirmatory or superiority claim."
        else:
            allowed = "(see policy)"
            forbidden = ""
        family_rows.append(
            {
                "analysis_family": family,
                "cell_id": cell_id,
                "benchmark": benchmark,
                "protocol": protocol,
                "analysis_status": status,
                "pairing_strength": pairing,
                "rga_plus_selection_rule": "validation_frozen (router vs boost; tie-break boost)",
                "comparator_selection_rule": "validation_frozen (max seed-mean val ROC-AUC; deterministic name tie-break)",
                "inference_status": (
                    "single_representative_seed_DeLong (raw-prediction archive pending; "
                    "ensemble DeLong + sample bootstrap deferred)"
                    if status == "audited primary reanalysis"
                    else "descriptive only"
                ),
                "holm_included": holm,
                "holm_family_size": family_size if holm else 0,
                "allowed_claim": allowed,
                "forbidden_claim": forbidden,
            }
        )

    args.family_registry_out.parent.mkdir(parents=True, exist_ok=True)
    with args.family_registry_out.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fr_fields)
        w.writeheader()
        for r in family_rows:
            w.writerow(r)
    print(f"Wrote {args.family_registry_out} ({len(family_rows)} rows)")

    # --- Audited inference results CSV ---
    inference_rows: list[dict] = []
    holm_input: dict[str, float] = {}  # cell_id -> raw p (Family A confirmatory only)
    representative_seed_idx = 0

    for cell_id, benchmark, protocol, family, status, _pairing, holm in FAMILY_REGISTRY:
        if status not in {"audited primary reanalysis", "exploratory", "protocol-diagnostic"}:
            continue
        rel_path = JSON_PATHS.get((benchmark, protocol))
        if rel_path is None:
            continue
        jpath = args.repo_root / rel_path
        if not jpath.exists():
            continue
        payload = json.loads(jpath.read_text())
        per_seed = payload.get("table_1_clean_performance", []) or []
        if not per_seed:
            continue
        rga_ens = rga_idx.get((benchmark, protocol)) or {}
        comp_ens = comp_idx.get((benchmark, protocol)) or {}
        chosen_head = rga_ens.get("selected_head")
        chosen_comparator = comp_ens.get("selected_comparator")
        if not chosen_head or not chosen_comparator:
            continue

        # Representative seed DeLong (seed-42 by index).
        rep_seed = per_seed[representative_seed_idx]
        chosen_head_key = "rga_meta_router" if chosen_head == "router" else "rga_boosted_fusion"
        delong_map = (rep_seed.get("delong_p_rga_plus_vs_baseline") or {}).get(chosen_head_key) or {}
        delong_p_rep = delong_map.get(chosen_comparator)
        delong_p_rep = _safe_float(delong_p_rep)

        # Seed-mean and SD for RGA+ head and comparator
        rga_aucs = []
        comp_aucs = []
        delta_aucs = []
        delong_seed_list = []
        for r in per_seed:
            h = r.get(chosen_head_key) or {}
            b = r.get(chosen_comparator) or {}
            rga_auc = _safe_float(h.get("roc_auc"))
            comp_auc = _safe_float(b.get("roc_auc"))
            if rga_auc is None or comp_auc is None:
                continue
            rga_aucs.append(rga_auc)
            comp_aucs.append(comp_auc)
            delta_aucs.append(rga_auc - comp_auc)
            ps = ((r.get("delong_p_rga_plus_vs_baseline") or {}).get(chosen_head_key) or {}).get(chosen_comparator)
            if isinstance(ps, (int, float)) and math.isfinite(float(ps)):
                delong_seed_list.append(float(ps))
        if not rga_aucs:
            continue
        n_seeds = len(rga_aucs)

        def _mean(xs):
            return sum(xs) / len(xs)

        def _sd(xs):
            if len(xs) < 2:
                return 0.0
            m = _mean(xs)
            return math.sqrt(sum((x - m) ** 2 for x in xs) / (len(xs) - 1))

        rga_mean = _mean(rga_aucs)
        rga_sd = _sd(rga_aucs)
        comp_mean = _mean(comp_aucs)
        comp_sd = _sd(comp_aucs)
        delta_mean = _mean(delta_aucs)

        if status == "audited primary reanalysis" and holm and delong_p_rep is not None:
            holm_input[cell_id] = delong_p_rep

        inference_rows.append(
            {
                "analysis_family": family,
                "cell_id": cell_id,
                "benchmark": benchmark,
                "protocol": protocol,
                "analysis_status": status,
                "rga_plus_head": chosen_head,
                "comparator": chosen_comparator,
                "n_seeds": n_seeds,
                "n_test_samples": "(not archived; raw predictions pending)",
                "ensemble_rga_plus_auc": rga_mean,
                "ensemble_rga_plus_auc_sd_over_seeds": rga_sd,
                "ensemble_comparator_auc": comp_mean,
                "ensemble_comparator_auc_sd_over_seeds": comp_sd,
                "ensemble_delta_auc": delta_mean,
                "delong_p_raw_single_rep_seed": delong_p_rep,
                "delong_p_holm_if_applicable": None,  # filled below
                "bootstrap_ci_low": None,  # pending raw predictions
                "bootstrap_ci_high": None,  # pending raw predictions
                "per_seed_delong_p_values": "|".join(f"{v:.6f}" for v in delong_seed_list),
                "analysis_label": (
                    "single_representative_seed_DeLong (seed 42) — ensemble DeLong + paired sample bootstrap "
                    "pending raw-prediction archive (Phase 1.F runner patch)"
                    if status == "audited primary reanalysis"
                    else "descriptive only"
                ),
                "claim_status": "locked_audited_reanalysis",
            }
        )

    # Apply Holm to Family A confirmatory cells only.
    if holm_input:
        holm_out = _holm_bonferroni(holm_input, K=holm_A_size)
        for row in inference_rows:
            if row["cell_id"] in holm_out:
                row["delong_p_holm_if_applicable"] = holm_out[row["cell_id"]]

    inf_fields = [
        "analysis_family",
        "cell_id",
        "benchmark",
        "protocol",
        "analysis_status",
        "rga_plus_head",
        "comparator",
        "n_seeds",
        "n_test_samples",
        "ensemble_rga_plus_auc",
        "ensemble_rga_plus_auc_sd_over_seeds",
        "ensemble_comparator_auc",
        "ensemble_comparator_auc_sd_over_seeds",
        "ensemble_delta_auc",
        "delong_p_raw_single_rep_seed",
        "delong_p_holm_if_applicable",
        "bootstrap_ci_low",
        "bootstrap_ci_high",
        "per_seed_delong_p_values",
        "analysis_label",
        "claim_status",
    ]
    args.inference_out.parent.mkdir(parents=True, exist_ok=True)
    with args.inference_out.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=inf_fields)
        w.writeheader()
        for r in inference_rows:
            w.writerow(r)
    print(f"Wrote {args.inference_out} ({len(inference_rows)} rows)")

    # --- Descriptive seed variability (per-method) ---
    var_rows: list[dict] = []
    method_names = (
        "static_attention",
        "craf_attention",
        "rga_meta_router",
        "rga_boosted_fusion",
        "random_forest",
        "early_fusion_mlp",
        "late_fusion_ensemble",
        "confidence_weighted_mean",
        "tent_score_adapter",
        "ttt_pseudo_label_adapter",
        "eata_score_adapter",
        "sar_score_adapter",
    )
    for cell_id, benchmark, protocol, family, _status, _pairing, _holm in FAMILY_REGISTRY:
        rel_path = JSON_PATHS.get((benchmark, protocol))
        if rel_path is None:
            continue
        jpath = args.repo_root / rel_path
        if not jpath.exists():
            continue
        payload = json.loads(jpath.read_text())
        per_seed = payload.get("table_1_clean_performance", []) or []
        for method in method_names:
            aucs: list[float] = []
            for r in per_seed:
                b = r.get(method) or {}
                v = _safe_float(b.get("roc_auc"))
                if v is not None:
                    aucs.append(v)
            if not aucs:
                continue
            mean = sum(aucs) / len(aucs)
            sd = math.sqrt(sum((x - mean) ** 2 for x in aucs) / (len(aucs) - 1)) if len(aucs) >= 2 else 0.0
            var_rows.append(
                {
                    "analysis_family": family,
                    "cell_id": cell_id,
                    "method": method,
                    "n_seeds": len(aucs),
                    "mean_auc": mean,
                    "sd_auc": sd,
                    "min_auc": min(aucs),
                    "max_auc": max(aucs),
                    "descriptive_only": True,
                }
            )
    var_fields = [
        "analysis_family",
        "cell_id",
        "method",
        "n_seeds",
        "mean_auc",
        "sd_auc",
        "min_auc",
        "max_auc",
        "descriptive_only",
    ]
    args.variability_out.parent.mkdir(parents=True, exist_ok=True)
    with args.variability_out.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=var_fields)
        w.writeheader()
        for r in var_rows:
            w.writerow(r)
    print(f"Wrote {args.variability_out} ({len(var_rows)} rows)")


if __name__ == "__main__":
    main()
