"""Emit the tightened T7 PAC slack table (loose vs tight side-by-side)."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

GENERATED = "% Auto-generated by emit_meta_router_pac_t7_tight_table.py"


def _fmt(value, decimals: int = 3) -> str:
    if value is None or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        return "--"
    return f"{float(value):.{decimals}f}"


def render(payload: dict) -> str:
    rows = payload.get("rows", [])
    delta = payload.get("delta", 0.05)
    out = [
        GENERATED,
        r"\begin{tabular}{lccccccc}",
        r"\toprule",
        r"\textbf{Fold} & $n$ & $B_{\mathrm{emp}}$ & $R_{\mathrm{emp}}$ & "
        + r"\textbf{Slack loose} & \textbf{Slack tight} & \textbf{Tightening} & \textbf{Usable?} \\",
        r"\midrule",
    ]
    for row in rows:
        fold = str(row["fold"]).replace("_", r"\_").replace(".csv", "").replace("_inputs", "")
        tight = float(row.get("slack_tight", float("nan")))
        loose = float(row.get("slack_loose", float("nan")))
        factor = row.get("tightening_factor")
        useful = r"\textbf{yes}" if math.isfinite(tight) and tight < 0.5 else "no"
        if isinstance(factor, (int, float)) and math.isfinite(factor):
            factor_str = _fmt(factor, 1) + r"$\times$"
        else:
            factor_str = "--"
        out.append(
            rf"{fold} & {row['n']} & {_fmt(row.get('B_emp'), 2)} & "
            rf"{_fmt(row.get('R_emp'), 2)} & {_fmt(loose, 2)} & "
            rf"{_fmt(tight, 3)} & "
            rf"{factor_str} & "
            rf"{useful} \\"
        )
    out += [
        r"\bottomrule",
        r"\end{tabular}",
        r"",
        r"% Tight slack uses Bartlett-Mendelson 2002 expected-Rademacher bound",
        r"% (2 L B_emp R_emp / sqrt(n)) + Maurer-Pontil empirical-Bernstein concentration.",
        r"% Loose slack preserves the original worst-case bound for reference.",
    ]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path,
                        default=Path("experiments/fusion/meta_router_pac_audit_tight.json"))
    parser.add_argument("--output", type=Path,
                        default=Path("docs/research/tables/meta_router_pac_t7_tight.tex"))
    args = parser.parse_args()
    payload = json.loads(args.input.read_text(encoding="utf-8"))
    table = render(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
