"""Emit GDR end-to-end audit table."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

GENERATED_COMMENT = "% Auto-generated by emit_gate_decision_rule_table.py (do not edit by hand)"


def _fmt(value, decimals: int = 3) -> str:
    if value is None or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        return "--"
    return f"{float(value):.{decimals}f}"


def render(payload: dict) -> str:
    out = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llcccccc}",
        r"\toprule",
        r"\textbf{Scenario} & \textbf{Regime} & \textbf{Expected} & \textbf{Observed} & "
        r"\textbf{Coherence} & \textbf{Cert.} & \textbf{Fire rate} & \textbf{Pass} \\",
        r"\midrule",
    ]
    for row in payload.get("scenarios", []):
        expected = r"\textbf{switch}" if row["expected_switch_allowed"] else "suppress"
        observed = r"\textbf{switch}" if row["observed_switch_allowed"] else "suppress"
        passed = r"\textbf{yes}" if row["audit_pass"] else "no"
        scenario = str(row["scenario_id"]).replace("_", r"\_")
        regime = str(row["regime"]).replace("/", r"/")
        out.append(
            rf"{scenario} & {regime} & {expected} & {observed} & "
            rf"{_fmt(row.get('coherence'), 3)} & "
            rf"{'yes' if row.get('certified') else 'no'} & "
            rf"{_fmt(row.get('fire_rate'), 3)} & {passed} \\"
        )
    summary = payload.get("n_pass", 0)
    total = payload.get("n_scenarios", 0)
    out += [
        r"\midrule",
        rf"\multicolumn{{7}}{{l}}{{\textbf{{Summary:}} {summary}/{total} scenarios match the predictive rule.}} \\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("experiments/fusion/gate_decision_rule_e2e_audit.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/research/tables/gate_decision_rule_e2e.tex"),
    )
    args = parser.parse_args()
    payload = json.loads(args.input.read_text(encoding="utf-8"))
    table = render(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
