"""Emit per-domain causal attribution tables (B3 Double-ML estimates).

Reads `table_9_causal_attribution` from one or more benchmark results JSONs
and renders a LaTeX table with per-domain Average Treatment Effects, 95%
asymptotic confidence intervals, and p-values.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

GENERATED_COMMENT = "% Auto-generated by emit_causal_attribution.py (do not edit by hand)"


def _fmt(value, decimals: int = 4) -> str:
    if value is None or (isinstance(value, float) and value != value):
        return "--"
    try:
        return f"{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return "--"


def _ci(low, high, decimals: int = 4) -> str:
    if low is None or high is None:
        return "--"
    try:
        return rf"[{_fmt(low, decimals)}, {_fmt(high, decimals)}]"
    except (TypeError, ValueError):
        return "--"


def render_table(results_path: Path, label_prefix: str = "") -> str:
    payload = json.loads(results_path.read_text(encoding="utf-8"))
    causal = payload.get("table_9_causal_attribution", {})
    per_domain = causal.get("per_domain", [])
    if not per_domain:
        return GENERATED_COMMENT + "\n% no causal attribution rows in " + str(results_path) + "\n"
    rows = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"\textbf{Domain} & \textbf{ATE} & \textbf{95\% CI} & \textbf{Seeds} \\",
        r"\midrule",
    ]
    for entry in per_domain:
        rows.append(
            rf"{label_prefix}{entry['domain']} & "
            rf"{_fmt(entry.get('ate_mean'))} & "
            rf"{_ci(entry.get('ate_ci_low'), entry.get('ate_ci_high'))} & "
            rf"{int(entry.get('n_seeds_with_finite_ate', 0))} \\"
        )
    rows += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="Benchmark results JSON")
    parser.add_argument("--output", type=Path, required=True, help="Target .tex path")
    parser.add_argument("--label-prefix", default="", help="Optional prefix for the domain column")
    args = parser.parse_args()

    table = render_table(args.input, label_prefix=args.label_prefix)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")
    print(table)


if __name__ == "__main__":
    main()
