"""Emit per-category clean-AUROC tables for MVTec 3D-AD + LOCO-AD variants.

Standard practice for MVTec-family benchmarks is to report per-category
AUROC alongside the mean. Reviewers expect to see whether method gains
come from a uniform lift across categories or are concentrated in a few
strong categories. This script consumes the ``table_1b_per_category_clean``
block produced by the breakthrough runner and emits one LaTeX table per
benchmark variant, columns = methods, rows = categories.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

GENERATED_COMMENT = "% Auto-generated by emit_per_category_breakdown.py (do not edit by hand)"

# Order of methods rendered as columns. RGA / RGA+ columns are bolded
# implicitly via the header; per-cell bolding by mean is left to a future
# pass to avoid LaTeX-table fragility.
METHOD_ORDER = [
    ("static_attention", "Static"),
    ("craf_attention", "RGA"),
    ("rga_meta_router", "RGA+ router"),
    ("rga_boosted_fusion", "RGA+ boost"),
    ("random_forest", "RF"),
    ("early_fusion_mlp", "MLP"),
    ("late_fusion_ensemble", "LFE"),
    ("tent_score_adapter", "Tent"),
    ("ttt_pseudo_label_adapter", "TTT"),
    ("eata_score_adapter", "EATA"),
    ("sar_score_adapter", "SAR"),
    ("confidence_weighted_mean", "Conf-m"),
]


# Benchmark variants to emit per-category tables for.
BENCHMARKS = [
    {
        "label": "MVTec 3D-AD PatchCore canonical",
        "results": "experiments/fusion/mvtec3d_patchcore_results.json",
        "output_name": "mvtec3d_patchcore_per_category.tex",
    },
    {
        "label": "MVTec 3D-AD PatchCore supervised-paired",
        "results": "experiments/fusion/mvtec3d_patchcore_supervised_paired_results.json",
        "output_name": "mvtec3d_patchcore_supervised_paired_per_category.tex",
    },
    {
        "label": "MVTec 3D-AD PatchCore held-out category",
        "results": "experiments/fusion/mvtec3d_patchcore_heldout_results.json",
        "output_name": "mvtec3d_patchcore_heldout_per_category.tex",
    },
    {
        "label": "MVTec LOCO-AD PatchCore canonical",
        "results": "experiments/fusion/mvtec_loco_patchcore_results.json",
        "output_name": "mvtec_loco_patchcore_per_category.tex",
    },
    {
        "label": "MVTec LOCO-AD PatchCore supervised-paired",
        "results": "experiments/fusion/mvtec_loco_patchcore_supervised_paired_results.json",
        "output_name": "mvtec_loco_patchcore_supervised_paired_per_category.tex",
    },
    {
        "label": "VisA RGB+edge supervised-paired",
        "results": "experiments/fusion/visa_supervised_paired_results.json",
        "output_name": "visa_supervised_paired_per_category.tex",
    },
]


def _fmt(value, decimals: int = 3) -> str:
    if value is None or (isinstance(value, float) and value != value):
        return "--"
    try:
        return f"{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return "--"


def render_per_category_table(results_payload: dict, caption_label: str) -> str | None:
    per_cat = results_payload.get("table_1b_per_category_clean", {})
    if not per_cat:
        return None
    methods_in_payload: set[str] = set()
    for cat_dict in per_cat.values():
        methods_in_payload.update(cat_dict.keys())
    visible_methods = [(key, display) for key, display in METHOD_ORDER if key in methods_in_payload]
    if not visible_methods:
        return None

    col_spec = "l" + "c" * len(visible_methods)
    rows = [
        GENERATED_COMMENT,
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
        r"\textbf{Category} & " + " & ".join(rf"\textbf{{{display}}}" for _, display in visible_methods) + r" \\",
        r"\midrule",
    ]

    cats = sorted(per_cat.keys())
    method_means: dict[str, list[float]] = {key: [] for key, _ in visible_methods}
    for cat in cats:
        cells = [_safe_cat_name(cat)]
        for key, _display in visible_methods:
            value = per_cat[cat].get(key, {}).get("mean")
            cells.append(_fmt(value))
            if isinstance(value, (int, float)) and value == value:
                method_means[key].append(float(value))
        rows.append(" & ".join(cells) + r" \\")

    rows.append(r"\midrule")
    mean_cells = [r"\textbf{Mean}"]
    for key, _ in visible_methods:
        vals = method_means[key]
        if vals:
            mean_cells.append(rf"\textbf{{{_fmt(sum(vals)/len(vals))}}}")
        else:
            mean_cells.append("--")
    rows.append(" & ".join(mean_cells) + r" \\")
    rows += [r"\bottomrule", r"\end{tabular}", f"% caption_hint: {caption_label}", ""]
    return "\n".join(rows)


def _safe_cat_name(cat: str) -> str:
    return str(cat).replace("_", r"\_")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument(
        "--tables-dir",
        type=Path,
        default=Path("docs/research/tables"),
    )
    args = parser.parse_args()

    args.tables_dir.mkdir(parents=True, exist_ok=True)
    emitted = []
    skipped = []
    for entry in BENCHMARKS:
        path = args.repo_root / entry["results"]
        if not path.exists():
            skipped.append(entry["label"])
            continue
        payload = json.loads(path.read_text(encoding="utf-8"))
        rendered = render_per_category_table(payload, entry["label"])
        if rendered is None:
            skipped.append(entry["label"])
            continue
        out_path = args.tables_dir / entry["output_name"]
        out_path.write_text(rendered, encoding="utf-8")
        emitted.append(str(out_path))

    print(f"Emitted {len(emitted)} per-category tables.")
    for path in emitted:
        print(f"  {path}")
    if skipped:
        print()
        print(f"Skipped {len(skipped)} benchmark variants (no per-category data):")
        for label in skipped:
            print(f"  {label}")


if __name__ == "__main__":
    main()
