"""Emit the Milestone-1 cross-protocol comparison table for the paper.

Pulls the five MVTec variant results JSONs (lightweight canonical,
M3DM canonical, PatchCore canonical, PatchCore supervised-paired,
PatchCore held-out) and renders a single LaTeX table summarising
static / RGA / strong-baseline ROC-AUC, the gate adapt rate, and the
category-aware mean reliability for each cell.

This is the Milestone-1 deliverable described in the upgrade plan:
"Does reliability gating help when natural RGB-D paired data has
stronger domain scorers?"
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

GENERATED_COMMENT = "% Auto-generated by emit_milestone1_comparison.py (do not edit by hand)"


def _fmt(value: float | None, decimals: int = 3) -> str:
    if value is None:
        return "--"
    try:
        return f"{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return "--"


def _dig(payload: dict | None, *keys: str) -> Any:
    for key in keys:
        if payload is None:
            return None
        payload = payload.get(key)
    return payload


def _method_label(name: str | None) -> str:
    labels = {
        "random_forest": "RF",
        "confidence_weighted_mean": "Conf.-mean",
        "tent_score_adapter": "Tent",
        "ttt_pseudo_label_adapter": "TTT",
        "early_fusion_mlp": "MLP",
        "late_fusion_ensemble": "LFE",
        "static_attention": "Static",
        "craf_attention": "RGA",
        "rga_boosted_fusion": "RGA+ boost",
        "rga_meta_router": "RGA+ router",
    }
    return labels.get(str(name), str(name or "--"))


def _cell(payload: dict) -> dict[str, float | str | None]:
    cs = payload.get("clean_metric_summary", {})
    static = _dig(cs, "static_attention", "roc_auc", "mean")
    rga = _dig(cs, "craf_attention", "roc_auc", "mean")
    boosted_rows = [
        row.get("rga_boosted_fusion", {})
        for row in payload.get("table_1_clean_performance", [])
    ]
    boosted_applicable = any(row.get("selected_candidate") != "constant" for row in boosted_rows)
    rga_plus = _dig(cs, "rga_boosted_fusion", "roc_auc", "mean") if boosted_applicable else None
    best_name = None
    best_roc = None
    for name, metrics in cs.items():
        if name in {"craf_attention", "rga_boosted_fusion", "rga_meta_router"}:
            continue
        roc = _dig(metrics, "roc_auc", "mean")
        if roc is None:
            continue
        if best_roc is None or float(roc) > float(best_roc):
            best_name = name
            best_roc = roc
    cat_rel = _dig(payload, "table_8_category_aware", "category_aware_mean_reliability")
    cat_adapt = _dig(payload, "table_8_category_aware", "category_aware_adapt_rate")
    return {
        "static": static,
        "rga": rga,
        "delta": (rga - static) if (rga is not None and static is not None) else None,
        "rga_plus": rga_plus,
        "delta_plus": (rga_plus - best_roc) if (rga_plus is not None and best_roc is not None) else None,
        "best_name": _method_label(best_name),
        "best_roc": best_roc,
        "cat_rel": cat_rel,
        "cat_adapt": cat_adapt,
    }


VARIANTS = [
    ("Lightweight image-stats", "canonical one-class", "experiments/fusion/mvtec3d_results.json"),
    ("PatchCore kNN", "canonical one-class", "experiments/fusion/mvtec3d_patchcore_results.json"),
    ("PatchCore kNN", "supervised paired", "experiments/fusion/mvtec3d_patchcore_supervised_paired_results.json"),
    ("PatchCore kNN", "held-out category", "experiments/fusion/mvtec3d_patchcore_heldout_results.json"),
]


def render_table(repo_root: Path) -> str:
    rows = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llcccccccc}",
        r"\toprule",
        r"\textbf{Scorer} & \textbf{Protocol} & \textbf{Static} & \textbf{RGA} & \textbf{$\Delta$} & \textbf{RGA+} & \textbf{$\Delta$ vs best} & \textbf{Best non-router} & \textbf{Best ROC} & \textbf{Gate adapt} \\",
        r"\midrule",
    ]
    for scorer, protocol, rel_path in VARIANTS:
        full_path = (repo_root / rel_path)
        if not full_path.exists():
            rows.append(rf"{scorer} & {protocol} & -- & -- & -- & -- & -- & -- & -- & -- \\")
            continue
        payload = json.loads(full_path.read_text(encoding="utf-8"))
        cell = _cell(payload)
        rows.append(
            rf"{scorer} & {protocol} & {_fmt(cell['static'])} & {_fmt(cell['rga'])} & "
            rf"{_fmt(cell['delta'])} & {_fmt(cell['rga_plus'])} & {_fmt(cell['delta_plus'])} & "
            rf"{cell['best_name']} & {_fmt(cell['best_roc'])} & "
            rf"{_fmt(cell['cat_adapt'])} \\"
        )
    rows += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("docs/research/tables/mvtec3d_milestone1_comparison.tex"))
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    args = parser.parse_args()

    table = render_table(args.repo_root)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    print(f"Wrote {args.output}")
    print(table)


if __name__ == "__main__":
    main()
