"""Generate paper tables and figures from reliability-gated fusion benchmark JSON."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np

METHOD_ORDER = [
    ("random_forest", "Random forest"),
    ("confidence_weighted_mean", "Conf.-weighted mean"),
    ("tent_score_adapter", "Tent score adapter"),
    ("ttt_pseudo_label_adapter", "TTT pseudo-label"),
    ("early_fusion_mlp", "Early fusion MLP"),
    ("late_fusion_ensemble", "Late fusion ensemble"),
    ("static_attention", "Static attention"),
    ("craf_attention", "RGA attention"),
]

SYSTEM_NAME = "ELARA"
METHOD_NAME = "RGA"
GENERATED_COMMENT = "% Auto-generated by the ELARA/RGA paper asset generator"


def _finite(value: Any) -> bool:
    return value is not None and isinstance(value, (int, float)) and math.isfinite(float(value))


def _fmt(value: Any, digits: int = 3) -> str:
    if not _finite(value):
        return "--"
    return f"{float(value):.{digits}f}"


def _fmt_pm(value: Any, std: Any, digits: int = 4) -> str:
    if not _finite(value):
        return "--"
    if not _finite(std) or abs(float(std)) < 0.5 * 10 ** (-digits):
        return _fmt(value, digits)
    return rf"{_fmt(value, digits)}$\pm${_fmt(std, digits)}"


def _fmt_ci(low: Any, high: Any, digits: int = 4) -> str:
    if not _finite(low) or not _finite(high):
        return "--"
    return rf"[{_fmt(low, digits)}, {_fmt(high, digits)}]"


def _fmt_pm_ci(vals: dict[str, Any], metric: str, digits: int = 4) -> str:
    rendered = _fmt_pm(vals.get(metric), vals.get(f"{metric}_std"), digits=digits)
    ci = _fmt_ci(vals.get(f"{metric}_ci_low"), vals.get(f"{metric}_ci_high"), digits=digits)
    return rendered if ci == "--" else rf"{rendered} {ci}"


def _latex_text(value: str) -> str:
    return value.replace("_", r"\_")


def _short_status(value: Any) -> str:
    text = str(value or "--")
    if text == "undefined: fewer than three finite domains":
        return "n/a (fewer than 3 domains)"
    if text == "undefined: insufficient finite CDA impacts or constant comparison values":
        return "n/a (constant/insufficient)"
    return text


def _bold_best(
    rows: list[tuple[str, str, dict[str, Any]]],
    metric: str,
    higher_is_better: bool = True,
    digits: int = 4,
) -> dict[str, str]:
    values = [(key, vals.get(metric)) for key, _, vals in rows if _finite(vals.get(metric))]
    if not values:
        return {key: _fmt_pm_ci(vals, metric, digits=digits) for key, _, vals in rows}
    best_value = max(v for _, v in values) if higher_is_better else min(v for _, v in values)
    out: dict[str, str] = {}
    for key, _, vals in rows:
        value = vals.get(metric)
        rendered = _fmt_pm_ci(vals, metric, digits=digits)
        if _finite(value) and abs(float(value) - float(best_value)) <= max(1e-12, 0.5 * 10 ** (-digits)):
            rendered = rf"\textbf{{{rendered}}}"
        out[key] = rendered
    return out


def _load(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _clean_rows(data: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    if data.get("clean_metric_summary"):
        output = []
        summary = data["clean_metric_summary"]
        for key, label in METHOD_ORDER:
            if key not in summary:
                continue
            metrics: dict[str, Any] = {}
            for metric, vals in summary[key].items():
                metrics[metric] = vals.get("mean")
                metrics[f"{metric}_std"] = vals.get("std")
                metrics[f"{metric}_ci_low"] = vals.get("ci_low")
                metrics[f"{metric}_ci_high"] = vals.get("ci_high")
                metrics[f"{metric}_n"] = vals.get("n")
            output.append((key, label, metrics))
        return output

    seed_rows = data["table_1_clean_performance"]
    output = []
    for key, label in METHOD_ORDER:
        metric_names = sorted({metric for row in seed_rows for metric in row[key]})
        metrics: dict[str, Any] = {}
        for metric in metric_names:
            values = [row[key].get(metric) for row in seed_rows]
            values = [float(v) for v in values if _finite(v)]
            if not values:
                continue
            metrics[metric] = float(np.mean(values))
            metrics[f"{metric}_std"] = float(np.std(values))
            if len(values) == 1:
                metrics[f"{metric}_ci_low"] = values[0]
                metrics[f"{metric}_ci_high"] = values[0]
            else:
                metrics[f"{metric}_ci_low"] = float(np.percentile(values, 2.5))
                metrics[f"{metric}_ci_high"] = float(np.percentile(values, 97.5))
        output.append((key, label, metrics))
    return output


def write_domain_scorer_table(metadata: dict[str, Any], out_dir: Path) -> None:
    metrics = metadata.get("domain_scorer_metrics", {})
    if not metrics:
        return
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"\textbf{Domain} & \textbf{Rows} & \textbf{Pos. rate} & \textbf{OOF ROC} & \textbf{OOF PR} \\",
        r"\midrule",
    ]
    for domain in metadata.get("domain_order", sorted(metrics)):
        vals = metrics[domain]
        lines.append(
            rf"{_latex_text(domain)} & {int(vals['rows'])} & {_fmt(vals['positive_rate'])} & "
            rf"{_fmt(vals['oof_roc_auc'], 4)} & {_fmt(vals['oof_pr_auc'], 4)} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / "real_domain_scorers.tex", "\n".join(lines))


def write_benchmark_metadata_table(metadata: dict[str, Any], out_dir: Path) -> None:
    if not metadata:
        return
    natural = "yes" if metadata.get("natural_pairing") else "no"
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"\textbf{Property} & \textbf{Value} \\",
        r"\midrule",
        rf"Benchmark type & {_latex_text(str(metadata.get('benchmark_type', '--')))} \\",
        rf"Natural pairing & {natural} \\",
        rf"Pairing unit & {_latex_text(str(metadata.get('pairing_unit', '--')))} \\",
        rf"Samples & {int(metadata.get('samples', 0)) if _finite(metadata.get('samples')) else '--'} \\",
        rf"Positive fraction & {_fmt(metadata.get('positive_fraction_actual'))} \\",
        rf"Scorer train fraction & {_fmt(metadata.get('scorer_train_fraction'), 2)} \\",
        rf"Source-row disjoint splits & {'yes' if metadata.get('source_row_disjoint_splits') else 'no'} \\",
        rf"Split column & {_latex_text(str(metadata.get('fusion_split_column', '--')))} \\",
        rf"Domains & {_latex_text(', '.join(metadata.get('domain_order', [])))} \\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    _write(out_dir / "elara_benchmark_metadata.tex", "\n".join(lines))


def write_paired_benchmark_metadata_table(metadata: dict[str, Any], out_dir: Path) -> None:
    if not metadata:
        return
    natural = "yes" if metadata.get("natural_pairing") else "no"
    categories = ", ".join(metadata.get("categories", []))
    score_protocol = metadata.get("score_protocol", {}) or {}
    fit_split = str(score_protocol.get("normal_reference_split", "--"))
    fit_defect = str(score_protocol.get("normal_reference_defect_type", "--"))
    fit_samples = score_protocol.get("normal_reference_samples")
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"\textbf{Property} & \textbf{Value} \\",
        r"\midrule",
        rf"Benchmark type & {_latex_text(str(metadata.get('benchmark_type', '--')))} \\",
        rf"Natural pairing & {natural} \\",
        rf"Categories & {_latex_text(categories or '--')} \\",
        rf"Samples & {int(metadata.get('samples', 0)) if _finite(metadata.get('samples')) else '--'} \\",
        rf"Positive fraction & {_fmt(metadata.get('positive_fraction_actual'))} \\",
        rf"Score fit split & {_latex_text(f'{fit_split}/{fit_defect}')} \\",
        rf"Score fit samples & {int(fit_samples) if _finite(fit_samples) else '--'} \\",
        rf"Score normalization & {_latex_text(str(score_protocol.get('score_normalization', '--')))} \\",
        rf"Domains & {_latex_text(', '.join(metadata.get('domain_order', [])))} \\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    _write(out_dir / "mvtec3d_benchmark_metadata.tex", "\n".join(lines))


def write_clean_table(data: dict[str, Any], out_dir: Path) -> None:
    rows = _clean_rows(data)
    roc = _bold_best(rows, "roc_auc", higher_is_better=True, digits=4)
    pr = _bold_best(rows, "pr_auc", higher_is_better=True, digits=4)
    f1 = _bold_best(rows, "f1", higher_is_better=True, digits=4)
    ece = _bold_best(rows, "ece", higher_is_better=False, digits=4)
    brier = _bold_best(rows, "brier", higher_is_better=False, digits=4)

    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        r"\textbf{Method} & \textbf{ROC-AUC} & \textbf{PR-AUC} & \textbf{F1} & \textbf{ECE} & \textbf{Brier} \\",
        r"\midrule",
    ]
    for key, label, _ in rows:
        lines.append(
            rf"{label} & {roc[key]} & {pr[key]} & {f1[key]} & {ece[key]} & {brier[key]} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / "elara_clean_results.tex", "\n".join(lines))


def write_named_clean_table(data: dict[str, Any], out_dir: Path, filename: str) -> None:
    rows = _clean_rows(data)
    roc = _bold_best(rows, "roc_auc", higher_is_better=True, digits=4)
    pr = _bold_best(rows, "pr_auc", higher_is_better=True, digits=4)
    f1 = _bold_best(rows, "f1", higher_is_better=True, digits=4)
    ece = _bold_best(rows, "ece", higher_is_better=False, digits=4)
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"\textbf{Method} & \textbf{ROC-AUC} & \textbf{PR-AUC} & \textbf{F1} & \textbf{ECE} \\",
        r"\midrule",
    ]
    for key, label, _ in rows:
        lines.append(rf"{label} & {roc[key]} & {pr[key]} & {f1[key]} & {ece[key]} \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / filename, "\n".join(lines))


def write_clean_ci_table(data: dict[str, Any], out_dir: Path) -> None:
    rows = _clean_rows(data)
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"\textbf{Method} & \textbf{ROC-AUC 95\% CI} & \textbf{PR-AUC 95\% CI} & \textbf{F1 95\% CI} \\",
        r"\midrule",
    ]
    for _, label, vals in rows:
        lines.append(
            rf"{label} & {_fmt_ci(vals.get('roc_auc_ci_low'), vals.get('roc_auc_ci_high'))} & "
            rf"{_fmt_ci(vals.get('pr_auc_ci_low'), vals.get('pr_auc_ci_high'))} & "
            rf"{_fmt_ci(vals.get('f1_ci_low'), vals.get('f1_ci_high'))} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / "elara_clean_ci_results.tex", "\n".join(lines))


def write_missing_table(data: dict[str, Any], out_dir: Path) -> None:
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{ccccc}",
        r"\toprule",
        rf"\textbf{{Dropout}} & \textbf{{Static ROC}} & \textbf{{{METHOD_NAME} ROC}} & \textbf{{Delta}} & \textbf{{Delta 95\% CI}} \\",
        r"\midrule",
    ]
    for row in data["table_4_missing_modality"]:
        delta = row.get("delta_auc")
        if delta is None and _finite(row.get("craf_auc")) and _finite(row.get("static_auc")):
            delta = row["craf_auc"] - row["static_auc"]
        lines.append(
            rf"{_fmt(row['dropout_prob'], 1)} & {_fmt(row['static_auc'], 4)} & {_fmt(row['craf_auc'], 4)} & "
            rf"{_fmt(delta, 4)} & {_fmt_ci(row.get('delta_auc_ci_low'), row.get('delta_auc_ci_high'))} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / "elara_missing_results.tex", "\n".join(lines))


def write_drift_table(data: dict[str, Any], out_dir: Path) -> None:
    rows = data["figure_1_drift_curves"]["degradation_aucs"]
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        rf"\textbf{{Domain}} & \textbf{{Static}} & \textbf{{{METHOD_NAME}}} & \textbf{{Delta}} & \textbf{{Seeds}} \\",
        r"\midrule",
    ]
    for domain, vals in rows.items():
        domain_latex = _latex_text(domain)
        lines.append(
            rf"{domain_latex} & {_fmt_pm_ci(vals, 'static')} & {_fmt_pm_ci(vals, 'craf')} & "
            rf"{_fmt(vals.get('delta'), 4)} & {int(vals.get('n_seeds', 0))} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / "elara_drift_summary.tex", "\n".join(lines))



def _cal_cell(cal: dict[str, Any], prefix: str) -> str:
    mean = cal.get(prefix)
    std = cal.get(f"{prefix}_std")
    ci_lo = cal.get(f"{prefix}_ci_low")
    ci_hi = cal.get(f"{prefix}_ci_high")
    pm = _fmt_pm(mean, std, digits=4)
    ci = _fmt_ci(ci_lo, ci_hi, digits=4)
    return pm if ci == "--" else rf"{pm} {ci}"


def write_calibration_table(data: dict[str, Any], out_dir: Path) -> None:
    cal = data["table_5_calibration"]
    cda = data["cda_validation"]
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lcc}",
        r"\toprule",
        rf"\textbf{{Metric}} & \textbf{{Static}} & \textbf{{{METHOD_NAME}}} \\",
        r"\midrule",
        rf"ECE & {_cal_cell(cal, 'static_ece')} & {_cal_cell(cal, 'craf_ece')} \\",
        rf"Brier & {_cal_cell(cal, 'static_brier')} & {_cal_cell(cal, 'craf_brier')} \\",
        rf"CDA samples & -- & {int(cda['n_samples'])} \\",
        rf"CDA/ECE Spearman & -- & {_fmt(cda.get('spearman_cda_vs_ece_reliability'))} \\",
        rf"CDA/ECE Spearman status & -- & {_latex_text(_short_status(cda.get('spearman_cda_vs_ece_reliability_status')))} \\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    _write(out_dir / "elara_calibration_cda.tex", "\n".join(lines))


def write_adversarial_table(data: dict[str, Any], out_dir: Path) -> None:
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llcccc}",
        r"\toprule",
        rf"\textbf{{Attack}} & \textbf{{Target}} & \textbf{{Static ROC}} & \textbf{{{METHOD_NAME} ROC}} & \textbf{{Delta}} & \textbf{{Delta 95\% CI}} \\",
        r"\midrule",
    ]
    for row in data["table_3_adversarial"]:
        attack = _latex_text(row["attack"])
        target = _latex_text(row["target_domain"])
        lines.append(
            rf"{attack} & {target} & {_fmt(row['static_auc'], 4)} & {_fmt(row['craf_auc'], 4)} & "
            rf"{_fmt(row['delta_auc'], 4)} & {_fmt_ci(row.get('delta_auc_ci_low'), row.get('delta_auc_ci_high'))} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / "elara_adversarial_results.tex", "\n".join(lines))


def write_tau_sweep_table(data: dict[str, Any], out_dir: Path) -> None:
    rows = data.get("table_6_tau_sweep", [])
    if not rows:
        return
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        rf"\textbf{{Condition}} & $\boldsymbol{{\tau}}$ & \textbf{{Static ROC}} & \textbf{{{METHOD_NAME} ROC}} & \textbf{{Delta}} & \textbf{{Delta 95\% CI}} & \textbf{{Adapt rate}} \\",
        r"\midrule",
    ]
    for row in rows:
        delta = row.get("delta_auc")
        if delta is None and _finite(row.get("craf_auc")) and _finite(row.get("static_auc")):
            delta = row["craf_auc"] - row["static_auc"]
        tau_raw = row.get("tau")
        if isinstance(tau_raw, str):
            tau_cell = _latex_text(tau_raw)
        else:
            tau_cell = _fmt(tau_raw, 2)
        lines.append(
            rf"{_latex_text(str(row.get('condition', '--')))} & {tau_cell} & "
            rf"{_fmt(row.get('static_auc'), 4)} & {_fmt(row.get('craf_auc'), 4)} & "
            rf"{_fmt(delta, 4)} & {_fmt_ci(row.get('delta_auc_ci_low'), row.get('delta_auc_ci_high'))} & "
            rf"{_fmt(row.get('adaptation_rate'), 3)} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / "elara_tau_sweep_results.tex", "\n".join(lines))


def write_component_ablation_table(data: dict[str, Any], out_dir: Path) -> None:
    rows = data.get("table_7_component_ablation", [])
    if not rows:
        return
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{llccccc}",
        r"\toprule",
        rf"\textbf{{Variant}} & \textbf{{Attack}} & \textbf{{Static ROC}} & \textbf{{{METHOD_NAME} ROC}} & \textbf{{Delta}} & \textbf{{Delta 95\% CI}} & \textbf{{Adapt rate}} \\",
        r"\midrule",
    ]
    for row in rows:
        delta = row.get("delta_auc")
        if delta is None and _finite(row.get("craf_auc")) and _finite(row.get("static_auc")):
            delta = row["craf_auc"] - row["static_auc"]
        lines.append(
            rf"{_latex_text(str(row.get('variant', '--')))} & {_latex_text(str(row.get('attack', '--')))} & "
            rf"{_fmt(row.get('static_auc'), 4)} & {_fmt(row.get('craf_auc'), 4)} & "
            rf"{_fmt(delta, 4)} & {_fmt_ci(row.get('delta_auc_ci_low'), row.get('delta_auc_ci_high'))} & "
            rf"{_fmt(row.get('adaptation_rate'), 3)} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / "elara_component_ablation_results.tex", "\n".join(lines))


def write_category_aware_table(data: dict[str, Any], out_dir: Path, output_basename: str = "elara_category_aware_drift.tex") -> None:
    summary = data.get("table_8_category_aware", {})
    if not summary:
        return
    global_adapt = summary.get("global_adapt_rate")
    cat_adapt = summary.get("category_aware_adapt_rate")
    global_rel = summary.get("global_mean_reliability")
    cat_rel = summary.get("category_aware_mean_reliability")
    n_seeds = summary.get("n_seeds", 0)
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lcc}",
        r"\toprule",
        rf"\textbf{{Drift signal}} & \textbf{{Adapt rate}} & \textbf{{Mean reliability}} \\",
        r"\midrule",
        rf"Global KS reference & {_fmt(global_adapt, 3)} & {_fmt(global_rel, 3)} \\",
        rf"Category-aware KS reference & {_fmt(cat_adapt, 3)} & {_fmt(cat_rel, 3)} \\",
        r"\bottomrule",
        r"\end{tabular}",
        rf"% n_seeds={int(n_seeds)}; misfire_reduction={_fmt(summary.get('misfire_reduction_absolute'), 3)}",
        "",
    ]
    _write(out_dir / output_basename, "\n".join(lines))


def write_failure_case_table(data: dict[str, Any], out_dir: Path) -> None:
    cases = data.get("failure_case_analysis", {}).get("representative_cases", [])
    if not cases:
        return
    lines = [
        GENERATED_COMMENT,
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        rf"\textbf{{Case}} & \textbf{{Label}} & \textbf{{Static $p$}} & \textbf{{{METHOD_NAME} $p$}} & \textbf{{Sample}} \\",
        r"\midrule",
    ]
    for case in cases[:5]:
        lines.append(
            rf"{_latex_text(case.get('case_type', '--'))} & {int(case.get('label', 0))} & "
            rf"{_fmt(case.get('static_prob'), 4)} & {_fmt(case.get('craf_prob'), 4)} & "
            rf"{_latex_text(str(case.get('sample_id', '--'))[:30])} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    _write(out_dir / "elara_failure_cases.tex", "\n".join(lines))


def _set_style() -> None:
    plt.rcParams.update(
        {
            "font.size": 10,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "figure.dpi": 150,
            "savefig.dpi": 250,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
        }
    )


def _save(fig: plt.Figure, path: Path) -> None:
    fig.patch.set_facecolor("white")
    fig.savefig(path, facecolor="white", edgecolor="none", transparent=False)


def plot_clean_benchmark(data: dict[str, Any], out_dir: Path) -> None:
    rows = _clean_rows(data)
    labels = [label for _, label, _ in rows]
    roc = [vals["roc_auc"] for _, _, vals in rows]
    pr = [vals["pr_auc"] for _, _, vals in rows]
    x = np.arange(len(labels))
    width = 0.36

    fig, ax = plt.subplots(figsize=(8.2, 3.4))
    ax.bar(x - width / 2, roc, width, label="ROC-AUC", color="#2f6f73")
    ax.bar(x + width / 2, pr, width, label="PR-AUC", color="#c46a32")
    lower = 0.95 if min(roc + pr) > 0.95 else 0.0
    ax.set_ylim(lower, 1.0)
    ax.set_ylabel("Score")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=25, ha="right")
    ax.legend(frameon=False, ncol=2)
    ax.grid(axis="y", alpha=0.22)
    fig.tight_layout()
    _save(fig, out_dir / "elara_clean_benchmark.png")
    plt.close(fig)


def plot_missing_modality(data: dict[str, Any], out_dir: Path) -> None:
    rows = data["table_4_missing_modality"]
    x = [row["dropout_prob"] for row in rows]
    static = [row["static_auc"] for row in rows]
    craf = [row["craf_auc"] for row in rows]

    fig, ax = plt.subplots(figsize=(4.6, 3.2))
    ax.plot(x, static, marker="o", linewidth=2, label="Static attention", color="#2f6f73")
    ax.plot(x, craf, marker="s", linewidth=2, label=METHOD_NAME, color="#c46a32")
    ax.set_xlabel("Additional domain dropout probability")
    ax.set_ylabel("ROC-AUC")
    lower = max(0.0, min(static + craf) - 0.02)
    ax.set_ylim(lower, 1.0)
    ax.grid(alpha=0.24)
    ax.legend(frameon=False)
    fig.tight_layout()
    _save(fig, out_dir / "elara_missing_modality.png")
    plt.close(fig)


def plot_drift_curves(data: dict[str, Any], out_dir: Path) -> None:
    drift = data["table_2_drift_robustness"]
    fig, axes = plt.subplots(1, len(drift), figsize=(8.2, 2.8), sharey=True)
    if len(drift) == 1:
        axes = [axes]
    for ax, (domain, rows) in zip(axes, drift.items()):
        noise = [row["noise_level"] for row in rows]
        static = [row["static_auc"] for row in rows]
        craf = [row["craf_auc"] for row in rows]
        ax.plot(noise, static, marker="o", linewidth=2, label="Static", color="#2f6f73")
        ax.plot(noise, craf, marker="s", linewidth=2, label=METHOD_NAME, color="#c46a32")
        ax.set_title(domain.replace("_", " "))
        ax.set_xlabel("Noise")
        ax.grid(alpha=0.24)
    axes[0].set_ylabel("ROC-AUC")
    axes[-1].legend(frameon=False, loc="lower left")
    fig.tight_layout()
    _save(fig, out_dir / "elara_drift_curves.png")
    plt.close(fig)


def plot_calibration(data: dict[str, Any], out_dir: Path) -> None:
    cal = data["table_5_calibration"]
    fig, ax = plt.subplots(figsize=(4.2, 3.6))
    ax.plot([0, 1], [0, 1], linestyle="--", color="#555555", linewidth=1, label="Ideal")
    for key, label, marker, color in [
        ("static_bins", "Static attention", "o", "#2f6f73"),
        ("craf_bins", METHOD_NAME, "s", "#c46a32"),
    ]:
        bins = cal[key]
        ax.plot(
            [b["mean_confidence"] for b in bins],
            [b["mean_accuracy"] for b in bins],
            marker=marker,
            linewidth=2,
            label=label,
            color=color,
        )
    ax.set_xlim(0.0, 1.0)
    ax.set_ylim(0.0, 1.0)
    ax.set_xlabel("Mean confidence")
    ax.set_ylabel("Empirical positive rate")
    ax.grid(alpha=0.24)
    ax.legend(frameon=False)
    fig.tight_layout()
    _save(fig, out_dir / "elara_calibration.png")
    plt.close(fig)


def plot_cda_impacts(data: dict[str, Any], out_dir: Path) -> None:
    impacts = data["cda_validation"]["mean_cf_impacts_abs"]
    labels = [domain.replace("_", " ") for domain in impacts]
    values = list(impacts.values())

    fig, ax = plt.subplots(figsize=(4.2, 3.0))
    ax.bar(labels, values, color="#6a7f3f")
    ax.set_ylabel("Mean absolute probability change")
    ax.grid(axis="y", alpha=0.24)
    fig.tight_layout()
    _save(fig, out_dir / "elara_cda_impacts.png")
    plt.close(fig)


def plot_adversarial_delta(data: dict[str, Any], out_dir: Path) -> None:
    rows = [
        row
        for row in data["table_3_adversarial"]
        if row.get("target_domain") == "all"
    ]
    attack_abbrev = {
        "zero_attack": "zero",
        "max_attack": "max",
        "gaussian_noise": "gaussian",
    }
    labels = [
        attack_abbrev.get(r["attack"], r["attack"].replace("_", " "))
        for r in rows
    ]
    values = [r["delta_auc"] for r in rows]
    colors = ["#2f6f73" if v >= 0 else "#c46a32" for v in values]

    fig, ax = plt.subplots(figsize=(4.8, 3.2))
    x = np.arange(len(labels))
    ax.axhline(0.0, color="#444444", linewidth=1)
    bars = ax.bar(x, values, color=colors, width=0.55)
    ax.set_ylabel(f"{METHOD_NAME} - static ROC-AUC")
    ax.set_xlabel("All-domain score attack")
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.grid(axis="y", alpha=0.24)
    upper = max(values) + 0.01
    lower = min(values) - 0.01
    ax.set_ylim(min(lower, -0.005), max(upper, 0.055))
    for bar, value in zip(bars, values):
        va = "bottom" if value >= 0 else "top"
        y = value + (0.002 if value >= 0 else -0.002)
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            y,
            f"{value:+.4f}",
            ha="center",
            va=va,
            fontsize=9,
        )
    fig.tight_layout()
    _save(fig, out_dir / "elara_adversarial_delta.png")
    plt.close(fig)


def plot_failure_cases(data: dict[str, Any], out_dir: Path) -> None:
    """Scatter of static-vs-RGA per-sample probabilities for representative cases.

    Highlights disagreements: samples where one method is on the correct side
    of 0.5 and the other isn't. Reviewer-requested figure (manuscript review
    v2 §3.3) — counters the "RGA is mechanistically identical to static"
    framing by visualizing concrete per-sample wins and losses.
    """
    cases = data.get("failure_case_analysis", {}).get("representative_cases", [])
    if not cases:
        return

    rows = []
    for case in cases:
        s = case.get("static_prob")
        c = case.get("craf_prob")
        y = case.get("label")
        if s is None or c is None or y is None:
            continue
        rows.append({
            "static": float(s),
            "craf": float(c),
            "label": int(y),
            "case_type": case.get("case_type", "?"),
        })
    if not rows:
        return

    fig, ax = plt.subplots(figsize=(4.6, 4.6))
    # Reference diagonal: where both methods agree
    ax.plot([0, 1], [0, 1], "--", color="#888888", linewidth=0.9, label="Agreement (y = x)")
    # Decision-boundary cross-hairs at 0.5
    ax.axhline(0.5, color="#cccccc", linewidth=0.6)
    ax.axvline(0.5, color="#cccccc", linewidth=0.6)

    # Plot positives and negatives separately
    pos = [r for r in rows if r["label"] == 1]
    neg = [r for r in rows if r["label"] == 0]
    if pos:
        ax.scatter(
            [r["static"] for r in pos],
            [r["craf"] for r in pos],
            color="#c46a32",
            edgecolor="#7d3f12",
            s=58,
            label="Anomaly (y=1)",
            zorder=3,
        )
    if neg:
        ax.scatter(
            [r["static"] for r in neg],
            [r["craf"] for r in neg],
            color="#2f6f73",
            edgecolor="#143033",
            s=58,
            marker="s",
            label="Normal (y=0)",
            zorder=3,
        )

    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_xlabel("Static attention probability")
    ax.set_ylabel(f"{METHOD_NAME} probability")
    ax.grid(alpha=0.18)
    ax.legend(loc="lower right", fontsize=8, framealpha=0.9)
    fig.tight_layout()
    _save(fig, out_dir / "elara_failure_cases.png")
    plt.close(fig)


def plot_system_architecture(out_dir: Path) -> None:
    fig, ax = plt.subplots(figsize=(8.8, 3.8))
    ax.set_axis_off()
    ax.set_xlim(0.2, 10.05)
    ax.set_ylim(0.35, 5.95)

    def box(x: float, y: float, w: float, h: float, text: str, color: str, fontsize: float = 8.6) -> None:
        rect = plt.Rectangle((x, y), w, h, linewidth=1.2, edgecolor="#333333", facecolor=color)
        ax.add_patch(rect)
        ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=fontsize, wrap=True)

    def arrow(x1: float, y1: float, x2: float, y2: float) -> None:
        ax.annotate(
            "",
            xy=(x2, y2),
            xytext=(x1, y1),
            arrowprops={"arrowstyle": "->", "linewidth": 1.2, "color": "#333333"},
        )

    domains = [
        ("Fraud\ntransactions", 0.4, 5.05),
        ("Cyber\ntelemetry", 0.4, 4.20),
        ("Behavior\nsessions", 0.4, 3.35),
        ("Text\nevidence", 0.4, 2.50),
        ("RGB--3D\ninspection", 0.4, 1.65),
        ("Clinical\nsignals", 0.4, 0.80),
    ]
    for label, x, y in domains:
        box(x, y, 1.45, 0.56, label, "#e8f1f2", fontsize=8.2)
        arrow(x + 1.45, y + 0.28, 2.45, y + 0.28)

    box(2.45, 0.55, 1.55, 5.2, "Domain\nexperts\n\nscores\nconfidence\nembeddings", "#f5efe6")
    arrow(4.0, 3.35, 4.55, 3.35)
    box(4.55, 2.35, 1.55, 2.0, "Unified\nfusion\nschema\n\nmask + score\n+ metadata", "#ece7f2")
    arrow(6.1, 3.35, 6.65, 3.35)
    box(6.65, 3.35, 1.55, 1.25, "Static\nattention\nfusion", "#e7f0df")
    box(6.65, 1.75, 1.55, 1.25, "Reliability\nestimator\nECE + KS\n+ sharpness", "#f1e4e4")
    arrow(7.42, 3.35, 7.42, 3.0)
    arrow(8.2, 3.95, 8.75, 3.95)
    arrow(8.2, 2.35, 8.75, 3.35)
    box(8.75, 3.05, 1.0, 1.3, "Risk\nscore\n+\nCDA", "#e2e8f0")
    fig.subplots_adjust(left=0.01, right=0.99, top=0.98, bottom=0.02)
    _save(fig, out_dir / "elara_system_architecture.png")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate reliability-gated fusion paper assets")
    parser.add_argument("--input", required=True, type=Path, help="Path to benchmark results JSON")
    parser.add_argument("--figures-dir", required=True, type=Path)
    parser.add_argument("--tables-dir", required=True, type=Path)
    parser.add_argument("--metadata", type=Path, default=None, help="Optional real-domain metadata JSON")
    parser.add_argument("--paired-input", type=Path, default=None, help="Optional naturally paired benchmark results JSON")
    parser.add_argument("--paired-metadata", type=Path, default=None, help="Optional naturally paired benchmark metadata JSON")
    args = parser.parse_args()

    data = _load(args.input)
    metadata = _load(args.metadata) if args.metadata else None
    paired_data = _load(args.paired_input) if args.paired_input else None
    paired_metadata = _load(args.paired_metadata) if args.paired_metadata else None
    args.figures_dir.mkdir(parents=True, exist_ok=True)
    args.tables_dir.mkdir(parents=True, exist_ok=True)

    write_clean_table(data, args.tables_dir)
    write_clean_ci_table(data, args.tables_dir)
    write_missing_table(data, args.tables_dir)
    write_drift_table(data, args.tables_dir)
    write_calibration_table(data, args.tables_dir)
    write_adversarial_table(data, args.tables_dir)
    write_tau_sweep_table(data, args.tables_dir)
    write_component_ablation_table(data, args.tables_dir)
    write_failure_case_table(data, args.tables_dir)
    if metadata:
        write_domain_scorer_table(metadata, args.tables_dir)
        write_benchmark_metadata_table(metadata, args.tables_dir)
    if paired_data:
        write_named_clean_table(paired_data, args.tables_dir, "mvtec3d_clean_results.tex")
    if paired_metadata:
        write_paired_benchmark_metadata_table(paired_metadata, args.tables_dir)

    _set_style()
    plot_clean_benchmark(data, args.figures_dir)
    plot_missing_modality(data, args.figures_dir)
    plot_drift_curves(data, args.figures_dir)
    plot_calibration(data, args.figures_dir)
    plot_cda_impacts(data, args.figures_dir)
    plot_adversarial_delta(data, args.figures_dir)
    plot_failure_cases(data, args.figures_dir)
    plot_system_architecture(args.figures_dir)

    print(f"Wrote figures to {args.figures_dir}")
    print(f"Wrote tables to {args.tables_dir}")


if __name__ == "__main__":
    main()
