"""Generate manuscript tables and figures for the healthcare gap audit."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np


def _load_report(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _fmt(value: object, digits: int = 3) -> str:
    if value is None:
        return "--"
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    if not np.isfinite(number):
        return "--"
    return f"{number:.{digits}f}"


def _latex_text(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def _yes_no(value: object) -> str:
    return "yes" if bool(value) else "no"


def write_gap_closure_table(report: dict[str, Any], output_dir: str | Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "healthcare_gap_closure_results.tex"

    statuses = report["gap_statuses"]
    detection = report.get("incident_detection", {}).get("by_split", {}).get("test", {})
    stress = report.get("reliability_stress", {}).get("test", {})
    schema = report.get("schema_integration", {})
    audit = report.get("deployment_audit", {})
    certificate = audit.get("diagnostic_switching_certificate", {})
    tensor_shape = " x ".join(str(v) for v in schema.get("tensor_shape", [])) or "--"

    rows = [
        (
            "1 Incident detection",
            statuses["1_true_multimodal_incident_detection"],
            f"test ROC-AUC {_fmt(detection.get('multimodal_roc_auc'))} vs best single {_fmt(detection.get('best_single_domain_roc_auc'))}",
        ),
        (
            "2 Reliability stress",
            statuses["2_autonomous_zero_misfire_adaptation"],
            f"natural fire {_fmt(stress.get('natural_fire_rate'))}; collapse fire {_fmt(stress.get('collapse_fire_rate_mean'))}",
        ),
        (
            "3 Schema integration",
            statuses["3_universal_system_integration"],
            f"tensor {tensor_shape}; raw patient ID absent {_yes_no(schema.get('raw_patient_id_absent'))}",
        ),
        (
            "4 Auditability",
            statuses["4_deployable_auditable_ai"],
            f"diagnostic policy loss {_fmt(certificate.get('policy_loss'))} vs static {_fmt(certificate.get('static_loss'))}",
        ),
    ]

    lines = [
        "% Auto-generated by generate_healthcare_gap_assets.py",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"\textbf{Gap} & \textbf{Engineering} & \textbf{Local empirical} & \textbf{Primary evidence} \\",
        r"\midrule",
    ]
    for label, status, evidence in rows:
        lines.append(
            rf"{_latex_text(label)} & {_yes_no(status.get('engineering_closed'))} & "
            rf"{_yes_no(status.get('empirical_closed'))} & {_latex_text(evidence)} \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_gap4_audit_table(report: dict[str, Any], output_dir: str | Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "healthcare_gap4_audit_results.tex"

    audit = report.get("deployment_audit", {})
    temporal = audit.get("temporal_validation", {})
    privacy = audit.get("privacy_license_review", {})
    monitoring = audit.get("monitoring", {})
    analyst = audit.get("analyst_audit_surface", {})
    certificate = audit.get("diagnostic_switching_certificate", {})
    rows = [
        ("Temporal reference", "pass" if temporal.get("temporal_order_valid") else "open"),
        ("Privacy/license review", "pass" if privacy.get("passed") else "open"),
        ("Calibration monitor", f"ready; alert {_yes_no(monitoring.get('calibration_alert'))}"),
        (
            "CDA-style top domain",
            f"{analyst.get('top_domain_by_abs_impact', '--')} ({_fmt((analyst.get('mean_abs_impact_by_domain') or {}).get(analyst.get('top_domain_by_abs_impact')))})",
        ),
        (
            "Diagnostic switch certificate",
            f"{'certified' if certificate.get('certified') else 'open'}; static {_fmt(certificate.get('static_loss'))}, policy {_fmt(certificate.get('policy_loss'))}",
        ),
        ("Scope", "local replay only"),
    ]

    lines = [
        "% Auto-generated by generate_healthcare_gap_assets.py",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"\textbf{Audit item} & \textbf{Result} \\",
        r"\midrule",
    ]
    for label, value in rows:
        lines.append(rf"{_latex_text(label)} & {_latex_text(value)} \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_gap_status_figure(report: dict[str, Any], output_dir: str | Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "healthcare_gap_closure_status.png"
    statuses = report["gap_statuses"]
    labels = ["Gap 1", "Gap 2", "Gap 3", "Gap 4"]
    keys = [
        "1_true_multimodal_incident_detection",
        "2_autonomous_zero_misfire_adaptation",
        "3_universal_system_integration",
        "4_deployable_auditable_ai",
    ]
    engineering = [1.0 if statuses[key]["engineering_closed"] else 0.0 for key in keys]
    empirical = [1.0 if statuses[key]["empirical_closed"] else 0.0 for key in keys]
    x = np.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(6.4, 3.0))
    ax.bar(x - width / 2, engineering, width, label="Engineering", color="#2563eb")
    ax.bar(x + width / 2, empirical, width, label="Local empirical", color="#16a34a")
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_ylim(0.0, 1.15)
    ax.set_yticks([0.0, 1.0])
    ax.set_yticklabels(["open", "closed"])
    ax.set_title("Healthcare Gap Closure Audit")
    ax.legend(loc="upper center", ncols=2, frameon=False)
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)
    return path


def write_stress_figure(report: dict[str, Any], output_dir: str | Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "healthcare_gap2_stress_rates.png"
    stress = report.get("reliability_stress", {}).get("test", {})
    collapse_rates = stress.get("collapse_fire_rate_by_domain") or {}
    labels = ["natural"] + [str(domain) for domain in collapse_rates]
    values = [float(stress.get("natural_fire_rate", 0.0))] + [float(collapse_rates[domain]) for domain in collapse_rates]
    colors = ["#64748b"] + ["#dc2626" for _ in collapse_rates]

    fig, ax = plt.subplots(figsize=(6.4, 3.0))
    ax.bar(np.arange(len(labels)), values, color=colors)
    ax.set_ylim(0.0, 1.1)
    ax.set_ylabel("Gate fire rate")
    ax.set_title("Natural Replay vs Injected Score Collapse")
    ax.set_xticks(np.arange(len(labels)))
    ax.set_xticklabels(labels, rotation=20, ha="right")
    ax.spines[["top", "right"]].set_visible(False)
    for idx, value in enumerate(values):
        ax.text(idx, min(value + 0.03, 1.04), _fmt(value, digits=2), ha="center", va="bottom", fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)
    return path


def generate_assets(report_path: str | Path, tables_dir: str | Path, figures_dir: str | Path) -> list[Path]:
    report = _load_report(report_path)
    return [
        write_gap_closure_table(report, tables_dir),
        write_gap4_audit_table(report, tables_dir),
        write_gap_status_figure(report, figures_dir),
        write_stress_figure(report, figures_dir),
    ]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        default="experiments/fusion/healthcare_gap4_deployment_audit_validation.json",
        help="Healthcare validation JSON produced by validate_healthcare_gap_closure.py.",
    )
    parser.add_argument("--tables-dir", default="docs/research/tables")
    parser.add_argument("--figures-dir", default="docs/research/figures")
    args = parser.parse_args()

    for path in generate_assets(args.report, args.tables_dir, args.figures_dir):
        print(path)


if __name__ == "__main__":
    main()
