"""Phase 1.1 — strip degenerate PR-AUC / ECE / Brier from promoted canonical
MVTec / LOCO / VisA tables and figures.

Per the Phase 1.A canonical label-metric semantics audit
(`docs/research/audit/CANONICAL_LABEL_METRIC_AUDIT.md`), canonical
one-class PR-AUC / ECE / Brier values equal the canonical test-fold's
anomaly prevalence (0.78 for MVTec 3D-AD, 0.63 for MVTec LOCO-AD, 0.56
for VisA) and reflect degenerate constant predictors rather than
discrimination ability. Promoted canonical tables and figures must
therefore show **ROC-AUC only**.

This script runs at the end of `scripts/rebuild_paper.sh` and:

  1. Overwrites the canonical `*_clean_ci_results.tex` files with
     ROC-AUC-only versions + a one-line diagnostic note.
  2. Overwrites the canonical `*_calibration_cda.tex` files to remove
     ECE / Brier rows + diagnostic note.
  3. Regenerates the canonical clean-benchmark bar charts as
     ROC-AUC-only.

Canonical runs (one-class normal-only training):
  - mvtec3d_*  (NOT _supervised_paired_)
  - mvtec3d_patchcore_*  (NOT _supervised_paired_ and NOT _heldout_)
  - mvtec_loco_patchcore_*  (NOT _supervised_paired_)
  - visa_fusion_*  (NOT _supervised_paired_)
  - elara_*  (always shown — ELARA-Bench-LA is not one-class but the
    cleanup is harmless here; we keep PR-AUC visible for ELARA-Bench-LA
    because it is not a canonical one-class run)

Implementation note: this script is idempotent. Running it twice
produces the same output.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


GENERATED_COMMENT = "% Auto-generated by phase1_1_canonical_cleanup.py — Phase 1.1 ROC-AUC-only canonical view."
CANONICAL_NOTE = (
    "% Canonical fusion train/validation folds are normal-only. The Phase 1.A audit "
    "confirmed that PR-AUC, ECE and Brier for constant-like supervised heads reflect "
    "the canonical test-fold's anomaly prevalence rather than useful discrimination "
    "evidence; therefore the promoted canonical view reports ROC-AUC only. See "
    "docs/research/audit/CANONICAL_LABEL_METRIC_AUDIT.md."
)


# Canonical (one-class) results JSONs.
CANONICAL_RUNS = [
    # (results_json_path, table_dir, table_prefix, figure_dir, figure_prefix)
    {
        "json": "experiments/fusion/mvtec3d_patchcore_results.json",
        "prefix": "mvtec3d_patchcore_",
    },
    {
        "json": "experiments/fusion/mvtec_loco_patchcore_results.json",
        "prefix": "mvtec_loco_patchcore_",
    },
    {
        "json": "experiments/fusion/visa_fusion_results.json",
        "prefix": "visa_fusion_",
    },
    {
        "json": "experiments/fusion/mvtec3d_results.json",
        "prefix": "mvtec3d_",
    },
]


CANONICAL_METHOD_ORDER = [
    ("random_forest", "Random forest"),
    ("confidence_weighted_mean", "Conf.-weighted mean"),
    ("tent_score_adapter", "Tent score adapter"),
    ("ttt_pseudo_label_adapter", "TTT pseudo-label"),
    ("eata_score_adapter", "EATA score adapter"),
    ("sar_score_adapter", "SAR score adapter"),
    ("early_fusion_mlp", "Early fusion MLP"),
    ("late_fusion_ensemble", "Late fusion ensemble"),
    ("static_attention", "Static attention"),
    ("craf_attention", "RGA attention"),
    ("rga_boosted_fusion", "RGA+ boosted fusion"),
    ("rga_meta_router", "RGA+ router"),
]


def _fmt_ci(low, high, digits=4):
    if low is None or high is None:
        return "--"
    try:
        return f"[{float(low):.{digits}f}, {float(high):.{digits}f}]"
    except (TypeError, ValueError):
        return "--"


def _fmt(value, digits=4):
    if value is None:
        return "--"
    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return "--"


def _gather_canonical_rows(payload: dict) -> list[tuple[str, str, dict]]:
    cs = payload.get("clean_metric_summary", {})
    rows = []
    for key, label in CANONICAL_METHOD_ORDER:
        m = cs.get(key)
        if not isinstance(m, dict):
            continue
        rows.append((key, label, m))
    return rows


def emit_canonical_roc_ci_table(rows, out_path: Path) -> None:
    lines = [
        GENERATED_COMMENT,
        CANONICAL_NOTE,
        r"\begin{tabular}{lcc}",
        r"\toprule",
        r"\textbf{Method} & \textbf{ROC-AUC mean} & \textbf{ROC-AUC 95\% CI} \\",
        r"\midrule",
    ]
    for key, label, m in rows:
        roc = m.get("roc_auc")
        if isinstance(roc, dict):
            mean = roc.get("mean")
            ci_low = roc.get("ci_low") or roc.get("ci_low_95") or roc.get("ci95_low")
            ci_high = roc.get("ci_high") or roc.get("ci_high_95") or roc.get("ci95_high")
        else:
            mean = roc
            ci_low = m.get("roc_auc_ci_low")
            ci_high = m.get("roc_auc_ci_high")
        lines.append(rf"{label} & {_fmt(mean, 4)} & {_fmt_ci(ci_low, ci_high)} \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))


def emit_canonical_calibration_diagnostic(out_path: Path) -> None:
    """Replace canonical ECE/Brier calibration table with a one-line diagnostic note."""
    lines = [
        GENERATED_COMMENT,
        CANONICAL_NOTE,
        r"\begin{tabular}{l}",
        r"\toprule",
        r"\textbf{Diagnostic} \\",
        r"\midrule",
        r"Canonical one-class supervised heads produce constant-like predictions; ECE \\",
        r"and Brier values therefore equal the canonical test-fold anomaly prevalence \\",
        r"(0.78 for MVTec 3D-AD, 0.63 for MVTec LOCO-AD, 0.56 for VisA) and are not \\",
        r"reported as quality measures. See CANONICAL\_LABEL\_METRIC\_AUDIT.md. \\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))


def plot_canonical_roc_only(rows, out_path: Path) -> None:
    labels = [label for _, label, _ in rows]
    rocs = []
    for _, _, m in rows:
        roc = m.get("roc_auc")
        if isinstance(roc, dict):
            rocs.append(float(roc.get("mean") or 0.5))
        elif isinstance(roc, (int, float)):
            rocs.append(float(roc))
        else:
            rocs.append(0.5)

    fig, ax = plt.subplots(figsize=(8.2, 3.4))
    x = np.arange(len(labels))
    ax.bar(x, rocs, 0.55, color="#2f6f73", label="ROC-AUC")
    ax.axhline(0.5, color="#888", linewidth=0.8, linestyle="--", label="chance")
    ax.set_ylim(0.0, 1.0)
    ax.set_ylabel("ROC-AUC")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=25, ha="right")
    ax.legend(frameon=False, ncol=2)
    ax.grid(axis="y", alpha=0.22)
    ax.set_title("Protocol-diagnostic ROC-AUC only "
                 "(canonical one-class; not a supervised-fusion leaderboard)",
                 fontsize=9)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.patch.set_facecolor("white")
    fig.savefig(out_path, facecolor="white", edgecolor="none")
    plt.close(fig)


def process_canonical_run(run: dict, repo_root: Path) -> list[str]:
    """Process one canonical run; return list of output paths touched."""
    json_path = repo_root / run["json"]
    prefix = run["prefix"]
    touched: list[str] = []
    if not json_path.exists():
        return touched
    payload = json.loads(json_path.read_text())
    rows = _gather_canonical_rows(payload)
    if not rows:
        return touched

    tables_dir = repo_root / "docs/research/tables"
    figs_dir = repo_root / "docs/research/figures"

    # Table 1: clean CI -> ROC-only
    for suffix in ("clean_ci_results", "clean_results"):
        t = tables_dir / f"{prefix}{suffix}.tex"
        if t.exists():
            emit_canonical_roc_ci_table(rows, t)
            touched.append(str(t))

    # Table 2: calibration_cda -> diagnostic-only
    cal_t = tables_dir / f"{prefix}calibration_cda.tex"
    if cal_t.exists():
        emit_canonical_calibration_diagnostic(cal_t)
        touched.append(str(cal_t))

    # Figure: clean_benchmark -> ROC-only
    fig_p = figs_dir / f"{prefix}clean_benchmark.png"
    if fig_p.exists():
        plot_canonical_roc_only(rows, fig_p)
        touched.append(str(fig_p))

    return touched


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    args = parser.parse_args()
    touched_all: list[str] = []
    for run in CANONICAL_RUNS:
        touched_all.extend(process_canonical_run(run, args.repo_root))
    if touched_all:
        print(f"Phase 1.1 canonical cleanup: rewrote {len(touched_all)} files")
        for t in touched_all:
            print(f"  {t}")
    else:
        print("Phase 1.1 canonical cleanup: no canonical files found.")


if __name__ == "__main__":
    main()
