"""Validate T2 mixture-confounding on REAL Eyecandies category scores.

Closes the long-standing T2 deferral (DEFERRED_PENDING_NATURAL_CATEGORY_METADATA):
Eyecandies has 10 natural categories with their own score distributions.

Under NO per-category drift (reference and test drawn from the same
per-category distributions), we show the GLOBAL KS gate false-fires on a
mixture-skewed cohort while the CATEGORY-AWARE KS gate does not -- the exact
T2 prediction, now on a real benchmark instead of synthetic mixtures.

Writes:
    experiments/fusion/t2_eyecandies_category_ks.json
    docs/research/tables/t2_eyecandies_category_ks.tex
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from elara.theory.t2_mixture_entropy import validate_against_cohorts  # noqa: E402


def emit_tex(res, domain: str) -> str:
    out = [
        "% Auto-generated by validate_t2_eyecandies_categories.py",
        r"\begin{tabular}{lc}",
        r"\toprule",
        r"\textbf{Quantity} & \textbf{Value} \\",
        r"\midrule",
        rf"Categories $k$ & {res.n_categories} \\",
        rf"Mixture entropy (uniform ref) & {res.mixture_entropy_uniform:.3f} nats \\",
        rf"TV(uniform ref, skewed test) & {res.tv_uniform_vs_skewed:.3f} \\",
        rf"Global KS statistic & {res.global_ks_statistic:.4f} \\",
        rf"Global KS $p$-value & {res.global_ks_pvalue:.2e} \\",
        rf"Global KS inflation lower bound & {res.global_ks_inflation_lower_bound:.4f} \\",
        rf"Category-aware max KS statistic & {res.category_aware_max_statistic:.4f} \\",
        rf"Category-aware min $p$-value & {res.category_aware_min_pvalue:.3f} \\",
        rf"Category-aware fire count & {res.category_aware_fire_count} / {res.n_categories} \\",
        r"\midrule",
        rf"\textbf{{Global gate fires?}} & \textbf{{{'yes' if res.global_fires else 'no'}}} \\",
        rf"\textbf{{Category-aware gate fires?}} & \textbf{{{'yes' if res.category_aware_fires else 'no'}}} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"",
        rf"% Domain: {domain}. Under NO per-category drift, the global KS gate",
        r"% false-fires on the mixture-skewed cohort (p < alpha) while the",
        r"% category-aware gate stays null -- the T2 prediction on real data.",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path,
                        default=ROOT / "experiments/fusion/mvtec3d_patchcore_supervised_paired_inputs.csv")
    parser.add_argument("--domain", default="rgb")
    parser.add_argument("--split", default="validation")
    parser.add_argument("--alpha", type=float, default=0.05)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out-json", type=Path,
                        default=ROOT / "experiments/fusion/t2_category_ks_validation.json")
    parser.add_argument("--out-tex", type=Path,
                        default=ROOT / "docs/research/tables/t2_category_ks.tex")
    args = parser.parse_args()

    df = pd.read_csv(args.input)
    # Accept either the 'fusion_split' or 'split' column naming.
    split_col = "fusion_split" if "fusion_split" in df.columns else "split"
    split_vals = set(df[split_col].astype(str).unique())
    want_split = args.split
    if want_split not in split_vals:
        # tolerate validation/val aliasing
        want_split = "val" if (args.split == "validation" and "val" in split_vals) else want_split
    sub = df[df[split_col].astype(str) == want_split]
    if "domain" in df.columns:
        doms = sub["domain"].unique().tolist()
        dom = args.domain if args.domain in doms else doms[0]
        sub = sub[sub["domain"] == dom]
        args.domain = dom
    if sub.empty:
        print(f"-- no rows for split={want_split} domain={args.domain}")
        return 1
    scores_by_cat = {
        cat: g["score"].to_numpy(dtype=float)
        for cat, g in sub.groupby("category")
    }
    res = validate_against_cohorts(scores_by_cat, alpha=args.alpha, seed=args.seed)

    payload = {
        "domain": args.domain,
        "split": args.split,
        "alpha": args.alpha,
        "n_categories": res.n_categories,
        "mixture_entropy_uniform": res.mixture_entropy_uniform,
        "tv_uniform_vs_skewed": res.tv_uniform_vs_skewed,
        "global_ks_statistic": res.global_ks_statistic,
        "global_ks_pvalue": res.global_ks_pvalue,
        "global_ks_inflation_lower_bound": res.global_ks_inflation_lower_bound,
        "category_aware_max_statistic": res.category_aware_max_statistic,
        "category_aware_min_pvalue": res.category_aware_min_pvalue,
        "category_aware_fire_count": res.category_aware_fire_count,
        "global_fires": res.global_fires,
        "category_aware_fires": res.category_aware_fires,
        "t2_confirmed": bool(res.global_fires and not res.category_aware_fires),
        "per_category": res.per_category,
    }
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(payload, indent=2))
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(emit_tex(res, args.domain))

    print(f"T2 category-KS validation [{args.input.name}] (domain={args.domain}, split={want_split}):")
    print(f"  k={res.n_categories} categories, mixture entropy={res.mixture_entropy_uniform:.3f} nats")
    print(f"  TV(uniform, skewed) = {res.tv_uniform_vs_skewed:.3f}")
    print(f"  GLOBAL KS:         stat={res.global_ks_statistic:.4f}  p={res.global_ks_pvalue:.2e}  "
          f"fires={res.global_fires}")
    print(f"  CATEGORY-AWARE KS: max_stat={res.category_aware_max_statistic:.4f}  "
          f"min_p={res.category_aware_min_pvalue:.3f}  fires={res.category_aware_fires} "
          f"({res.category_aware_fire_count}/{res.n_categories})")
    print(f"  T2 confirmed (global fires, cat-aware does not): {payload['t2_confirmed']}")
    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
