"""Validate the GDR minimax theorem on a synthetic two-regime operator family.

Writes:
    experiments/fusion/gdr_minimax_validation.json
    docs/research/tables/gdr_minimax.tex
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from elara.theory.gdr_minimax import validate_minimax  # noqa: E402


def emit_tex(res) -> str:
    return "\n".join([
        "% Auto-generated by validate_gdr_minimax.py",
        r"\begin{tabular}{lc}",
        r"\toprule",
        r"\textbf{Policy} & \textbf{Worst-case regret} \\",
        r"\midrule",
        rf"always\_switch & {res.always_max_regret:.4f} \\",
        rf"never\_switch & {res.never_max_regret:.4f} \\",
        rf"\textbf{{GDR}} ($\theta^*={res.best_theta:.2f}$) & "
        rf"\textbf{{{res.gdr_max_regret:.4f}}} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"",
        rf"% b_C={res.b_C}, c_H={res.c_H}, separation eps at theta*={res.eps_at_best_theta:.3f}.",
        rf"% GDR strictly minimaxes the fixed policies: {res.gdr_is_minimax}.",
        r"% Worst-case regret is over the adversary's regime mixture pi in [0,1].",
    ])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--b-C", type=float, default=0.10)
    parser.add_argument("--c-H", type=float, default=0.10)
    parser.add_argument("--out-json", type=Path,
                        default=ROOT / "experiments/fusion/gdr_minimax_validation.json")
    parser.add_argument("--out-tex", type=Path,
                        default=ROOT / "docs/research/tables/gdr_minimax.tex")
    args = parser.parse_args()

    res = validate_minimax(b_C=args.b_C, c_H=args.c_H)
    payload = {
        "b_C": res.b_C, "c_H": res.c_H,
        "best_theta": res.best_theta,
        "eps_at_best_theta": res.eps_at_best_theta,
        "gdr_max_regret": res.gdr_max_regret,
        "always_max_regret": res.always_max_regret,
        "never_max_regret": res.never_max_regret,
        "gdr_is_minimax": res.gdr_is_minimax,
    }
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(payload, indent=2))
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(emit_tex(res))

    print("GDR minimax validation:")
    print(f"  always_switch worst-case regret: {res.always_max_regret:.4f}")
    print(f"  never_switch  worst-case regret: {res.never_max_regret:.4f}")
    print(f"  GDR(theta*={res.best_theta:.2f}) worst-case regret: {res.gdr_max_regret:.4f}")
    print(f"  GDR strictly minimaxes fixed policies: {res.gdr_is_minimax}")
    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_tex}")
    return 0 if res.gdr_is_minimax else 1


if __name__ == "__main__":
    raise SystemExit(main())
