"""Empirically verify T1 quality-blind fusion impossibility on the
constructive adversary.

Writes:
    experiments/fusion/t1_impossibility_validation.json
    docs/research/tables/t1_impossibility.tex
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from elara.theory.t1_impossibility import validate_t1  # noqa: E402


def emit_tex(payload: dict) -> str:
    rows = payload["rows"]
    out = [
        "% Auto-generated by validate_t1_impossibility.py",
        r"\begin{tabular}{lccccccc}",
        r"\toprule",
        r"\textbf{Regime} & $D$ & $p$ & \textbf{Rule} & "
        r"\textbf{Risk gap} & \textbf{Bound} & \textbf{Ratio} & \textbf{OK?} \\",
        r"\midrule",
    ]
    for r in rows:
        ok = r"\textbf{\checkmark}" if r["bound_satisfied"] else r"\textbf{\times}"
        ratio = (r["empirical_gap"] / r["lower_bound"]) if r["lower_bound"] > 0 else float("inf")
        regime_short = {"sparse_T1a": "sparse", "sparse_T1a_informational": "sparse*",
                        "coherent_T1b": "coherent"}.get(r["regime"], r["regime"])
        out.append(
            rf"{regime_short} & {r['D']} & {r['p_corrupt']:.2f} & {r['rule']} & "
            rf"{r['empirical_gap']:.4f} & {r['lower_bound']:.4f} & "
            rf"{ratio:.2f} & {ok} \\"
        )
    out += [
        r"\bottomrule",
        r"\end{tabular}",
        r"",
        r"% T1a (sparse, linear rules only): bound = p / (3 D^2)",
        r"% T1b (coherent, ALL rules incl. median): bound = p / 12",
        r"% Rows marked sparse* are informational: median escapes T1a (rank-based",
        r"% robustness), which is consistent with T1a's restriction to linear rules.",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n", type=int, default=20_000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--out-json", type=Path,
                        default=ROOT / "experiments/fusion/t1_impossibility_validation.json")
    parser.add_argument("--out-tex", type=Path,
                        default=ROOT / "docs/research/tables/t1_impossibility.tex")
    args = parser.parse_args()

    payload = validate_t1(n=args.n, seed=args.seed)
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(payload, indent=2))
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(emit_tex(payload))

    a_ok = payload["t1a_sparse_linear_satisfied"]
    b_ok = payload["t1b_coherent_all_rules_satisfied"]
    print(f"T1a (sparse, linear rules): {a_ok}")
    print(f"T1b (coherent, all rules):  {b_ok}")
    print(f"  rows: {len(payload['rows'])}  (D x p_corrupt x rule x regime grid)")
    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_tex}")
    return 0 if (a_ok and b_ok) else 1


if __name__ == "__main__":
    raise SystemExit(main())
