"""Validate the T6 sequential-detection (CUSUM-style ARL/AED) theorem against
the B-MECH-4 window-size sweep.

Writes:
    experiments/fusion/t6_sequential_detection_validation.json
    docs/research/tables/t6_sequential_detection.tex
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from elara.theory.t6_sequential_detection import validate_against_sweep  # noqa: E402


def _aggregate(path: Path) -> list[dict]:
    buckets: dict[int, list[dict]] = defaultdict(list)
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            buckets[int(row["window_size"])].append(row)
    out = []
    for w in sorted(buckets):
        rows = buckets[w]
        out.append({
            "window_size": w,
            "false_activation_rate": sum(float(r["false_activation_rate"]) for r in rows) / len(rows),
            "detection_power": sum(float(r["true_degradation_detection_power"]) for r in rows) / len(rows),
        })
    return out


def emit_tex(res, target_arl: float) -> str:
    out = [
        "% Auto-generated by validate_t6_sequential_detection.py",
        r"\begin{tabular}{ccccc}",
        r"\toprule",
        r"$W$ & $\mathrm{ARL}_0(W)$ at $h_0$ & "
        r"\textbf{Power (obs)} & \textbf{Power (theory)} & \textbf{AED (windows)} \\",
        r"\midrule",
    ]
    for i, w in enumerate(res.windows):
        arl = res.arl_at_each_window[i]
        arl_s = r"$\infty$" if not math.isfinite(arl) else f"{arl:.0f}"
        pi_pred = res.predicted_detection_power[i]
        aed = (1.0 / pi_pred) if pi_pred > 0 else float("inf")
        aed_s = r"$\infty$" if not math.isfinite(aed) else f"{aed:.2f}"
        out.append(
            rf"{w} & {arl_s} & "
            rf"{res.observed_detection_power[i]:.3f} & {pi_pred:.3f} & {aed_s} \\"
        )
    out += [
        r"\bottomrule",
        r"\end{tabular}",
        r"",
        rf"% Fixed-threshold fit: h0 = {res.fitted_fixed_threshold:.4f}, drift delta = {res.fitted_drift:.3f}.",
        rf"% Power monotone increasing in W: {res.power_monotone_increasing}; "
        rf"ARL_0 monotone increasing in W: {res.arl_monotone_increasing}.",
        rf"% Mean abs error (theory vs observed power): {res.mean_abs_power_error:.3f}.",
        r"% At fixed h0 the null KS concentrates as W grows, so BOTH the false-alarm",
        r"% spacing ARL_0(W)=1/(2 exp(-2 W h0^2)) AND detection power Phi((delta-h0)sqrt(2W))",
        r"% increase with W -- the sequential-detection content the sweep exercised (T6.1-T6.2).",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path,
                        default=ROOT / "experiments/phase2/mechanism/ks_window_size_power.csv")
    parser.add_argument("--target-arl", type=float, default=1600.0)
    parser.add_argument("--out-json", type=Path,
                        default=ROOT / "experiments/fusion/t6_sequential_detection_validation.json")
    parser.add_argument("--out-tex", type=Path,
                        default=ROOT / "docs/research/tables/t6_sequential_detection.tex")
    args = parser.parse_args()

    if not args.input.exists():
        print(f"-- missing input: {args.input}")
        return 1
    rows = _aggregate(args.input)
    res = validate_against_sweep(rows, target_arl=args.target_arl)

    payload = {
        "fitted_fixed_threshold": res.fitted_fixed_threshold,
        "fitted_drift": res.fitted_drift,
        "power_monotone_increasing": res.power_monotone_increasing,
        "arl_monotone_increasing": res.arl_monotone_increasing,
        "mean_abs_power_error": res.mean_abs_power_error,
        "windows": res.windows,
        "observed_false_activation": res.observed_false_activation,
        "observed_detection_power": res.observed_detection_power,
        "predicted_detection_power": res.predicted_detection_power,
        "arl_at_each_window": res.arl_at_each_window,
    }
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(payload, indent=2))
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(emit_tex(res, args.target_arl))

    print("T6 sequential-detection (ARL/AED) validation:")
    print(f"  fixed-threshold fit: h0 = {res.fitted_fixed_threshold:.4f}  drift delta = {res.fitted_drift:.3f}")
    print(f"  power monotone increasing in W: {res.power_monotone_increasing}")
    print(f"  ARL_0 monotone increasing in W: {res.arl_monotone_increasing}")
    print(f"  mean abs error (theory vs observed power): {res.mean_abs_power_error:.3f}")
    for i, w in enumerate(res.windows):
        arl = res.arl_at_each_window[i]
        arl_s = "inf" if not math.isfinite(arl) else f"{arl:.0f}"
        print(f"    W={w:>4d}  ARL_0={arl_s:>8s}  "
              f"power_obs={res.observed_detection_power[i]:.3f}  "
              f"power_theory={res.predicted_detection_power[i]:.3f}")
    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
