"""Validate T3 closed-form mean-gate miss probability against the
empirical k-of-D corruption sweep on ELARA-Bench-LA.

Writes:
    experiments/fusion/t3_mean_gate_miss_validation.json
    docs/research/tables/t3_mean_gate_miss.tex
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from elara.theory.t3_mean_gate_miss import validate_against_empirical  # noqa: E402


def emit_tex(payload: dict) -> str:
    preds = payload["predictions"]
    out = [
        "% Auto-generated by validate_t3_mean_gate_miss.py",
        r"\begin{tabular}{ccccccc}",
        r"\toprule",
        r"$k$ & $D$ & $\tau$ & "
        r"\textbf{$P(\mathrm{miss})$ det.} & \textbf{$P(\mathrm{miss})$ calib.} & "
        r"\textbf{Empirical} & \textbf{Abs. err. (calib.)} \\",
        r"\midrule",
    ]
    seen = set()
    for p in preds:
        key = (p["k"], p.get("D", payload["D"]), payload["tau"])
        if key in seen:
            continue
        seen.add(key)
        emp = p.get("empirical_miss_probability")
        err = p.get("abs_error_calibrated")
        out.append(
            rf"{p['k']} & {payload['D']} & {payload['tau']:.2f} & "
            rf"{p['predicted_miss_deterministic']:.3f} & "
            rf"{p['predicted_miss_calibrated']:.3f} & "
            rf"{(emp if emp is not None else float('nan')):.3f} & "
            rf"{(err if err is not None else float('nan')):.3f} \\"
        )
    det = payload.get("deterministic_miss_threshold", float("nan"))
    out += [
        r"\bottomrule",
        r"\end{tabular}",
        r"",
        rf"% Deterministic miss boundary: k* = {det:.2f}. The mean gate fails to fire",
        rf"% for k <= floor(k*) (deterministic prediction). The calibrated prediction",
        rf"% uses per-sample reliability std ~0.08 to smooth the step transition.",
        rf"% Estimated mu_h={payload['mu_h']:.3f}, mu_c={payload['mu_c']:.3f}",
        rf"% from k=0 and k=D rows of the empirical k-of-D sweep.",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path,
                        default=ROOT / "experiments/fusion/craf_real_k_domain_results.json")
    parser.add_argument("--out-json", type=Path,
                        default=ROOT / "experiments/fusion/t3_mean_gate_miss_validation.json")
    parser.add_argument("--out-tex", type=Path,
                        default=ROOT / "docs/research/tables/t3_mean_gate_miss.tex")
    parser.add_argument("--tau", type=float, default=0.66)
    parser.add_argument("--D", type=int, default=4)
    parser.add_argument("--gate", default="mean")
    parser.add_argument("--attack", default="none",
                        help="Attack condition to filter on (none = clean k-of-D)")
    args = parser.parse_args()

    payload_raw = json.loads(args.input.read_text(encoding="utf-8"))
    table10 = payload_raw.get("table_10_k_domain_corruption") or []
    if not table10:
        print(f"-- no table_10_k_domain_corruption in {args.input}")
        return 1
    payload = validate_against_empirical(
        table10,
        tau=args.tau, D=args.D,
        gate_mode_filter=args.gate,
        attack_filter=args.attack,
    )
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(payload, indent=2))
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(emit_tex(payload))

    print(f"T3 validation against {args.gate}-gate {args.attack}-attack sweep:")
    print(f"  estimated mu_h={payload['mu_h']:.3f}, mu_c={payload['mu_c']:.3f}")
    print(f"  deterministic miss boundary k* = {payload['deterministic_miss_threshold']:.2f}")
    mae_det = payload.get("mean_abs_error_deterministic")
    mae_cal = payload.get("mean_abs_error_calibrated")
    if mae_det is not None:
        print(f"  mean abs error vs empirical: det={mae_det:.3f}  calibrated={mae_cal:.3f}")
    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
