"""Validate T9 (clean-transfer reliability-gate impossibility) two ways:

  1. CONSTRUCTIVE (synthetic): both clean-transfer regimes (redundant-mean-optimal
     and complementary-ceiling) confirm the headroom decomposition, the
     homoscedastic closure A(CW)=A*, and the Gate-E-unpassable certificate.
  2. REAL DATA: the two opened external transfer benchmarks (3D-ADAM RGB+depth,
     MulSen RGB+infrared). For each, on the CLEAN test split, computes A(CW), a
     cross-fitted flexible oracle estimate of the Neyman-Pearson ceiling A*, the
     recoverable optimality gap eps_subopt = A_oracle - A_CW, the minimum
     detectable effect, and the impossibility certificate. This is the formal
     statement of "no fusion rule beats CW on clean transfer": eps_subopt < MDE,
     so even an unconstrained oracle cannot be certified above CW -- the
     reliability gate provably cannot, and Gate E is closed by proof.

Writes:
    experiments/fusion/t9_clean_transfer_ceiling_validation.json
    docs/research/tables/t9_clean_transfer_ceiling.tex
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from elara.theory.t9_clean_transfer_ceiling import (  # noqa: E402
    auc_empirical,
    gate_e_unpassable_certificate,
    validate_t9,
)


def _cross_fitted_oracle(X: np.ndarray, y: np.ndarray, seed: int = 7) -> tuple[float, np.ndarray]:
    """Out-of-fold flexible oracle: gradient-boosted posterior on the joint
    feature vector (both modality scores + confidences). Over-generous estimate
    of A* -- it sees labels and the full joint distribution; any reliability gate
    sees strictly less. Returns (oof AUROC, oof scores)."""
    from sklearn.ensemble import HistGradientBoostingClassifier
    from sklearn.model_selection import StratifiedKFold

    oof = np.zeros(len(y), dtype=float)
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    for tr, te in skf.split(X, y):
        clf = HistGradientBoostingClassifier(max_depth=3, max_iter=300,
                                             learning_rate=0.06, random_state=seed)
        clf.fit(X[tr], y[tr])
        oof[te] = clf.predict_proba(X[te])[:, 1]
    return auc_empirical(oof, y), oof


def real_data_arm(csv_path: Path, label: str, seed: int = 7) -> dict | None:
    """Compute the T9 certificate on a real opened transfer benchmark."""
    import pandas as pd

    if not csv_path.exists():
        return None
    df = pd.read_csv(csv_path)
    test = df[df["split"] == "test"].copy()
    if test.empty:
        return None
    domains = sorted(test["domain"].dropna().unique().tolist())
    domains = [d for d in domains if d != "domain"]
    if len(domains) < 2:
        return None
    d0, d1 = domains[0], domains[1]

    # pivot by pairing_key -> (score_d0, conf_d0, score_d1, conf_d1, label)
    piv = test.pivot_table(index="pairing_key", columns="domain",
                           values=["score", "confidence"], aggfunc="first")
    piv.columns = [f"{a}__{b}" for a, b in piv.columns]
    piv["label"] = test.groupby("pairing_key")["label"].first()
    piv = piv.dropna()
    y = piv["label"].to_numpy().astype(int)
    s0 = piv[f"score__{d0}"].to_numpy(float)
    s1 = piv[f"score__{d1}"].to_numpy(float)
    c0 = piv[f"confidence__{d0}"].to_numpy(float)
    c1 = piv[f"confidence__{d1}"].to_numpy(float)

    # confidence-weighted mean (falls back to simple mean where confidences vanish)
    wsum = c0 + c1
    cw = np.where(wsum > 1e-9, (c0 * s0 + c1 * s1) / np.maximum(wsum, 1e-9),
                  0.5 * (s0 + s1))
    a_cw = auc_empirical(cw, y)
    a_s0 = auc_empirical(s0, y)
    a_s1 = auc_empirical(s1, y)

    # oracle on the full joint feature vector
    X = np.column_stack([s0, s1, c0, c1])
    a_oracle, oof = _cross_fitted_oracle(X, y, seed=seed)

    # empirical correlation between CW and oracle rankings (for the MDE SE)
    rho = float(np.corrcoef(cw, oof)[0, 1]) if np.std(oof) > 0 else 0.9
    rho = max(min(rho, 0.999), 0.0)

    n_pos = int((y == 1).sum()); n_neg = int((y == 0).sum())
    cert = gate_e_unpassable_certificate(a_cw, a_oracle, n_pos, n_neg, rho=rho)
    complementary = (a_cw > a_s0 + 1e-6) and (a_cw > a_s1 + 1e-6)
    return {
        "dataset": label,
        "csv": str(csv_path.relative_to(ROOT)) if str(csv_path).startswith(str(ROOT)) else str(csv_path),
        "domains": [d0, d1],
        "n_pairs": int(len(y)), "n_pos": n_pos, "n_neg": n_neg,
        "A_single_%s" % d0: a_s0,
        "A_single_%s" % d1: a_s1,
        "A_cw": a_cw,
        "A_oracle_estimate_of_A_star": a_oracle,
        "modalities_complementary_on_clean": bool(complementary),
        "rho_cw_oracle": rho,
        "certificate": cert,
    }


def emit_tex(payload: dict) -> str:
    out = [
        "% Auto-generated by validate_t9_clean_transfer_ceiling.py",
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r"\textbf{Setting} & $A(\mathrm{CW})$ & $\hat{A}^{*}$ (oracle) & "
        r"$\varepsilon_{\mathrm{subopt}}$ & MDE & \textbf{Gate~E} & $n$ \\",
        r"\midrule",
    ]
    for reg in payload.get("synthetic", {}).get("regimes", []):
        c = reg["certificate"]
        verdict = r"\textbf{unpassable}" if c["gate_e_unpassable"] else "open"
        out.append(
            rf"{reg['regime'].replace('_',' ')} & {reg['A_cw_empirical']:.4f} & "
            rf"{reg['A_oracle_empirical']:.4f} & {c['eps_subopt_recoverable']:.5f} & "
            rf"{c['min_detectable_effect']:.5f} & {verdict} & "
            rf"{c['n_pos']+c['n_neg']} \\"
        )
    out.append(r"\midrule")
    for r in payload.get("real_data", []):
        if r is None:
            continue
        c = r["certificate"]
        verdict = r"\textbf{unpassable}" if c["gate_e_unpassable"] else "open"
        out.append(
            rf"{r['dataset']} (clean) & {r['A_cw']:.4f} & {r['A_oracle_estimate_of_A_star']:.4f} & "
            rf"{c['eps_subopt_recoverable']:.5f} & {c['min_detectable_effect']:.5f} & "
            rf"{verdict} & {r['n_pairs']} \\"
        )
    out += [
        r"\bottomrule",
        r"\end{tabular}",
        r"",
        r"% Delta*(G) <= eps_subopt = A* - A(CW) for EVERY fusion class G (Neyman-Pearson ceiling).",
        r"% Gate E is unpassable (closed by proof) when eps_subopt < MDE: even an",
        r"% unconstrained oracle cannot be certified above CW, so the reliability gate cannot.",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--out-json", type=Path,
                        default=ROOT / "experiments/fusion/t9_clean_transfer_ceiling_validation.json")
    parser.add_argument("--out-tex", type=Path,
                        default=ROOT / "docs/research/tables/t9_clean_transfer_ceiling.tex")
    args = parser.parse_args()

    synthetic = validate_t9(seed=args.seed)
    real = [
        # v3 strong patch-PatchCore detector (A_cw=0.9349); the older
        # *_sealed_inputs.csv holds the near-chance pooled-bank detector.
        real_data_arm(ROOT / "experiments/fusion/m2_external_3d_adam_v3_inputs.csv",
                      "3D-ADAM RGB+depth", seed=args.seed),
        real_data_arm(ROOT / "experiments/fusion/m2_external_mulsen_percat_inputs.csv",
                      "MulSen RGB+infrared", seed=args.seed),
    ]
    real_present = [r for r in real if r is not None]
    real_all_unpassable = all(r["certificate"]["gate_e_unpassable"] for r in real_present) if real_present else None

    payload = {
        "theorem": "T9 clean-transfer reliability-gate impossibility",
        "synthetic": synthetic,
        "real_data": real,
        "real_data_gate_e_unpassable_all": real_all_unpassable,
        "all_ok": bool(synthetic["all_ok"] and (real_all_unpassable in (True, None))),
    }
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(payload, indent=2))
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(emit_tex(payload))

    print("=== T9 clean-transfer impossibility ===")
    print(f"  synthetic all_ok: {synthetic['all_ok']}")
    for r in real_present:
        c = r["certificate"]
        print(f"  {r['dataset']:>22}: A_cw={r['A_cw']:.4f} A_oracle={r['A_oracle_estimate_of_A_star']:.4f} "
              f"eps_subopt={c['eps_subopt_recoverable']:.5f} MDE={c['min_detectable_effect']:.5f} "
              f"complementary={r['modalities_complementary_on_clean']} "
              f"GateE_unpassable={c['gate_e_unpassable']}")
    print(f"  real-data Gate E unpassable (all): {real_all_unpassable}")
    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_tex}")
    return 0 if payload["all_ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
