"""T4 — finite-sample risk-dominance sample complexity.

Lifts T4 from a point-estimate indifference prevalence (pi_star) to a
finite-sample statement:

    "With probability 1 - delta, the gated policy risk-dominates static at
     deployment prevalence pi, provided the fired-subset benefit was
     estimated from at least n* = C^2 ln(2/delta) / (2 M0^2) samples."

Reads the locked B-CERT-1 risk-dominance terms (q0, q1, Delta_0, Delta_1,
n) from experiments/phase2/certification/risk_dominance_terms_v2.csv and
reports, per scenario and per deployment prevalence:
  - the point margin M0
  - the margin LCB at 95% confidence (Hoeffding worst-case on Delta_0,Delta_1)
  - whether dominance is certified at finite n
  - the minimum n needed to certify dominance at that prevalence

Writes:
    experiments/fusion/t4_risk_dominance_sample_complexity.json
    docs/research/tables/t4_risk_dominance_sample_complexity.tex
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from elara.certification.risk_dominance import (  # noqa: E402
    min_n_for_dominance,
    risk_dominance_margin_lcb,
)

PI_GRID = (0.05, 0.1, 0.25, 0.5)


def emit_tex(rows: list[dict]) -> str:
    out = [
        "% Auto-generated by validate_t4_risk_dominance_sample_complexity.py",
        r"\begin{tabular}{llccccc}",
        r"\toprule",
        r"\textbf{Scenario} & $\pi$ & \textbf{Margin} & \textbf{Margin LCB} & "
        r"\textbf{$n$ used} & \textbf{$n^*$ needed} & \textbf{Dominates?} \\",
        r"\midrule",
    ]
    for r in rows:
        scen = str(r["scenario_id"]).replace("_", r"\_")
        nstar = r["min_n"]
        nstar_s = r"$\infty$" if not math.isfinite(nstar) else f"{int(nstar)}"
        dom = r"\textbf{yes}" if r["dominates_finite_sample"] else "no"
        out.append(
            rf"{scen} & {r['pi']:.2f} & {r['margin_point']:+.4f} & "
            rf"{r['margin_lcb']:+.4f} & {r['n_used']} & {nstar_s} & {dom} \\"
        )
    out += [
        r"\bottomrule",
        r"\end{tabular}",
        r"",
        r"% Margin LCB: Hoeffding worst-case on Delta_0, Delta_1 at 95% confidence,",
        r"% range R=2. n* = C^2 ln(2/delta) / (2 M0^2) is the min fired-sample count",
        r"% to certify dominance at prevalence pi (infinite when point margin <= 0).",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path,
                        default=ROOT / "experiments/phase2/certification/risk_dominance_terms_v2.csv")
    parser.add_argument("--confidence-delta", type=float, default=0.05)
    parser.add_argument("--out-json", type=Path,
                        default=ROOT / "experiments/fusion/t4_risk_dominance_sample_complexity.json")
    parser.add_argument("--out-tex", type=Path,
                        default=ROOT / "docs/research/tables/t4_risk_dominance_sample_complexity.tex")
    args = parser.parse_args()

    if not args.input.exists():
        print(f"-- missing input: {args.input}")
        return 1
    df = pd.read_csv(args.input)

    rows = []
    for _, t in df.iterrows():
        q0 = float(t["q0_clean_fire_rate"])
        q1 = float(t["q1_degraded_fire_rate"])
        d0 = float(t["delta_0_clean_cost"])
        d1 = float(t["delta_1_degraded_benefit"])
        n_clean = int(t["n_clean_samples"])
        n_deg = int(t["n_degraded_samples"])
        # fired-sample counts (q * n); guard against zero
        n_clean_fired = max(int(round(q0 * n_clean)), 1)
        n_deg_fired = max(int(round(q1 * n_deg)), 1)
        for pi in PI_GRID:
            lcb = risk_dominance_margin_lcb(
                pi=pi, q0=q0, q1=q1, delta_0=d0, delta_1=d1,
                n_clean_fired=n_clean_fired, n_degraded_fired=n_deg_fired,
                confidence_delta=args.confidence_delta,
            )
            mn = min_n_for_dominance(
                pi=pi, q0=q0, q1=q1, delta_0=d0, delta_1=d1,
                confidence_delta=args.confidence_delta,
            )
            rows.append({
                "gate_id": t["gate_id"],
                "scenario_id": t["scenario_id"],
                "pi": pi,
                "margin_point": lcb["margin_point"],
                "margin_lcb": lcb["margin_lcb"],
                "eps_0": lcb["eps_0"],
                "eps_1": lcb["eps_1"],
                "n_used": n_deg_fired,
                "min_n": mn["min_n"],
                "certifiable": mn["certifiable"],
                "dominates_finite_sample": lcb["dominates_finite_sample"],
            })

    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(
        {"confidence_delta": args.confidence_delta, "pi_grid": list(PI_GRID), "rows": rows},
        indent=2,
    ))
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(emit_tex(rows))

    print("T4 finite-sample risk-dominance sample-complexity:")
    for r in rows:
        nstar = "inf" if not math.isfinite(r["min_n"]) else str(int(r["min_n"]))
        print(
            f"  {str(r['scenario_id']):<16s} pi={r['pi']:.2f}  "
            f"M0={r['margin_point']:+.4f}  M_lcb={r['margin_lcb']:+.4f}  "
            f"n_used={r['n_used']:>5d}  n*={nstar:>8s}  "
            f"{'DOMINATES' if r['dominates_finite_sample'] else 'no'}"
        )
    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
