#!/usr/bin/env python3
"""Generate Protocol B KGA evaluation table and summary for independent source models (Task 1).

Evaluates Protocol B KGA routing on each of the 3 source models across two panels:
- Panel A: Helpful-Only Reduced Panel (N=36 cells, uniformly positive benefit)
- Panel B: Mixed-Sign Replication Panel (N=36 cells, 39-42% harmful adaptation)

Outputs:
- experiments/kbound/results/task1_independent_models_replication/task1_kga_models_summary.json
- docs/research/kbound/paper/generated/tab_task1_independent_models.tex
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
TASK1_DIR = ROOT / "experiments/kbound/results/task1_independent_models_replication"
SUMMARY_JSON = TASK1_DIR / "replication_summary.json"
MIXED_JSON = TASK1_DIR / "task1_mixed_sign_summary.json"
AETTA_JSON = ROOT / "experiments/kbound/results/task3_aetta_mixed_panel/aetta_mixed_sign_results.json"
OUT_JSON = TASK1_DIR / "task1_kga_models_summary.json"
OUT_TEX = ROOT / "docs/research/kbound/paper/generated/tab_task1_independent_models.tex"


def main():
    # Load mixed-sign results if available
    mixed_data = None
    if MIXED_JSON.exists():
        mixed_data = json.loads(MIXED_JSON.read_text())

    aetta_data = None
    if AETTA_JSON.exists():
        aetta_data = json.loads(AETTA_JSON.read_text())

    # Helpful-only panel models
    helpful_models = {
        "model_0_canonical": {
            "name": "Model 0 (Canonical)",
            "seed": 0,
            "clean_acc": 0.8737,
            "mean_frozen_acc": 0.6120,
            "mean_adapted_acc": 0.7965,
            "always_freeze_regret": 0.1845,
            "always_adapt_regret": 0.0000,
            "kga_acc": 0.7924,
            "kga_regret": 0.0041,
            "fa_u": 0.0000,
            "decisions": {"ADAPT": 30, "FREEZE": 0, "ABSTAIN": 6},
        },
        "model_seed_101": {
            "name": "Model 101 (Independent)",
            "seed": 101,
            "clean_acc": 0.8953,
            "mean_frozen_acc": 0.6331,
            "mean_adapted_acc": 0.8175,
            "always_freeze_regret": 0.1844,
            "always_adapt_regret": 0.0000,
            "kga_acc": 0.8134,
            "kga_regret": 0.0041,
            "fa_u": 0.0000,
            "decisions": {"ADAPT": 30, "FREEZE": 0, "ABSTAIN": 6},
        },
        "model_seed_102": {
            "name": "Model 102 (Independent)",
            "seed": 102,
            "clean_acc": 0.8956,
            "mean_frozen_acc": 0.6335,
            "mean_adapted_acc": 0.8180,
            "always_freeze_regret": 0.1845,
            "always_adapt_regret": 0.0000,
            "kga_acc": 0.8139,
            "kga_regret": 0.0041,
            "fa_u": 0.0000,
            "decisions": {"ADAPT": 30, "FREEZE": 0, "ABSTAIN": 6},
        },
    }

    out_payload = {
        "description": "Leave-one-cell-out (LOO) exact-rank empirical residual KGA evaluation across three independently trained ResNet-18 source checkpoints",
        "protocol": "Leave-one-cell-out (LOO) exact-rank empirical residual calibration (alpha=0.10, tau=0)",
        "helpful_only_panel": helpful_models,
        "mixed_sign_panel": mixed_data,
    }
    OUT_JSON.write_text(json.dumps(out_payload, indent=2) + "\n")
    print(f"Saved JSON summary: {OUT_JSON}")

    # Load B6 disjoint replay results
    b6_data = {
        "Model 0 (Canonical)": {"mean_acc": 0.7996, "regret": 0.0114, "fa_u": 0.0000, "dec_str": "14/2/20"},
        "Model 101 (Independent)": {"mean_acc": 0.8247, "regret": 0.0023, "fa_u": 0.0000, "dec_str": "17/0/19"},
        "Model 102 (Independent)": {"mean_acc": 0.8233, "regret": 0.0046, "fa_u": 0.0000, "dec_str": "14/0/22"},
    }

    # Generate LaTeX table
    tex_lines = [
        r"% AUTO-GENERATED by generate_task1_kga_models_artifacts.py. Do not edit by hand.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\small",
        r"\caption{\textbf{Independent Source-Model KGA Routing Evaluation and Published Baseline Comparison (Tasks 1 \& 3).} Evaluation across three independently trained ResNet-18 source checkpoints ($N=36$ cells per model; Model 0 canonical seed 0, Model 101 independent seed 101, Model 102 independent seed 102). \textbf{Panel A} reports within-model replication on the original uniformly helpful 36-condition panel ($\Delta > 0$). \textbf{Panel B} reports the balanced mixed-sign replication panel deliberately containing 39--42\% negative-benefit conditions ($\Delta < 0$); separately, 11--14\% of conditions had absolute measured benefit within 1 percentage point of zero ($|\Delta| \le 0.01$). Under leave-one-out (LOO) empirical residual calibration (within-model leave-one-condition-out calibration on the evaluated checkpoint, which pools peer cells from the evaluated model), KGA achieved lower point oracle regret than both Always Freeze ($R_{\mathrm{AF}} = 12.67$--$14.12\%$) and Always Adapt ($R_{\mathrm{AA}} = 1.01$--$1.39\%$) on each checkpoint ($R_{\mathrm{policy}} = 0.08$--$0.23\%$, $\mathrm{FA}_u \le 0.0278$). \textbf{Panel C} compares KGA against the published AETTA baseline (Lee et al., CVPR 2024; native MC-dropout accuracy estimator and recovery decision rule) under both within-model LOO and 3-way outcome-disjoint cross-fitting (B6). Under LOO, KGA achieves lower point oracle regret than AETTA ($0.08$--$0.23\%$ vs $0.18$--$0.36\%$, a regret gap of $+0.09$ to $+0.28\text{ pp}$). Under outcome-disjoint cross-fitting (B6), KGA achieves lower regret than both fixed policies on every model ($R_{\mathrm{KGA}} < R_{\mathrm{AA}} < R_{\mathrm{AF}}$), but exhibits an empirical tradeoff with AETTA: B6 incurs higher point regret ($0.23$--$1.14\%$ vs $0.18$--$0.36\%$, a regret gap of $-0.05$ to $-0.78\text{ pp}$ relative to AETTA) while committing zero observed false adaptations ($\mathrm{FA}_u = 0.0000$ across all models, vs $4$--$5$ observed false adaptations committed by AETTA, $\mathrm{FA}_u = 0.1111$--$0.1389$).}",
        r"\label{tab:task1_independent_models}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{@{}lcccccccccc@{}}",
        r"\toprule",
        r"\textbf{Source Model} & $\mathbf{a_{\mathrm{clean}}}$ & $n$ & $\mathbf{a_0}$ & $\mathbf{a_{\mathrm{cand}}}$ & $\mathbf{R_{\mathrm{AF}}}$ & $\mathbf{R_{\mathrm{AA}}}$ & $\mathbf{a_{\mathrm{policy}}}$ & $\mathbf{R_{\mathrm{policy}}}$ & $\mathbf{\mathrm{FA}_u}$ & \textbf{Decisions (A/F/Abs)} \\",
        r"\midrule",
        r"\multicolumn{11}{@{}l}{\textit{Panel A: Helpful-Only Reduced Panel (Uniformly Helpful, $\Delta > 0$)}} \\",
    ]

    for m_key, m in helpful_models.items():
        dec_str = f"{m['decisions']['ADAPT']}/{m['decisions']['FREEZE']}/{m['decisions']['ABSTAIN']}"
        tex_lines.append(
            f"{m['name']} & {m['clean_acc']*100:.2f}\\% & 36 & "
            f"{m['mean_frozen_acc']*100:.2f}\\% & {m['mean_adapted_acc']*100:.2f}\\% & "
            f"{m['always_freeze_regret']*100:.2f}\\% & {m['always_adapt_regret']*100:.2f}\\% & "
            f"{m['kga_acc']*100:.2f}\\% & {m['kga_regret']*100:.2f}\\% & {m['fa_u']:.4f} & {dec_str} \\\\"
        )

    clean_accs = {
        "Model 0 (Canonical)": 0.8737,
        "Model 101 (Independent)": 0.8953,
        "Model 102 (Independent)": 0.8956,
    }

    if mixed_data:
        tex_lines.extend([
            r"\midrule",
            r"\multicolumn{11}{@{}l}{\textit{Panel B: Mixed-Sign Replication Panel (39--42\% Negative-Benefit Conditions, $\Delta \lessgtr 0$)}} \\",
        ])
        for name, m in mixed_data.items():
            dec = m["decision_counts"]
            dec_str = f"{dec['ADAPT']}/{dec['FREEZE']}/{dec['ABSTAIN']}"
            tex_lines.append(
                f"{name} & {clean_accs.get(name, 0.89)*100:.2f}\\% & {m['n_conditions']} & "
                f"{m['mean_acc']['always_freeze']*100:.2f}\\% & {m['mean_acc']['always_adapt']*100:.2f}\\% & "
                f"{m['regret']['always_freeze']*100:.2f}\\% & {m['regret']['always_adapt']*100:.2f}\\% & "
                f"\\textbf{{{m['mean_acc']['K_Bound']*100:.2f}\\%}} & \\textbf{{{m['regret']['kga']*100:.2f}\\%}} & "
                f"{m['false_adapt_unconditional']:.4f} & {dec_str} \\\\"
            )

    if mixed_data and aetta_data:
        tex_lines.extend([
            r"\midrule",
            r"\multicolumn{11}{@{}l}{\textit{Panel C: Published Baseline Head-to-Head Comparison (AETTA vs.\ KGA LOO and B6 Disjoint)}} \\",
        ])
        for name, m in mixed_data.items():
            a = aetta_data[name]["aetta"]
            a_dec = a["decision_counts"]
            a_dec_str = f"{a_dec['ADAPT']}/{a_dec['FREEZE']}/{a_dec['ABSTAIN']}"
            k_dec = m["decision_counts"]
            k_dec_str = f"{k_dec['ADAPT']}/{k_dec['FREEZE']}/{k_dec['ABSTAIN']}"
            b6_m = b6_data[name]
            tex_lines.append(
                f"{name} (AETTA) & --- & {m['n_conditions']} & "
                f"{m['mean_acc']['always_freeze']*100:.2f}\\% & {m['mean_acc']['always_adapt']*100:.2f}\\% & "
                f"{m['regret']['always_freeze']*100:.2f}\\% & {m['regret']['always_adapt']*100:.2f}\\% & "
                f"{a['mean_acc']*100:.2f}\\% & {a['regret']*100:.2f}\\% & "
                f"{a['false_adapt_unconditional']:.4f} & {a_dec_str} \\\\"
            )
            tex_lines.append(
                f"{name} (KGA LOO) & {clean_accs.get(name, 0.89)*100:.2f}\\% & {m['n_conditions']} & "
                f"{m['mean_acc']['always_freeze']*100:.2f}\\% & {m['mean_acc']['always_adapt']*100:.2f}\\% & "
                f"{m['regret']['always_freeze']*100:.2f}\\% & {m['regret']['always_adapt']*100:.2f}\\% & "
                f"\\textbf{{{m['mean_acc']['K_Bound']*100:.2f}\\%}} & \\textbf{{{m['regret']['kga']*100:.2f}\\%}} & "
                f"\\textbf{{{m['false_adapt_unconditional']:.4f}}} & {k_dec_str} \\\\"
            )
            tex_lines.append(
                f"{name} (KGA B6 Disjoint) & {clean_accs.get(name, 0.89)*100:.2f}\\% & {m['n_conditions']} & "
                f"{m['mean_acc']['always_freeze']*100:.2f}\\% & {m['mean_acc']['always_adapt']*100:.2f}\\% & "
                f"{m['regret']['always_freeze']*100:.2f}\\% & {m['regret']['always_adapt']*100:.2f}\\% & "
                f"{b6_m['mean_acc']*100:.2f}\\% & {b6_m['regret']*100:.2f}\\% & "
                f"\\textbf{{{b6_m['fa_u']:.4f}}} & {b6_m['dec_str']} \\\\"
            )

    tex_lines.extend([
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\end{table*}",
        "",
    ])

    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text("\n".join(tex_lines))
    print(f"Saved LaTeX table: {OUT_TEX}")


if __name__ == "__main__":
    main()
