#!/usr/bin/env python3
"""Generate historical-release or current manuscript-revision identity blocks."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

EXPECTED_SCHEMA = "kbound_current_release_identity_v1"
REVISION_SCHEMA = "kbound_manuscript_revision_v1"
EXPECTED_ROLES = {
    "short_main": "Named compact main paper",
    "short_supplement": "Named standalone supplement",
    "tmlr": "Anonymous integrated TMLR review manuscript",
    "full_report": "Named full technical report",
}
ROLE_MACROS = {
    "short_main": "KBoundRoleShortMain",
    "short_supplement": "KBoundRoleShortSupplement",
    "tmlr": "KBoundRoleTMLR",
    "full_report": "KBoundRoleFullReport",
}
REVISION_ROLE = {"main_with_appendix": "Main paper with integrated appendices"}


def _require_text(document: dict[str, object], key: str) -> str:
    value = document.get(key)
    if not isinstance(value, str) or not value:
        raise ValueError(f"release identity requires nonempty string field {key!r}")
    return value


def _tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(character, character) for character in value)


def render(authority: dict[str, object], source_commit: str) -> str:
    schema = authority.get("schema")
    if schema not in (EXPECTED_SCHEMA, REVISION_SCHEMA):
        raise ValueError("unexpected current-release identity schema")
    is_revision = schema == REVISION_SCHEMA
    release_id = _require_text(authority, "revision_id" if is_revision else "release_id")
    source_closure = _require_text(authority, "revision_date" if is_revision else "source_closure")
    panel_sha = _require_text(authority, "canonical_panel_sha256")
    manifest_sha = _require_text(
        authority, "historical_evidence_manifest_sha256" if is_revision else "source_manifest_sha256"
    )
    if not re.fullmatch(r"[0-9a-f]{64}", panel_sha):
        raise ValueError("canonical panel SHA-256 must be 64 lowercase hex characters")
    if not re.fullmatch(r"[0-9a-f]{64}", manifest_sha):
        raise ValueError("source-manifest SHA-256 must be 64 lowercase hex characters")
    if not re.fullmatch(r"[0-9a-f]{12}", source_commit):
        raise ValueError("source snapshot commit must be exactly 12 lowercase hex characters")
    documents = authority.get("documents")
    expected_roles = {**EXPECTED_ROLES, **(REVISION_ROLE if is_revision else {})}
    if not isinstance(documents, dict) or set(documents) != set(expected_roles):
        raise ValueError(f"release identity must define exactly these document roles: {sorted(expected_roles)}")
    for key, expected_role in expected_roles.items():
        document = documents[key]
        if not isinstance(document, dict) or document.get("role") != expected_role:
            raise ValueError(f"release role mismatch for {key}")
        if document.get("anonymous") is not (key == "tmlr"):
            raise ValueError(f"anonymity-mode mismatch for {key}")

    lines = [
        "% AUTO-GENERATED by scripts/generate_release_identity.py. Do not edit by hand.",
        rf"\newcommand{{\KBoundReleaseID}}{{{_tex_escape(release_id)}}}",
        rf"\newcommand{{\KBoundSourceClosure}}{{{_tex_escape(source_closure)}}}",
        rf"\newcommand{{\KBoundCanonicalPanelSHA}}{{{panel_sha}}}",
        rf"\newcommand{{\KBoundSourceManifestSHA}}{{{manifest_sha}}}",
        rf"\newcommand{{\KBoundSourceSnapshotCommit}}{{{source_commit}}}",
    ]
    role_macros = {**ROLE_MACROS, **({"main_with_appendix": "KBoundRoleMainWithAppendix"} if is_revision else {})}
    for key, macro in role_macros.items():
        role = expected_roles[key]
        lines.append(rf"\newcommand{{\{macro}}}{{{_tex_escape(role)}}}")
    id_label = "Revision ID:" if is_revision else "Release ID:"
    date_label = "Revision date:" if is_revision else "Source closure:"
    manifest_label = "Historical evidence-manifest SHA-256:" if is_revision else "Source-manifest SHA-256:"
    commit_label = "Base commit (with subsequent manuscript edits):" if is_revision else "Source snapshot commit:"
    lines.extend(
        [
            r"\newcommand{\KBoundReleaseRule}{\par\smallskip\hrule\smallskip}",
            r"\newcommand{\KBoundNamedReleaseBlock}[1]{%",
            r"  \begin{center}\begin{minipage}{0.98\linewidth}\scriptsize",
            r"  \KBoundReleaseRule",
            rf"  \textbf{{{id_label}}} \KBoundReleaseID\quad",
            rf"  \textbf{{{date_label}}} \KBoundSourceClosure\\",
            r"  \textbf{Document role:} #1\\",
            r"  \textbf{Canonical panel SHA-256:} \hashtext{\KBoundCanonicalPanelSHA}\\",
            rf"  \textbf{{{manifest_label}}} \hashtext{{\KBoundSourceManifestSHA}}\\",
            rf"  \textbf{{{commit_label}}} \texttt{{\KBoundSourceSnapshotCommit}}",
            r"  \KBoundReleaseRule",
            r"  \end{minipage}\end{center}%",
            r"}",
            r"\newcommand{\KBoundAnonymousReleaseBlock}{%",
            r"  \begin{center}\begin{minipage}{0.98\linewidth}\scriptsize",
            r"  \KBoundReleaseRule",
            r"  \textbf{Anonymous build ID:} \KBoundReleaseID\\",
            r"  \textbf{Document role:} \KBoundRoleTMLR\\",
            r"  \textbf{Canonical panel SHA-256:} \hashtext{\KBoundCanonicalPanelSHA}\\",
            rf"  \textbf{{{manifest_label}}} \hashtext{{\KBoundSourceManifestSHA}}",
            r"  \KBoundReleaseRule",
            r"  \end{minipage}\end{center}%",
            r"}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    kbound_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--authority",
        type=Path,
        default=kbound_root / "paper/release/manuscript_revision.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=kbound_root / "paper/generated/current_release_identity.tex",
    )
    parser.add_argument("--source-snapshot-commit")
    arguments = parser.parse_args()
    authority = json.loads(arguments.authority.read_text(encoding="utf-8"))
    if not isinstance(authority, dict):
        raise ValueError("release identity authority must be a JSON object")
    source_commit = arguments.source_snapshot_commit or _require_text(
        authority, "base_commit" if authority.get("schema") == REVISION_SCHEMA else "source_snapshot_commit"
    )
    output = render(authority, source_commit)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(output, encoding="ascii")
    print(f"wrote {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
