#!/usr/bin/env python3
"""Generate the shared TeX release-identity block for all four manuscripts."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

EXPECTED_SCHEMA = "kbound_current_release_identity_v1"
EXPECTED_ROLES = {
    "short_main": "Named compact main paper",
    "short_supplement": "Named standalone supplement",
    "tmlr": "Anonymous integrated TMLR review manuscript",
    "full_report": "Named full technical report",
}
ROLE_MACROS = {
    "short_main": "KBoundRoleShortMain",
    "short_supplement": "KBoundRoleShortSupplement",
    "tmlr": "KBoundRoleTMLR",
    "full_report": "KBoundRoleFullReport",
}


def _require_text(document: dict[str, object], key: str) -> str:
    value = document.get(key)
    if not isinstance(value, str) or not value:
        raise ValueError(f"release identity requires nonempty string field {key!r}")
    return value


def _tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(character, character) for character in value)


def render(authority: dict[str, object], source_commit: str) -> str:
    if authority.get("schema") != EXPECTED_SCHEMA:
        raise ValueError("unexpected current-release identity schema")
    release_id = _require_text(authority, "release_id")
    source_closure = _require_text(authority, "source_closure")
    panel_sha = _require_text(authority, "canonical_panel_sha256")
    manifest_sha = _require_text(authority, "source_manifest_sha256")
    if not re.fullmatch(r"[0-9a-f]{64}", panel_sha):
        raise ValueError("canonical panel SHA-256 must be 64 lowercase hex characters")
    if not re.fullmatch(r"[0-9a-f]{64}", manifest_sha):
        raise ValueError("source-manifest SHA-256 must be 64 lowercase hex characters")
    if not re.fullmatch(r"[0-9a-f]{12}", source_commit):
        raise ValueError("source snapshot commit must be exactly 12 lowercase hex characters")
    documents = authority.get("documents")
    if not isinstance(documents, dict) or set(documents) != set(EXPECTED_ROLES):
        raise ValueError("release identity must define exactly the four current document roles")
    for key, expected_role in EXPECTED_ROLES.items():
        document = documents[key]
        if not isinstance(document, dict) or document.get("role") != expected_role:
            raise ValueError(f"release role mismatch for {key}")
        if document.get("anonymous") is not (key == "tmlr"):
            raise ValueError(f"anonymity-mode mismatch for {key}")

    lines = [
        "% AUTO-GENERATED by scripts/generate_release_identity.py. Do not edit by hand.",
        rf"\newcommand{{\KBoundReleaseID}}{{{_tex_escape(release_id)}}}",
        rf"\newcommand{{\KBoundSourceClosure}}{{{_tex_escape(source_closure)}}}",
        rf"\newcommand{{\KBoundCanonicalPanelSHA}}{{{panel_sha}}}",
        rf"\newcommand{{\KBoundSourceManifestSHA}}{{{manifest_sha}}}",
        rf"\newcommand{{\KBoundSourceSnapshotCommit}}{{{source_commit}}}",
    ]
    for key, macro in ROLE_MACROS.items():
        role = EXPECTED_ROLES[key]
        lines.append(rf"\newcommand{{\{macro}}}{{{_tex_escape(role)}}}")
    lines.extend(
        [
            r"\newcommand{\KBoundReleaseRule}{\par\smallskip\hrule\smallskip}",
            r"\newcommand{\KBoundNamedReleaseBlock}[1]{%",
            r"  \begin{center}\begin{minipage}{0.98\linewidth}\scriptsize",
            r"  \KBoundReleaseRule",
            r"  \textbf{Release ID:} \KBoundReleaseID\quad",
            r"  \textbf{Source closure:} \KBoundSourceClosure\\",
            r"  \textbf{Document role:} #1\\",
            r"  \textbf{Canonical panel SHA-256:} \hashtext{\KBoundCanonicalPanelSHA}\\",
            r"  \textbf{Source-manifest SHA-256:} \hashtext{\KBoundSourceManifestSHA}\\",
            r"  \textbf{Source snapshot commit:} \texttt{\KBoundSourceSnapshotCommit}",
            r"  \KBoundReleaseRule",
            r"  \end{minipage}\end{center}%",
            r"}",
            r"\newcommand{\KBoundAnonymousReleaseBlock}{%",
            r"  \begin{center}\begin{minipage}{0.98\linewidth}\scriptsize",
            r"  \KBoundReleaseRule",
            r"  \textbf{Anonymous build ID:} \KBoundReleaseID\\",
            r"  \textbf{Document role:} \KBoundRoleTMLR\\",
            r"  \textbf{Canonical panel SHA-256:} \hashtext{\KBoundCanonicalPanelSHA}\\",
            r"  \textbf{Source-manifest SHA-256:} \hashtext{\KBoundSourceManifestSHA}",
            r"  \KBoundReleaseRule",
            r"  \end{minipage}\end{center}%",
            r"}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    kbound_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--authority",
        type=Path,
        default=kbound_root / "paper/release/current_release.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=kbound_root / "paper/generated/current_release_identity.tex",
    )
    parser.add_argument("--source-snapshot-commit")
    arguments = parser.parse_args()
    authority = json.loads(arguments.authority.read_text(encoding="utf-8"))
    if not isinstance(authority, dict):
        raise ValueError("release identity authority must be a JSON object")
    source_commit = arguments.source_snapshot_commit or _require_text(
        authority, "source_snapshot_commit"
    )
    output = render(authority, source_commit)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(output, encoding="ascii")
    print(f"wrote {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
