#!/usr/bin/env python3
"""Emit paper result-table numbers as LaTeX macros from results_source.json.

    python docs/research/kbound/scripts/make_tables.py

Single source of truth -> docs/research/kbound/paper/generated/kbound_numbers.tex.
After a re-run, refresh results_source.json (out-of-fold numbers), run this, rebuild.
"""
import json, os
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
SRC  = os.path.join(ROOT, "docs/research/kbound/results_source.json")
OUT  = os.path.join(ROOT, "docs/research/kbound/paper/generated/kbound_numbers.tex")
d = json.load(open(SRC)); ns = d["natural_shifts"]
f   = lambda x: f"{x:.4f}"
pct = lambda x: f"{x*100:.0f}"
oh, iw = ns["officehome_M_v2"], ns["iwildcam_H_v2"]
M = {
 "OHadapt": f(oh["regret_adapt"]), "OHfreeze": f(oh["regret_freeze"]), "OHkga": f(oh["regret_kga"]), "OHfa": pct(oh["false_adapt"]),
 "iWadapt": f(iw["regret_adapt"]), "iWfreeze": f(iw["regret_freeze"]), "iWkga": f(iw["regret_kga"]), "iWfa": pct(iw["false_adapt"]),
}
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as fh:
    fh.write("% AUTO-GENERATED by scripts/make_tables.py from results_source.json. Do not edit by hand.\n")
    for k, v in M.items():
        fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print("wrote", OUT)
for k, v in M.items(): print(f"  \\{k} = {v}")
