#!/usr/bin/env python3
"""
Build multi-seed natural-shift forest figure + LaTeX table from extract_multiseed_natural
aggregate JSONs (Camelyon-compatible).

  python3 make_multiseed_natural_forest.py \\
      --agg experiments/kbound/results/multiseed/*/extracted/multiseed_*.json \\
         experiments/kbound/results/multiseed/multiseed_camelyon17_*.json \\
      --out-fig docs/research/kbound/figures/fig_natural_forest_multiseed.png \\
      --out-tex docs/research/kbound/figures/tab_multiseed_natural.tex

Does not overwrite the locked single-run OOF forest (fig_natural_forest.png).
Missing tracks are skipped with a warning — no fabricated rows.
"""
from __future__ import annotations

import argparse
import glob
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

HERE = os.path.abspath(os.path.dirname(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))  # scripts -> repo root
FIG_DIR = os.path.join(REPO, "docs", "research", "kbound", "figures")
GREEN, GRAY = "#1b7837", "#888888"

DISPLAY = {
    "officehome": "Office-Home",
    "iwildcam": "iWildCam",
    "rxrx1": "RxRx1",
    "camelyon17": "Camelyon17",
}


def _load_aggs(patterns):
    files = []
    for p in patterns:
        files.extend(sorted(glob.glob(p, recursive=True)))
    by = {}
    for f in files:
        if not f.endswith(".json"):
            continue
        if "extract_manifest" in os.path.basename(f):
            continue
        if not os.path.basename(f).startswith("multiseed_"):
            continue
        d = json.load(open(f))
        if "gap_vs_adapt" not in d and "regret_kga" not in d:
            continue
        key = (d.get("dataset"), d.get("candidate"))
        # prefer file that already has forest gaps
        prev = by.get(key)
        if prev is None or ("gap_vs_adapt" in d and "gap_vs_adapt" not in prev[1]):
            by[key] = (f, d)
    return [by[k] for k in sorted(by)]


def _gaps(d):
    """Return (label_prefix, adapt_mean/lo/hi, freeze_mean/lo/hi)."""
    ds = DISPLAY.get(d["dataset"], d["dataset"])
    cand = d.get("candidate", "")
    prefix = f"{ds} ({cand})" if cand else ds
    if "gap_vs_adapt" in d and "gap_vs_freeze" in d:
        ga, gf = d["gap_vs_adapt"], d["gap_vs_freeze"]
        return prefix, (ga["mean"], ga["ci95"][0], ga["ci95"][1]), (
            gf["mean"], gf["ci95"][0], gf["ci95"][1]
        )
    # Fallback for older Camelyon aggregates: reconstruct means from regrets only
    # (CIs unavailable → point with zero-width — marked in caption via note).
    rk, ra, rf = d["regret_kga"][0], d["regret_adapt"][0], d["regret_freeze"][0]
    return prefix, (ra - rk, ra - rk, ra - rk), (rf - rk, rf - rk, rf - rk)


def forest(rows, out_fig):
    # rows: list of (label, m, lo, hi)
    fig_h = max(3.2, 0.45 * len(rows) + 1.2)
    fig, ax = plt.subplots(figsize=(6.8, fig_h))
    y = list(range(len(rows)))[::-1]
    for yi, (lab, m, lo, hi) in zip(y, rows):
        c = GREEN if lo > 0 else GRAY
        ax.plot([lo, hi], [yi, yi], color=c, lw=3, solid_capstyle="round")
        ax.plot(m, yi, "o", color=c, ms=7)
    ax.axvline(0, color="k", lw=1, ls="--")
    ax.set_yticks(y)
    ax.set_yticklabels([r[0] for r in rows], fontsize=8)
    ax.set_xlabel("Regret reduction by KGA (95% paired bootstrap CI)")
    ax.set_title(
        "Multi-seed natural-shift safety (per-seed LOO KGA; not Protocol OOF locks)",
        fontsize=10,
    )
    ax.legend(
        handles=[
            Patch(color=GREEN, label="CI excludes 0 (beats policy)"),
            Patch(color=GRAY, label="CI includes 0 (ties / inconclusive)"),
        ],
        fontsize=7.5, loc="lower right", framealpha=0.9,
    )
    ax.margins(y=0.08)
    os.makedirs(os.path.dirname(out_fig) or ".", exist_ok=True)
    fig.tight_layout()
    fig.savefig(out_fig, dpi=200)
    plt.close(fig)
    print("wrote", out_fig)


def latex_table(aggs, out_tex):
    lines = [
        r"% Auto-generated by make_multiseed_natural_forest.py — do not hand-edit.",
        r"\begin{tabular}{lccccl}",
        r"\toprule",
        r"track (candidate) & seeds & KGA regret & adapt & freeze & "
        r"$\mathrm{FA}_{\mathrm u}$ & verdict \\",
        r"\midrule",
    ]
    for _, d in aggs:
        ds = DISPLAY.get(d["dataset"], d["dataset"])
        cand = d.get("candidate", "")
        rk = d["regret_kga"]
        lines.append(
            f"{ds} ({cand}) & {d['n_seeds']} & "
            f"{rk[0]:.4f}$\\pm${rk[1]:.4f} & "
            f"{d['regret_adapt'][0]:.4f} & {d['regret_freeze'][0]:.4f} & "
            f"{d['FA_u_max']:.3f} & {d['verdict']} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    os.makedirs(os.path.dirname(out_tex) or ".", exist_ok=True)
    open(out_tex, "w").write("\n".join(lines))
    print("wrote", out_tex)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--agg", nargs="+", required=True,
                    help="multiseed_*.json paths or globs")
    ap.add_argument("--out-fig", default=os.path.join(
        FIG_DIR, "fig_natural_forest_multiseed.png"))
    ap.add_argument("--out-tex", default=os.path.join(
        FIG_DIR, "tab_multiseed_natural.tex"))
    ap.add_argument("--out-json", default=os.path.join(
        FIG_DIR, "multiseed_natural_forest_payload.json"))
    a = ap.parse_args()

    aggs = _load_aggs(a.agg)
    if not aggs:
        raise SystemExit(f"no aggregate JSONs matched: {a.agg}")

    forest_rows = []
    payload = []
    for path, d in aggs:
        prefix, ga, gf = _gaps(d)
        forest_rows.append((f"{prefix}\nvs always-adapt", *ga))
        forest_rows.append((f"{prefix}\nvs always-freeze", *gf))
        payload.append({"source": path, **{k: d[k] for k in d if k != "latex_row"}})

    forest(forest_rows, a.out_fig)
    latex_table(aggs, a.out_tex)
    json.dump({"rows": payload, "figure": a.out_fig, "table": a.out_tex},
              open(a.out_json, "w"), indent=2)
    print("wrote", a.out_json)
    print(f"tracks: {len(aggs)} aggregates -> {len(forest_rows)} forest rows")


if __name__ == "__main__":
    main()
