#!/usr/bin/env python3
"""Render completed next-phase studies from byte-identical, pinned summaries.

This script does not fit, score, select policies, or rewrite experiment evidence.
All authorities are checked before any presentation output is written.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

KBOUND = Path(__file__).resolve().parents[1]
SOURCE_DIR = KBOUND / "next_phase/table_sources"
OUTPUT_DIR = KBOUND / "paper/generated"
AUTHORITIES = {
    "calibration_value_summary.json": (
        "output/next_phase/calibration_value_v1/FINAL_RESULTS_SUMMARY.json",
        "1b2f00d9dba566d35e86311f0c5e4e63833c333b702cee11c29eeb2411d9a191",
    ),
    "calibration_group_risk.json": (
        "output/next_phase/calibration_value_v1/group_risk_report_05/heldout_semantic_group_risk.json",
        "090f334156219e6f4e26cdcda23859420769ba1c65bbfebd4b62ed15648c2a3a",
    ),
    "paired_transport_summary.json": (
        "output/next_phase/paired_transport_v1/summary.json",
        "e24468294bdbc1308e3def160fe83b1a56c6c306f276e068a83db8c5b4227b29",
    ),
}
TABLE_NAMES = (
    "tab_nextphase_calibration.tex",
    "tab_nextphase_group_risk.tex",
    "tab_nextphase_paired_transport.tex",
)


def _load(source_dir: Path) -> dict[str, Any]:
    result = {}
    for name, (_, expected) in AUTHORITIES.items():
        data = (source_dir / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != expected:
            raise ValueError(f"authority hash mismatch: {name}")
        result[name] = json.loads(data)
    return result


def _comments(authority: str) -> list[str]:
    original, digest = AUTHORITIES[authority]
    return [
        "% Generated by scripts/make_next_phase_tables.py; do not edit numerical rows.",
        f"% Original authority: {original}",
        f"% Byte-identical rendering copy: next_phase/table_sources/{authority}",
        f"% SHA-256: {digest}",
    ]


def _one(rows: list[dict[str, Any]], **criteria: Any) -> dict[str, Any]:
    matches = [row for row in rows if all(row.get(key) == value for key, value in criteria.items())]
    if len(matches) != 1:
        raise ValueError(f"expected one row for {criteria}, found {len(matches)}")
    return matches[0]


def _calibration(data: dict[str, Any]) -> str:
    cohorts = [
        ("cifar10c/eata", "environment", "CIFAR EATA / corruption"),
        ("cifar10c/sar", "environment", "CIFAR SAR / corruption"),
        ("cifar10c/tent", "environment", "CIFAR Tent / corruption"),
        ("imagenetc/eata", "environment", "ImageNet EATA / corruption"),
        ("imagenetc/sar", "environment", "ImageNet SAR / corruption"),
        ("imagenetc/tent", "environment", "ImageNet Tent / corruption"),
        ("mixed_checkpoints/tent", "checkpoint", "Mixed Tent / checkpoint"),
        ("mixed_checkpoints/tent", "joint", "Mixed Tent / checkpoint + corruption"),
    ]
    arms = ["point", "fixed_margin_harm5", "constant_cell_alpha0.1", "scaled_cell_alpha0.1"]
    lines = _comments("calibration_value_summary.json") + [
        r"\begin{tabular}{@{}lrrrrrrr@{}}",
        r"\toprule",
        r"Cohort / outer hold-out & Cells & Point & Margin & Constant & Scaled & Inclusion C & Inclusion S \\",
        r"\midrule",
    ]
    for dataset, kind, label in cohorts:
        rows = [_one(data["rows"], dataset=dataset, kind=kind, arm=arm)["metrics"] for arm in arms]
        if len({row["n"] for row in rows}) != 1:
            raise ValueError("arm denominators disagree")
        losses = [f"{100 * row['harm_weighted_losses']['5']:.4f}" for row in rows]
        inclusion = [f"{100 * row['interval_inclusion']:.2f}\\%" for row in rows[2:]]
        lines.append(" & ".join([label, str(rows[0]["n"]), *losses, *inclusion]) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def _group_risk(data: dict[str, Any]) -> str:
    lines = _comments("calibration_group_risk.json") + [
        r"\begin{tabular}{@{}lrrrrr@{}}",
        r"\toprule",
        r"CIFAR candidate & Groups & Exposed & Error groups & Conditional group error & Cell error \\",
        r"\midrule",
    ]
    for method in ("eata", "sar", "tent"):
        row = _one(data["rows"], dataset=f"cifar10c/{method}", kind="environment", arm="conditional_risk0.2")
        group = row["heldout_group_metrics"]
        cell = row["equal_cell_comparison"]
        values = [
            "Tent" if method == "tent" else method.upper(),
            str(group["n_all_groups"]),
            str(group["n_adapted_groups"]),
            str(group["n_error_groups"]),
            f"{100 * group['false_adapt_conditional']:.2f}\\%",
            f"{100 * cell['false_adapt_conditional']:.2f}\\%",
        ]
        lines.append(" & ".join(values) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def _paired(data: dict[str, Any]) -> str:
    cases = [
        ("paired_cancellation", 100, 0.0, "Paired cancellation"),
        ("same_evidence_full_violation", 100, 0.0, "Same evidence, violated assumption"),
        ("fullrank_near_null", 100, 0.0, "Near null"),
        ("fullrank_near_null", 10000, 0.0, "Near null"),
        ("fullrank_helpful", 1000, 0.0, "Helpful"),
        ("fullrank_helpful", 1000, 0.1, "Helpful, wider sensitivity"),
        ("fullrank_harmful", 1000, 0.0, "Harmful"),
    ]
    lines = _comments("paired_transport_summary.json") + [
        r"\begin{tabular}{@{}lrrrrrr@{}}",
        r"\toprule",
        r"Synthetic regime & $n$/class & $\rho$ & True $\Delta$ & Paired A/F/U & Separate A/F/U & Plug-in A/F/U \\",
        r"\midrule",
    ]
    for scenario, n, rho, label in cases:
        rows = [
            _one(data["rows"], scenario=scenario, n_per_class=n, rho=rho, arm=arm)
            for arm in ("paired_lp", "separate_accuracy", "plugin")
        ]
        if any(row["trials"] != 60 for row in rows):
            raise ValueError("unexpected synthetic trial denominator")
        counts = [f"{row['adapt_count']}/{row['freeze_count']}/{row['abstain_count']}" for row in rows]
        lines.append(" & ".join([label, str(n), f"{rho:.1f}", f"{rows[0]['true_benefit']:.2f}", *counts]) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def build(source_dir: Path, output_dir: Path) -> None:
    sources = _load(source_dir)
    rendered = (
        _calibration(sources["calibration_value_summary.json"]),
        _group_risk(sources["calibration_group_risk.json"]),
        _paired(sources["paired_transport_summary.json"]),
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in zip(TABLE_NAMES, rendered, strict=True):
        (output_dir / name).write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, default=SOURCE_DIR)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR)
    args = parser.parse_args()
    build(args.source_dir, args.output_dir)


if __name__ == "__main__":
    main()
