"""Regenerate paper figures.

Figures are produced as a side effect of the experiment scripts in ../../scripts/
(each writes its PNGs into ../final/). This dispatcher just documents and re-invokes
them. Run the experiments first (see ../../scripts/99_reproduce_kbound.py).
"""
MAP = {
    "fig_certificate.png": "knowability_experiment.py",
    "fig_kbound_harmful.png": "kbound_harmful_regime.py",
    "fig_mixed_policies.png": "mixed_regime_experiment.py",
    "fig_witness_clean.png": "kbound_full_experiments.py",
    "fig_cifar_tent.png": "cifar_tent_mps.py",
    "fig_tta_collapse.png": "tta_collapse_experiment.py",
}
if __name__ == "__main__":
    print("Figures are generated by these scripts (run them to refresh ../final/):")
    for fig, scr in MAP.items():
        print(f"  {fig:28s} <- scripts/{scr}")
